<?php $this->placeholder('heading')->captureStart(); ?>
Permission Error
<?php $this->placeholder('heading')->captureEnd() ;?>

<?php $this->placeholder('breadcrumb')->captureStart(); ?>
<li class="active">
	<a href="javascript: void(0);">Permission Error</a>
</li>
<?php $this->placeholder('breadcrumb')->captureEnd() ;?>

<?php $this->placeholder('header')->captureStart('SET'); ?>
<h1>
	Permission Error
</h1>
<?php $this->placeholder('header')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart(); ?>
<div class="alert alert-danger">
	We're sorry, you do not have permission to access the resource <strong><?php echo $this->resource; ?></strong>
	<?php if(!empty($this->action)) { ?>
	with the action <strong><?php echo $this->action; ?></strong>
	<?php } ?>
</div>
<?php $this->placeholder('content')->captureEnd(); ?>