<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	var status_text_active = 'Active';
	var status_text_closed = 'Closed';
	var status_text_deleted = 'Deleted';

	$(document).ready(function() {
		var table = null;
		$("#contracts_a").on('shown.bs.tab', function() {
			if (!table) {
				table = $("#contracts").DataTable({
					serverSide: true,			
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
							d['vendor_id'] = '<?php echo $this->id; ?>';

							d['!status'] = status_text_deleted;
							//on initial load or "Active"
							if(typeof $("#status").val() == 'undefined' || $("#status").val() == status_text_active) {
								d['!status'] = [status_text_closed, status_text_deleted];
							}
							else if($("#status").val() == status_text_closed) {
								d['status'] = status_text_closed;
							}
						},
						url: "<?php echo $this->basePath('contract/rest/contracts/'); ?>"
					},
					iDisplayLength: 25,
					stateSave: false,
					deferRender: true,
					searchDelay: 500,
					responsive: {
						details: {
							renderer: function(api, row, columns) {
								return $.datatables_utils.responsive_renderer(api, row, columns, table);
							}
						}
					},
					columns: [
					    { data: 'id', searchable: false, render: function(val, type, data, options) {
							return "<div class='inline pos-rel'>"
								+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
									+ "Actions "
									+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
								+ "</button>"
								+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>"
									<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'view')) { ?>
									+ "<li>"
										+ "<a data-rel='tooltip' href='<?php echo $this->basePath('contract/contracts/view/'); ?>" + val + "'>"
											+ "<span class='green'>"
												+ "<i class='ace-icon fa fa-image bigger-120'></i>"
												+ " View"
											+ "</span>"
										+ "</a>"
									+ "</li>"
									<?php } ?>
								+ "</ul>"
							+ "</div>"; 
					    }},
					    { data: 'status', searchable: true },
					    { data: 'description', searchable: true, render: $.datatables_utils.format_na },
					    { data: 'department_full', searchable: true },
					    { data: 'start_date', searchable: true },
					    { data: 'end_date', searchable: true }
					],
					order: [
						[ 4, "desc" ]
					]
				});

				$('#contracts_filter').prepend(
					"Status: "
					+ "<select id='status' name='status'>"
					+ "<option value='All'>All</option>"
					+ "<option value='Active' selected>Active</option>"
					+ "<option value='Closed'>Closed</option>"
					+ "</select> "
				);

			} else {
				table.responsive.recalc();
			}
			
			$(document).on('change', '#status', function() {
				table.draw();
			});
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="contracts" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th>Status</th>
					<th>Description</th>
					<th>Department</th>
					<th>Start Date</th>
					<th>End Date</th>
				</tr>
			</thead>
		</table>
	</div>
</div>