<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		$('#edit_vendor').on('submit', function() {
			var id = $("#edit_vendor_id").val();
			var name = $("#edit_vendor_name").val();
			var notes = $("#edit_vendor_notes").val();
			var active = $("#edit_vendor_active").prop('checked') ? 1 : 0;
			
			$("#edit_vendor_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Editing vendor...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('contract/vendors/edit/'); ?>',
				data: { 
					id: id,
					name: name,
					notes: notes,
					active: active
				}
			}).done(function(data) {
				if (data.status == 1) {
					$("#edit_vendor_message")
						.removeClass("label-default")
						.addClass("label-success")
						.html("Successfully edited vendor");
					
					setTimeout(function() {
						$("#edit_vendor_message").hide();
						$("#edit-vendor-modal").modal('hide');

						if($("#edit_vendor_reload").val()==1) {
							location.reload();
						}
						
						reloadVendorsTable();
					}, 1000);
				} else {
					$("#edit_vendor_message")
						.removeClass("label-default")
						.addClass("label-danger");
						
					if (data.error) {
						if ($.isArray(data.error)) {
							$("#edit_vendor_message").html(data.error.join('<br />'));
						} else {
							$("#edit_vendor_message").html(data.error);
						}
					} else {
						$("#edit_vendor_message").html("Unable to edit vendor, please try again");
					}
				}
			}).fail(function(error) {
				$("#edit_vendor_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html("Unable to edit vendor, please try again");
			});
			
			// prevent the page submit
			return false;
		});
	});
	
	function editVendor(row) {
		$("#edit_vendor_message").hide();
		var data = $("#vendors").dataTable().fnGetData(row);
		if (data) {
			$("#edit_vendor_id").val(data.id);
			$("#edit_vendor_reload").val(0);
			$("#edit_vendor_name").val(data.name);
			$("#edit_vendor_notes").val(data.notes);
			$("#edit_vendor_active").prop('checked', (data.active==1));

			$('#edit-vendor-modal').modal('show');
		}
	}

	function editVendorView() {
		$("#edit_vendor_message").hide();
		
		$("#edit_vendor_id").val('<?php echo $this->id; ?>');
		$("#edit_vendor_reload").val(1);
		$("#edit_vendor_name").val('<?php echo $this->name; ?>');
		//notes set below
		$("#edit_vendor_active").prop('checked', (<?php echo ($this->active) ? $this->active : 0; ?>));
		
		$('#edit-vendor-modal').modal('show');
	}
	
	function reloadVendorsTable() {
		if($.fn.DataTable.isDataTable('#vendors')) {
			$("#vendors").dataTable().api().ajax.reload();
        }
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="edit-vendor-modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Edit Vendor
				</div>
			</div>
			<form id="edit_vendor" class="form-horizontal">
				<div class="modal-body no-padding">				
					<div class="row no-padding no-margin">
						<div class="alert alert-warning">
							All fields with an <i class="ace-icon fa fa-asterisk red"></i> are required.
						</div>
					</div>
					<input type='hidden' id='edit_vendor_id' name='edit_vendor_id'>
					<input type="hidden" id="edit_vendor_reload" name="edit_vendor_reload" value="0" />
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="edit_vendor_name">Name </label>
						<div class="col-sm-8">
							<span class="block input-icon input-icon-right">
								<input type="text"
									   id="edit_vendor_name"
									   name="edit_vendor_name"
									   placeholder="Vendor Name"
									   class="width-100" />
							</span>
						</div>
					</div>
					
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="edit_vendor_notes">Notes </label>
						<div class="col-sm-8">
							<span class="block input-icon input-icon-right">
								<textarea
									   id="edit_vendor_notes"
									   name="edit_vendor_notes"
									   placeholder="Notes"
									   class="width-100"><?php echo $this->notes; ?></textarea>
								<span class='lbl' style='vertical-align: text-top;'></span>
							</span>
						</div>
					</div>
					
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="edit_vendor_active">Active? </label>
						<div class="col-sm-8">
							<span class="block input-icon input-icon-right">
								<input name='edit_vendor_active'
									id='edit_vendor_active'
									type='checkbox'
									class='ace ace-switch ace-switch-2'
									value='1' />
								<span class='lbl' style='vertical-align: text-top;'></span>
							</span>
						</div>
					</div>
				</div>
				<div class="space-6"></div>
				<div class="modal-footer">
					<button class="btn btn-sm pull-left"
							type="button"
							data-dismiss="modal">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</button>
					<button class="btn btn-sm btn-primary pull-left"
							type="submit">
						<i class="ace-icon fa fa-check bigger-125"></i>
						Submit
					</button>
					<div id="edit_vendor_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>