<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		$('#add_schedule').on('submit', function() {
			var name = $("#add_schedule_name").val();
			var days = $("#add_schedule_days").val()
			
			$("#add_schedule_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Adding new notification schedule...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('contract/notification-schedules/add/'); ?>',
				data: { 
					name: name,
					days: days
				}
			}).done(function(data) {
				if (data.status == 1) {
					$("#add_schedule_message")
						.removeClass("label-default")
						.addClass("label-success")
						.html("Successfully added new notification schedule");
					
					setTimeout(function() {
						$("#add_schedule_message").hide();
						
						$("#add-schedule-modal").modal('hide');
						reloadSchedulesTable();
					}, 1000);
				} else {
					$("#add_schedule_message")
						.removeClass("label-default")
						.addClass("label-danger");
						
					if (data.error) {
						if ($.isArray(data.error)) {
							$("#add_schedule_message").html(data.error.join('<br />'));
						} else {
							$("#add_schedule_message").html(data.error);
						}
					} else {
						$("#add_schedule_message").html("Unable to add new notification schedule, please try again");
					}
				}
			}).fail(function(error) {
				$("#add_schedule_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html("Unable to add new notification schedule, please try again");
			});
			
			// prevent the page submit
			return false;
		});
	});
	
	function addSchedule() {
		$("#add_schedule_message").hide();
		$("#add_schedule_name").val('');
		$("#add_schedule_days").val('');
	}
	
	function reloadSchedulesTable() {
		$("#notification_schedules").dataTable().api().ajax.reload();
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="add-schedule-modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Add New Notification Schedule
				</div>
			</div>
			<form id="add_schedule" class="form-horizontal">
				<div class="modal-body no-padding">				
					<div class="row no-padding no-margin">
						<div class="alert alert-warning">
							All fields with an <i class="ace-icon fa fa-asterisk red"></i> are required.  Provide the Notification Schedule name.
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="add_schedule_name">Name </label>
						<div class="col-sm-8">
							<span class="block input-icon input-icon-right">
								<input type="text"
									   id="add_schedule_name"
									   name="add_schedule_name"
									   placeholder="New Notification Schedule Name"
									   class="width-100" />
							</span>
						</div>
					</div>
								
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="add_schedule_days">Days </label>
						<div class="col-sm-8">
							<span class="block input-icon input-icon-right">
								<input type="text"
									   id="add_schedule_days"
									   name="add_schedule_days"
									   placeholder="Comma Separated Days"
									   class="width-100" />
							</span>
						</div>
					</div>
				</div>
				<div class="space-6"></div>
				<div class="modal-footer">
					<button class="btn btn-sm pull-left"
							type="button"
							data-dismiss="modal">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</button>
					<button class="btn btn-sm btn-primary pull-left"
							type="submit">
						<i class="ace-icon fa fa-plus bigger-125"></i>
						Add
					</button>
					<div id="add_schedule_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>