<?php $this->placeholder('heading')->captureStart('SET'); ?>
BRICS Service Request Created
<?php $this->placeholder('heading')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<table class="table-row" width="600" bgcolor="#FFFFFF" style="table-layout: fixed; background-color: #ffffff; width: 600px;" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td class="table-row-td" style="font-family: Arial, sans-serif; line-height: 19px; color: #444444; font-size: 13px; font-weight: normal; padding-left: 36px; padding-right: 36px;" valign="top" align="left">
   <table class="table-col" align="left" width="528" cellspacing="0" cellpadding="0" border="0" style="table-layout: fixed; width: 528px;"><tbody><tr><td class="table-col-td" width="528" style="font-family: Arial, sans-serif; line-height: 19px; color: #444444; font-size: 13px; font-weight: normal;" valign="top" align="left">
	 <table class="header-row" width="528" cellspacing="0" cellpadding="0" border="0" style="table-layout: fixed; width: 528px;"><tbody><tr><td class="header-row-td" width="528" style="font-size: 28px; margin: 0px; font-family: Arial, sans-serif; font-weight: normal; line-height: 19px; color: #888888; padding-bottom: 10px; padding-top: 15px;" valign="top" align="left">Hi <?php echo $this->user; ?>,</td></tr></tbody></table>
	 <table class="header-row" width="528" cellspacing="0" cellpadding="0" border="0" style="table-layout: fixed; width: 528px;"><tbody><tr><td class="header-row-td" width="528" style="font-family: Arial, sans-serif; font-weight: lighter; line-height: 19px; color: #666666; margin: 0px; font-size: 18px; padding-bottom: 8px; padding-top: 10px;" valign="top" align="left">Your Service Request in BRICS has been created.</td></tr></tbody></table>
   </td></tr></tbody></table>
</td></tr></tbody></table>
	
<table class="table-row" width="600" bgcolor="#FFFFFF" style="table-layout: fixed; background-color: #ffffff; width: 600px;" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td class="table-row-td" style="font-family: Arial, sans-serif; line-height: 19px; color: #444444; font-size: 13px; font-weight: normal; padding-left: 36px; padding-right: 36px;" valign="top" align="left">
    <table class="table-col" align="left" width="528" cellspacing="0" cellpadding="0" border="0" style="table-layout: fixed; width: 528px;"><tbody><tr><td class="table-col-td" width="528" style="font-family: Arial, sans-serif; line-height: 19px; color: #444444; font-size: 13px; font-weight: normal; width: 528px;" valign="top" align="left">
        <table class="header-row" width="528" cellspacing="0" cellpadding="0" border="0" style="table-layout: fixed; width: 528px;"><tbody><tr><td class="header-row-td" width="528" style="font-family: Arial, sans-serif; font-weight: normal; line-height: 19px; color: #888888; margin: 0px; font-size: 18px; padding-bottom: 8px; padding-top: 10px;" valign="top" align="left">
            Please use the Service Request number <strong><?php echo $this->osr; ?></strong> to track all progress.<br /><br />
            Our team will review your Service Request and will be in contact within 24 hours.  If we were not able to reach you within that time frame, please contact our support team directly via email at <a href="mailto:wwie-osr@arris.com?subject=OSR <?php echo $this->osr; ?> Update Request">wwie-osr@arris.com</a>.
        </td></tr></tbody></table>
    </td></tr></tbody></table>
</td></tr></tbody></table>
<?php $this->placeholder('content')->captureEnd(); ?>