<?php
$route = $this->route()->getRouteName();
$controller = $this->route()->getControllerName();
$action = $this->route()->getAction();

$routeactive = ($route == "auth/default" && $controller == 'security') ? 'active' : '';
$routeopen = ($routeactive == 'active') ? 'open' : '';
$routearrow = ($routeopen == 'open') ? 'fa-angle-up' : 'fa-angle-down';
?>

<?php $auth_ns = $this->config()->getConfig('auth', 'auth_ns'); ?>

<?php if ($this->authorization()->isPermittedIn('Auth::Security', array('roles', 'resources', 'permissions'), $auth_ns)) { ?>
	<?php if ($this->layout_type == 'h') { ?>
	<li class="<?php echo $routeactive . ' ' . $routeopen . ' hover'; ?>">
	<?php } else { ?>
	<li class="<?php echo $routeactive; ?> <?php echo $routeopen; ?>">
	<?php } ?>	
		<a href="#" class="dropdown-toggle">
			<i class="menu-icon fa fa-lock"></i>
			<span class="menu-text">
				Security
			</span>
			<b class="arrow <?php echo ($this->layout_type != 'h') ? "fa {$routearrow}" : ''; ?>"></b>
		</a>
		<b class="arrow"></b>
		<ul class="submenu">
			<?php if ($this->authorization()->isPermitted('Auth::Security', 'roles', $auth_ns)) { ?>
			<li class="<?php echo ($controller == "security" && $action == "roles") ? $routeactive : ""; ?> <?php echo ($this->layout_type == 'h') ? "hover" : ''; ?>">
				<a href="<?php echo $this->basePath('auth/security/roles/'); ?>">
					<i class="menu-icon fa fa-caret-right"></i>
					Roles
				</a>
				<b class="arrow"></b>
			</li>
			<?php } ?>
			<?php if ($this->authorization()->isPermitted('Auth::Security', 'resources', $auth_ns)) { ?>
			<li class="<?php echo ($controller == "security" && $action == "resources") ? $routeactive : ""; ?> <?php echo ($this->layout_type == 'h') ? "hover" : ''; ?>">
				<a href="<?php echo $this->basePath('auth/security/resources/'); ?>">
					<i class="menu-icon fa fa-caret-right"></i>
					Resources
				</a>
				<b class="arrow"></b>
			</li>
			<?php } ?>
			<?php if ($this->authorization()->isPermitted('Auth::Security', 'permissions', $auth_ns)) { ?>
			<li class="<?php echo ($controller == "security" && $action == "permissions") ? $routeactive : ""; ?> <?php echo ($this->layout_type == 'h') ? "hover" : ''; ?>">
				<a href="<?php echo $this->basePath('auth/security/permissions/'); ?>">
					<i class="menu-icon fa fa-caret-right"></i>
					Permissions
				</a>
				<b class="arrow"></b>
			</li>
			<?php } ?>
		</ul>
	</li>
<?php } ?>