<?php include(__DIR__ . "/layout/layout.phtml"); ?>

<?php $this->placeholder('breadcrumb')->captureStart('APPEND'); ?>
<li>
	Admin
</li>
<li>
	<a href="<?php echo $this->basePath('contract/vendors/'); ?>">Vendors</a>
</li>
<li>
	<a href="<?php echo $this->basePath('contract/vendors/view/'.$this->id); ?>"><?php echo $this->name; ?></a>
</li>
<?php $this->placeholder('breadcrumb')->captureEnd(); ?>

<?php $this->placeholder('style')->captureStart(); ?>
<style type="text/css">
	#vendor-logo {
		max-height: 80px;
		max-width: 200px;
	}
</style>
<?php $this->placeholder('style')->captureEnd(); ?>

<?php $this->placeholder('header')->captureStart('SET'); ?>
<div class="row">
	<div class="col-sm-8">
		<h1>
			Contracts
			<small>
				<i class="ace-icon fa fa-angle-double-right"></i>
				Vendors
			</small>
		</h1>
	</div>
	<div class="col-sm-4 align-right">
		<div class="btn-group">
			<button type="button" class="btn btn-xs btn-inverse dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Actions
				<span class="ace-icon fa fa-caret-down icon-only"></span>
			</button>
			<ul class="dropdown-menu dropdown-inverse dropdown-white dropdown-menu-right">
				<?php if ($this->authorization()->isPermitted('Contract::Vendors', 'edit')) { ?>
				<li>
					<a data-toggle='modal' href='#' onclick="editVendorView()">
						<i class="ace-icon fa fa-edit"></i>
						Edit
					</a>
				</li>
				<?php } ?>
			</ul>
		</div>
	</div>
</div>
<?php $this->placeholder('header')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<div class="row">
	<div class="col-sm-6">
		<div class="widget-body">
			<div class="widget-main padding-12">
				<div class="row">
					<div class="col-xs-12">
						<img id='vendor-logo' src="<?php echo $this->basePath($this->logo); ?>" onerror="this.style.display='none'">
					</div>
				</div>
				<div class="space-6"></div>
				<div class="row">
					<div class="col-xs-12 label label-lg label-default align-left">
						<b>Vendor Detail</b>
					</div>
				</div>
				<div>
					<ul class="list-unstyled">
						<li class="row">
							<span class="col-xs-3 bolder"><i class="ace-icon fa fa-caret-right blue"></i> Name</span>
							<span class="col-xs-9"><?php echo $this->name; ?></span>
						</li>
						<li class="row">
							<span class="col-xs-3 bolder"><i class="ace-icon fa fa-caret-right blue"></i> Notes</span>
							<span class="col-xs-9"><?php echo $this->formatter()->na($this->notes); ?></span>
						</li>
						<li class="row">
							<span class="col-xs-3 bolder"><i class="ace-icon fa fa-caret-right blue"></i> Active?</span>
							<span class="col-xs-9"><?php echo $this->formatter()->yesno($this->active); ?></span>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<br />
<div class="row tabbable">
	<div class="col-xs-12">
			<div class="btn-group pull-right bring-front">
			<button type="button" class="btn btn-xs btn-inverse dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Tab Actions
				<span class="ace-icon fa fa-caret-down icon-only"></span>
			</button>
			<ul class="dropdown-menu dropdown-inverse dropdown-white dropdown-menu-right">
				<?php if ($this->authorization()->isPermitted('Contract::Vendors', 'add-contact')) { ?>
				<li>
					<a data-toggle='modal' data-target='#add-contact-modal'  href='#' onclick="addContact()">
						<i class="ace-icon fa fa-edit"></i>
						Add New Support Contact
					</a>
				</li>
				<?php } ?>
			</ul>
		</div>
	
		<ul class="nav nav-tabs responsive">
			<li>
				<a data-toggle="tab" href="#contracts_pane" id="contracts_a">Contracts</a>
			</li>
			<li>
				<a data-toggle="tab" href="#contacts_pane" id="contacts_a">Support Contacts</a>
			</li>
		</ul>
		<div class="tab-content responsive">
			<div id="contracts_pane" class="tab-pane fade">
				<?php include(__DIR__ . "/pane/contracts.phtml"); ?>
			</div>
			<div id="contacts_pane" class="tab-pane fade">
				<?php include(__DIR__ . "/pane/contacts.phtml"); ?>
			</div>
		</div>
	</div>
</div>
<?php include(__DIR__ . "/pane/edit.phtml"); ?>
<?php include(__DIR__ . "/pane/add-contact.phtml"); ?>
<?php include(__DIR__ . "/pane/edit-contact.phtml"); ?>
<?php include(__DIR__ . "/pane/delete-contact.phtml"); ?>
<?php include(__DIR__ . "/pane/default-contact.phtml"); ?>
<?php $this->placeholder('content')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		<?php if($this->onload == 'add-contact') { ?>
			$('#contacts_a').tab('show');
			addContact();
			$("#add-contact-modal").modal("show");
		<?php } else { ?>
			$('#contracts_a').tab('show');
		<?php } ?>
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>