<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		$('#add_contact').on('submit', function() {
			var vendor_id = <?php echo $this->id; ?>;
			var description = $("#add_contact_description").val();
			var phone_number = $("#add_contact_phone_number").val();
			var email = $("#add_contact_email").val();
			var url = $("#add_contact_url").val();
			var notes = $("#add_contact_notes").val();
			
			$("#add_contact_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Adding new contact...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('contract/vendors/add-contact/'); ?>',
				data: { 
					vendor_id: vendor_id, 
					description: description,
					phone_number: phone_number,
					email: email,
					url: url,
					notes: notes
				}
			}).done(function(data) {
				if (data.status == 1) {
					$("#add_contact_message")
						.removeClass("label-default")
						.addClass("label-success")
						.html("Successfully added new contact");
					
					setTimeout(function() {
						$("#add_contact_message").hide();
						
						$("#add-contact-modal").modal('hide');

						<?php if($this->onload!='') { ?>
							window.location.href = '<?php echo $this->wizard()->getRedirect('contracts', $this->basePath('contract/contracts/')); ?>';
						<?php } ?>
						
						reloadContactsTable();
					}, 1000);
				} else {
					$("#add_contact_message")
						.removeClass("label-default")
						.addClass("label-danger");
						
					if (data.error) {
						if ($.isArray(data.error)) {
							$("#add_contact_message").html(data.error.join('<br />'));
						} else {
							$("#add_contact_message").html(data.error);
						}
					} else {
						$("#add_contact_message").html("Unable to add new contact, please try again");
					}
				}
			}).fail(function(error) {
				$("#add_contact_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html("Unable to add new contact, please try again");
			});
			
			// prevent the page submit
			return false;
		});
	});
	
	function addContact() {
		$("#add_contact_message").hide();
	}
	
	function reloadContactsTable() {
		$("#contacts").dataTable().api().ajax.reload();
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="add-contact-modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Add New Support Contact
				</div>
			</div>
			<form id="add_contact" class="form-horizontal">
				<div class="modal-body no-padding">				
					<div class="row no-padding no-margin">
						<div class="alert alert-warning">
							All fields with an <i class="ace-icon fa fa-asterisk red"></i> are required.
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="add_contact_description">Description </label>
						<div class="col-sm-8">
							<span class="block input-icon input-icon-right">
								<input type="text"
									   id="add_contact_description"
									   name="add_contact_description"
									   placeholder="Description"
									   class="width-100" />
							</span>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="add_contact_phone_number">Phone Number </label>
						<div class="col-sm-8">
							<span class="block input-icon input-icon-right">
								<input type="text"
									   id="add_contact_phone_number"
									   name="add_contact_phone_number"
									   placeholder="Phone Number"
									   class="width-100" />
							</span>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="add_contact_email">Email </label>
						<div class="col-sm-8">
							<span class="block input-icon input-icon-right">
								<input type="text"
									   id="add_contact_email"
									   name="add_contact_email"
									   placeholder="Email"
									   class="width-100" />
							</span>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="add_contact_url">URL </label>
						<div class="col-sm-8">
							<span class="block input-icon input-icon-right">
								<input type="text"
									   id="add_contact_url"
									   name="add_contact_url"
									   placeholder="Support portal"
									   class="width-100" />
							</span>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="add_contact_notes">Notes </label>
						<div class="col-sm-8">
							<span class="block input-icon input-icon-right">
								<textarea
									   id="add_contact_notes"
									   name="add_contact_notes"
									   placeholder="Notes"
									   class="width-100"></textarea>
							</span>
						</div>
					</div>
				</div>
				<div class="space-6"></div>
				<div class="modal-footer">
					<button class="btn btn-sm pull-left"
							type="button"
							data-dismiss="modal">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</button>
					<button class="btn btn-sm btn-primary pull-left"
							type="submit">
						<i class="ace-icon fa fa-plus bigger-125"></i>
						Add
					</button>
					<div id="add_contact_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>