<?php $this->placeholder('style')->captureStart(); ?>
<style type="text/css">
	#contacts_filter {
		display: none;
	}
	#contacts_length {
		display: none;
	}
</style>
<?php $this->placeholder('style')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = null;
		$("#contacts_a").on('shown.bs.tab', function() {
			if (!table) {
				table = $("#contacts").DataTable({
					serverSide: true,			
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
							d['vendor_id'] = '<?php echo $this->id; ?>';
							d['active'] = 1;
						},
						url: "<?php echo $this->basePath('contract/rest/vendor-contacts/'); ?>"
					},
					iDisplayLength: 25,
					stateSave: false,
					deferRender: true,
					searchDelay: 500,
					responsive: {
						details: {
							renderer: function(api, row, columns) {
								return $.datatables_utils.responsive_renderer(api, row, columns, table);
							}
						}
					},
					columns: [
					    { data: 'id', orderable: false, searchable: false, render: function(val, type, data, options) {
							var str
								= "<div class='inline pos-rel'>"
									+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
										+ "Actions "
										+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
									+ "</button>"
									+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>";
									<?php if ($this->authorization()->isPermitted('Contract::Vendors', 'default-contact')) { ?>
									if(data.default == 0) {
									str	+= "<li>"
										+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"defaultContact('" + options.row + "')\">"
												+ "<span class='green'>"
													+ "<i class='ace-icon fa fa-check bigger-120'></i>"
													+ " Mark as Default"
												+ "</span>"
											+ "</a>"
										+ "</li>";
									}
									<?php } ?>
									<?php if ($this->authorization()->isPermitted('Contract::Vendors', 'edit-contact')) { ?>
									str	+= "<li>"
										+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"editContact('" + options.row + "')\">"
												+ "<span class='blue'>"
													+ "<i class='ace-icon fa fa-edit bigger-120'></i>"
													+ " Edit"
												+ "</span>"
											+ "</a>"
										+ "</li>";
									<?php } ?>
									<?php if ($this->authorization()->isPermitted('Contract::Vendors', 'delete-contact')) { ?>
									str	+= "<li>"
										+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"deleteContact('" + options.row + "')\">"
												+ "<span class='red'>"
													+ "<i class='ace-icon fa fa-trash bigger-120'></i>"
													+ " Delete"
												+ "</span>"
											+ "</a>"
										+ "</li>";
									<?php } ?>
									str += "</ul>"
								+ "</div>";

							return str; 
					    }},
					    { data: 'default', searchable: false, sortable: false, render: function(val, type, data, options) {
						    var str = '';

						    if(val==1) {
							    str = '<i class="ace-icon fa fa-check"></i>';
						    }

						    return str;
					    }},
					    { data: 'description', searchable: true, render: $.datatables_utils.format_na },
						{ data: 'phone_number', searchable: true, render: $.datatables_utils.format_na },
					    { data: 'email', searchable: true, render: $.datatables_utils.format_na },
						{ data: 'url', searchable: true, render: $.datatables_utils.format_na },
						{ data: 'notes', searchable: true, render: $.datatables_utils.format_na }
					],
					fnPreDrawCallback: function() {
						return true;
					}
				});
			} else {
				table.responsive.recalc();
			}
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="contacts" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th style="width: 40px;">Default</th>
					<th>Description</th>
					<th>Phone Number</th>
					<th>Email</th>
					<th>URL</th>
					<th>Notes</th>
				</tr>
			</thead>
		</table>
	</div>
</div>