<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {		
		$.validate_utils.create('#add_service', {
			name: {
				required: true,
				message: 'Please provide a Name'
			}
		}, function(form) {
			$("#add_service_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Adding service...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('api/services/add/'); ?>',
				data: $(form).serializeArray()
			}).done(function(data) {
				$("#add_service_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully added service");
				
				setTimeout(function() {
					$("#add_service_message").hide();					
					$("#add_service_modal").modal('hide');
					
					if ($.fn.DataTable.isDataTable('#services')) {
						$("#services").dataTable().api().ajax.reload();
					}
				}, 1000);
			}).fail(function(error) {
				if (error.responseJSON && error.responseJSON['error']) {
					error = error.responseJSON['error'];
				} else {
					error = 'Unable to add service, try again';
				}
				
				$("#add_service_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			
			// prevent the page submit
			return false;
		});
		
		$('#add_service_modal').on('show.bs.modal', function(e) {
			// reset the form
			$("#add_service")[0].reset();
		});		
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="add_service_modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Add New Service
				</div>
			</div>
			<form id="add_service" class="form-horizontal">
				<div class="modal-body">
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								All fields with an <i class="ace-icon fa fa-asterisk red"></i> are required.
							</div>
							<div class="form-group">
								<label class="col-sm-2 control-label no-padding-right" for="add_service_name">Name </label>
								<div class="col-sm-9">
									<span class="block input-icon input-icon-right">
										<input type="text"
											   id="add_service_name"
											   name="name"
											   placeholder="Service name"
											   class="width-100" />
										<i class="ace-icon fa fa-asterisk red" style="margin-right: 15px;"></i>
									</span>
								</div>
							</div>
							<div class="form-group">
								<label class="col-sm-2 control-label no-padding-right" for="add_service_version">Version </label>
								<div class="col-sm-9">
									<input type="text"
										   id="add_service_version"
										   name="version"
										   placeholder="Service version"
										   class="width-100" />
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer align-left">
					<a class="btn btn-sm" href="#" data-dismiss="modal" aria-hidden="true">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</a>
					<button class="btn btn-sm btn-primary"
							type="submit">
						<i class="ace-icon fa fa-plus bigger-125"></i>
						Add
					</button>
					<div id="add_service_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>