<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
        $.validate_utils.create('#delete_service_method', {}, function(form) {
			$("#delete_service_method_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Deleting service method...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('api/services/delete-method/' . $this->id); ?>',
                data: $(form).serializeArray()
			}).done(function(data) {
				$("#delete_service_method_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully deleted service method");
				
                if (window.refreshStats) {
					window.refreshStats();
				}
                
				setTimeout(function() {
					$("#delete_service_method_message").hide();						
					$("#delete_service_method_modal").modal('hide');
					
					if ($.fn.DataTable.isDataTable('#methods')) {
						$("#methods").dataTable().api().ajax.reload();
					}
				}, 1000);
			}).fail(function(error) {
				if (error.responseJSON && error.responseJSON['error']) {
					error = error.responseJSON['error'];
				} else {
					error = 'Unable to delete service method, try again';
				}
				
				$("#delete_service_method_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			
			// prevent the page submit
			return false;
		});
	});
	
	function deleteServiceMethod(row) {
		$("#delete_service_method_message").hide();
		var data = $("#methods").dataTable().fnGetData(row);
		if (data) {
			$("#delete_service_method_id").val(data.id);
			$("#delete_service_method_method_value").html(data.method);
            
			$('#delete_service_method_modal').modal('show');
		}
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="delete_service_method_modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Delete Service Method
				</div>
			</div>
			<form id="delete_service_method" class="form-horizontal">
                <input type="hidden" id="delete_service_method_id" name="method_id" />
				<div class="modal-body">
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								Are you sure?  Click <strong>Delete</strong> to proceed and delete this service.
							</div>							
							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Method </div>
									<div class="profile-info-value">
										<span id="delete_service_method_method_value"></span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="space-6"></div>
				<div class="modal-footer">
					<button class="btn btn-sm pull-left"
							type="button"
							data-dismiss="modal">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</button>
					<button class="btn btn-sm btn-danger pull-left"
							type="submit">
						<i class="ace-icon fa fa-trash bigger-125"></i>
						Delete
					</button>
					<div id="delete_service_method_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>