<?php
$route = $this->route()->getRouteName();
$controller = $this->route()->getControllerName();
$action = $this->route()->getAction();

$is_view_service = false;
if($route == 'api/default' && $controller == 'services' && $action == 'view') {
	$is_view_service = true;
}
?>
<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		$("#delete_service").on('submit', function() {
			$("#delete_service_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Deleting service...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('api/services/delete/'); ?>' + $("#delete_service_id").val()
			}).done(function(data) {
				$("#delete_service_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully deleted service");
				
				setTimeout(function() {
					$("#delete_service_message").hide();						
					$("#delete_service_modal").modal('hide');
					
					if ($.fn.DataTable.isDataTable('#services')) {
						$("#services").dataTable().api().ajax.reload();
					}
				}, 1000);
			}).fail(function(error) {
				if (error.responseJSON && error.responseJSON['error']) {
					error = error.responseJSON['error'];
				} else {
					error = 'Unable to delete service, try again';
				}
				
				$("#delete_service_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			
			// prevent the page submit
			return false;
		});
	});
	
	function deleteService(row) {
		$("#delete_service_message").hide();
		var data = $("#services").dataTable().fnGetData(row);
		if (data) {
			$("#delete_service_id").val(data.id);
			$("#delete_service_name_value").html(data.name);
			
			$('#delete_service_modal').modal('show');
		}
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="delete_service_modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Delete Service
				</div>
			</div>
			<form id="delete_service" class="form-horizontal">
				<div class="modal-body">
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								Are you sure?  Click <strong>Delete</strong> to proceed and delete this service.
							</div>
							<input type="hidden" id="delete_service_id" name="id" value="<?php echo ($is_view_service) ? $this->id : ''; ?>" />
							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Name </div>
									<div class="profile-info-value">
										<span id="delete_service_name_value"><?php echo ($is_view_service) ? $this->service['name'] : ''; ?></span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="space-6"></div>
				<div class="modal-footer">
					<button class="btn btn-sm pull-left"
							type="button"
							data-dismiss="modal">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</button>
					<button class="btn btn-sm btn-danger pull-left"
							type="submit">
						<i class="ace-icon fa fa-trash bigger-125"></i>
						Delete
					</button>
					<div id="delete_service_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>