<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = null;
		$("#methods_a").on('shown.bs.tab', function() {
			if (!table) {
				table = $("#methods").DataTable({
					processing: true,
					serverSide: true,
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
						},
						url: "<?php echo $this->basePath('api/rest/services/' .  $this->id . '/methods/'); ?>"
					},
					oLanguage: {
						sEmptyTable: "No service methods",
						sProcessing: "",
						sSearch: "Search",
						sSearchPlaceholder: "Search within..."
					},
					iDisplayLength: 50,
					stateSave: false,
					deferRender: true,
					searchDelay: 500,
					responsive: {
						details: {
							renderer: function(api, row, columns) {
								return $.datatables_utils.responsive_renderer(api, row, columns, table);
							}
						}
					},
					columns: [
						{ data: 'id', orderable: false, searchable: false, render: $.datatables_utils.format_empty, className: 'control' },
						{ data: 'id', orderable: false, searchable: false, render: function(val, type, data, options) {
							return "<div class='inline pos-rel'>"
									+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
										+ "Actions "
										+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
									+ "</button>"
									+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>"
										<?php if($this->authorization()->isPermitted('Api::ServiceMethods', 'edit')) { ?>
										+ "<li>"
											+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"editServiceMethod('" + options.row + "')\">"
												+ "<span class='blue'>"
													+ "<i class='ace-icon fa fa-edit bigger-120'></i>"
													+ " Edit"
												+ "</span>"
											+ "</a>"
										+ "</li>"
										<?php } ?>
										<?php if($this->authorization()->isPermitted('Api::ServiceMethods', 'delete')) { ?>
											+ "<li>"
												+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"deleteServiceMethod('" + options.row + "')\">"
													+ "<span class='red'>"
														+ "<i class='ace-icon fa fa-trash bigger-120'></i>"
														+ " Delete"
													+ "</span>"
												+ "</a>"
											+ "</li>"
											<?php } ?>
									+ "</ul>"
								+ "</div>";
						}, className: 'all' },
						{ data: 'id', orderable: false, searchable: false, render: function(val, type, data) {
							return "<input class='ace cb' type='checkbox' value='" + val + "' /><span class='lbl'></span>";
						}, className: 'align-center all' },
						{ data: 'method', searchable: true, render: function(val, type, data) {
							val = (val == '' || val == null) ? 'N/A' : val;
                            return val;
						}, className: 'all' },
						{ data: 'security_resource_controller', searchable: true, render: function(val, type, data) {
							if (data.security_resource_id && parseInt(data.security_resource_id, 10) != 0) {
								var action = data.security_resource_action || '';
								val = val || '';
								val = val + ' >> ' + action;
								
								<?php if($this->authorization()->isPermitted('Gem::Security', 'resources-edit', $gem_ns)) { ?>
								return "<a href='<?php echo $this->basePath($this->config()->getConfig('api', 'security_resource_app') . '/security/resources-edit/'); ?>" + data.security_resource_id + "'>" + val + "</a>";
								<?php } else {?>
								return val;
								<?php } ?>
							} else {
								return '';
							}
						}, className: 'all' },
						{ data: 'ctime', searchable: false, render: $.datatables_utils.format_date }
					],
					order: [[3, "asc"]],
					fnPreDrawCallback: function() {
						$("#methods_info").html("Loading service methods...");
						$('#methods .cb-all').prop('checked', false);
						return true;
					},
					fnDrawCallback: function() {
						$("#methods input.cb, #methods input.cb-all").off('click.gem');
						$("#methods input.cb, #methods input.cb-all").on('click.gem', function() {
							if ($(this).hasClass('cb-all')) {
								if ($(this).prop('checked')) {
									// check all cb
									$('#methods input.cb').prop('checked', true);
								} else {
									// uncheck all cb
									$('#methods input.cb').prop('checked', false);
								}
							}
							
							$('#methods li.action').addClass('disabled');							
							var checks = $('#methods input.cb:checked').length;
							
							if (checks > 0) {
								// enable all buttons
								$('#methods li.action').removeClass('disabled');
							}
						});
					}
				});
			} else {
				table.responsive.recalc();
			}
		});
		
		$('#methods_a').tab('show');
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="methods" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th style="min-width: 40px; max-width: 40px;"></th>
					<th style="min-width: 60px; max-width: 60px;" class="align-center">
						<input class='ace cb-all' type='checkbox' />
						<span class='lbl'></span>
					</th>
					<th style="min-width: 100px;">Method</th>
					<th style="min-width: 100px;">Security Resource</th>
					<th style="min-width: 100px;">Created</th>
				</tr>
			</thead>
			<tfoot>
				<td></td>				
				<td>
					<div class="btn-group">
						<button class="btn btn-minier btn-yellow dropdown-toggle"
								data-toggle="dropdown"
								data-position="auto">
							Actions
							<i class="ace-icon fa fa-caret-down icon-only bigger-120"></i>
						</button>
						<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
							<?php if($this->authorization()->isPermitted('Api::ServiceMethods', 'delete')) { ?>
								<li class="action disabled">
									<a href="javascript: void(0);"
									   class="red"
									   onclick="deleteMethodsSelected()">
										<i class="ace-icon fa fa-trash"></i>
										Delete
									</a>
								</li>
							<?php } ?>
						</ul>
					</div>
				</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tfoot>
		</table>
	</div>
</div>
<?php include(__DIR__ . "/edit-method.phtml"); ?>
<?php include(__DIR__ . "/delete-method.phtml"); ?>