<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		$.validate_utils.create('#add_key', {
			user_id: {
				required: true,
				message: 'Please select a User'
			}
		}, function(form) {
			$("#add_key_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Adding key...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('api/keys/add/'); ?>',
				data: $(form).serializeArray()
			}).done(function(data) {
				$("#add_key_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully added key");
				
				setTimeout(function() {
					$("#add_key_message").hide();
					$("#add_key_modal").modal('hide');
					
					<?php if (intval($this->add) == 1) { ?>
					window.location = '<?php echo $this->basePath('api/keys/view/'); ?>' + data.id;
					<?php } else { ?>
                    if (parseInt(data.auto_configure, 10) == 0) {
                        // we need to move to the edit screen to allow the user to configure this key
                        window.location = '<?php echo $this->basePath('api/keys/view/'); ?>' + data.id;
                    } else {
                        if ($.fn.DataTable.isDataTable('#keys')) {
                            $("#keys").dataTable().api().ajax.reload();
                        }
                    }
					<?php } ?>
				}, 1000);
			}).fail(function(error) {
				if (error.responseJSON && error.responseJSON.error) {
					error = error.responseJSON.error;
				} else {
					error = 'Unable to add key, try again';
				}
				
				$("#add_key_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			
			// prevent the page submit
			return false;
		});
		
		$('#add_key_modal').on('show.bs.modal', function() {
			// reset the form
			$("#add_key")[0].reset();
            
            if(!$("#add_key_user").data('select2')) {
                $.select2_utils.create([{
                    id: 'add_key_user',
                    url: '<?php echo $this->basePath('hr/rest/hr-users/'); ?>',
                    display: 'display_name',
					onData: function(d) {
						d.terminated = 0;
					}
                }], 25);
            } else {
                $('#add_key_user').select2('val', null);
            }
            
            // default the auto-configure to always be true
            $('#add_key_auto_configure').prop('checked', true);
		});
		
		<?php if (intval($this->add) == 1) { ?>
        $('#add_key_modal').modal('show');
        <?php } ?>
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="add_key_modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Add New Key
				</div>
			</div>
			<form id="add_key" class="form-horizontal">
				<div class="modal-body">
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								All fields with an <i class="ace-icon fa fa-asterisk red"></i> are required.
							</div>
							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="add_key_user">User </label>
								<div class="col-sm-8">
									<span class="block input-icon input-icon-right">
										<input type="text"
											   id="add_key_user"
											   name="user_id"
											   placeholder="User"
											   class="width-100" />
										<i class="ace-icon fa fa-asterisk red" style="margin-right: 15px;"></i>
									</span>
								</div>
							</div>
							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="add_key_description">Description </label>
								<div class="col-sm-8">
									<textarea id="add_key_description"
                                              name="description"
                                              placeholder="Description"
                                              class="width-100"></textarea>
								</div>
							</div>
                            <div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="add_key_auto_configure">Auto Configure </label>
								<div class="col-sm-8">
                                    <div class="space-4"></div>
									<input type="checkbox"
                                           name="auto_configure"
                                           id="add_key_auto_configure"
                                           value="1"
                                           class="ace ace-switch ace-switch-2" />
                                    <span class="lbl"> &nbsp; Allow our system to auto-configure API access</span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer align-left">
					<a class="btn btn-sm" href="#" data-dismiss="modal" aria-hidden="true">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</a>
					<button class="btn btn-sm btn-primary"
							type="submit">
						<i class="ace-icon fa fa-plus bigger-125"></i>
						Add
					</button>                    
					<div id="add_key_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>