<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var selects = [{
			id: 'assign_service_methods_service_methods',
			url: '<?php echo $this->basePath('api/rest/keys/' . $this->id . '/available-service-methods/'); ?>',
            display: 'method',
            onData: function(data) {
                data['service|method'] = data['method'];
                delete data['method'];
            },
            onResult: function(item) {
                var text = item.service || '';
                text += ' >> ' + item.method;
                
                return {
                    id: item.id,
                    text: text
                };
            }
		}];
		
		$.select2_utils.create(selects, 25, {
			multiple: true
		});
		
		$.validate_utils.create('#assign_service_methods', {
			roles: {
				required: true,
				message: 'Please select a Service Method'
			}
		}, function(form) {
			$("#assign_service_methods_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Assigning service methods...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('api/keys/assign-service-methods/' . $this->id); ?>',
				data: $(form).serializeArray()
			}).done(function(data) {
				$("#assign_service_methods_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully assigned service methods");
				
				setTimeout(function() {
					$("#assign_service_methods_message").hide();						
					$("#assign_service_methods_modal").modal('hide');
					
					if ($.fn.DataTable.isDataTable('#service_methods')) {
						$("#service_methods").dataTable().api().ajax.reload();
					}
				}, 1000);
			}).fail(function(error) {
				if (error.responseJSON && error.responseJSON['error']) {
					error = error.responseJSON['error'];
				} else {
					error = 'Unable to assign service methods, try again';
				}
				
				$("#assign_service_methods_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			return false;
		});
		
		$('#assign_service_methods_modal').on('show.bs.modal', function(e) {
			// reset the service_methods field
			$("#assign_service_methods_service_methods").select2('val', null);
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="assign_service_methods_modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Assign Service Methods
				</div>
			</div>
			<form id="assign_service_methods" class="form-horizontal">
				<div class="modal-body">
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								All fields with an <i class="ace-icon fa fa-asterisk red"></i> are required.  Select as many <strong>Service Methods</strong> as desire.
							</div>
							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="assign_service_methods_service_methods">Service Methods </label>
								<div class="col-sm-8">
									<span class="block input-icon input-icon-right">
										<input type="text"
											   id="assign_service_methods_service_methods"
											   name="service_methods"
											   placeholder="Service Methods"
											   class="width-100" />
										<i class="ace-icon fa fa-asterisk red" style="margin-right: 15px;"></i>
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer align-left">
					<a class="btn btn-sm" href="#" data-dismiss="modal" aria-hidden="true">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</a>
					<button class="btn btn-sm btn-primary"
							type="submit">
						<i class="ace-icon fa fa-plus bigger-125"></i>
						Assign
					</button>
					<div id="assign_service_methods_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>