<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = null;
		$("#service_methods_a").on('shown.bs.tab', function() {
			if (!table) {
				table = $("#service_methods").DataTable({
					processing: true,
					serverSide: true,
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
						},
						url: "<?php echo $this->basePath('api/rest/keys/' .  $this->id . '/auto-service-methods/'); ?>"
					},
					oLanguage: {
						sEmptyTable: "No service methods",
						sProcessing: "",
						sSearch: "Search",
						sSearchPlaceholder: "Search within..."
					},
					iDisplayLength: 50,
					stateSave: false,
					deferRender: true,
					searchDelay: 500,
					responsive: {
						details: {
							renderer: function(api, row, columns) {
								return $.datatables_utils.responsive_renderer(api, row, columns, table);
							}
						}
					},
					columns: [
						{ data: 'service_method_id', orderable: false, searchable: false, render: $.datatables_utils.format_empty, className: 'control' },
						{ data: 'service', searchable: true, render: function(val, type, data) {
                            val = (val == '' || val == null) ? 'N/A' : val;
                            
                            <?php if($this->authorization()->isPermitted('Api::Services', 'view')) { ?>
                            return "<a href='<?php echo $this->basePath('api/services/view/'); ?>" + data.service_id + "'>" + val + "</a>";
                            <?php } else { ?>
                            return val;
                            <?php } ?>
						}, className: 'all' },
                        { data: 'service_method', searchable: true, render: $.datatables_utils.format_na, className: 'all' }
					],
					order: [[1, "asc"], [2, "asc"]],
					fnPreDrawCallback: function() {
						$("#service_methods_info").html("Loading service methods...");
						$('#service_methods .cb-all').prop('checked', false);
						return true;
					}
				});
			} else {
				table.responsive.recalc();
			}
		});
		
		$('#service_methods_a').tab('show');
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="service_methods" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
                    <th style="min-width: 100px;">Service</th>
					<th style="min-width: 100px;">Method</th>
				</tr>
			</thead>
			<tfoot>
				<td></td>
				<td></td>
				<td></td>
			</tfoot>
		</table>
	</div>
</div>