<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = null;
		$("#service_methods_a").on('shown.bs.tab', function() {
			if (!table) {
				table = $("#service_methods").DataTable({
					processing: true,
					serverSide: true,
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
						},
						url: "<?php echo $this->basePath('api/rest/keys/' .  $this->id . '/service-methods/'); ?>"
					},
					oLanguage: {
						sEmptyTable: "No service methods",
						sProcessing: "",
						sSearch: "Search",
						sSearchPlaceholder: "Search within..."
					},
					iDisplayLength: 50,
					stateSave: false,
					deferRender: true,
					searchDelay: 500,
					responsive: {
						details: {
							renderer: function(api, row, columns) {
								return $.datatables_utils.responsive_renderer(api, row, columns, table);
							}
						}
					},
					columns: [
						{ data: 'service_method_id', orderable: false, searchable: false, render: $.datatables_utils.format_empty, className: 'control' },
						{ data: 'service_method_id', orderable: false, searchable: false, render: function(val, type, data, options) {
							return "<div class='inline pos-rel'>"
									+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
										+ "Actions "
										+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
									+ "</button>"
									+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>"
										<?php if($this->authorization()->isPermitted('Api::Keys', 'unassign-service-methods')) { ?>
											+ "<li>"
												+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"unassignServiceMethod('" + options.row + "')\">"
													+ "<span class='red'>"
														+ "<i class='ace-icon fa fa-remove bigger-120'></i>"
														+ " Unassign"
													+ "</span>"
												+ "</a>"
											+ "</li>"
											<?php } ?>
									+ "</ul>"
								+ "</div>";
						}, className: 'all' },
						{ data: 'service_method_id', orderable: false, searchable: false, render: function(val, type, data) {
							return "<input class='ace cb' type='checkbox' value='" + val + "' /><span class='lbl'></span>";
						}, className: 'align-center all' },
						{ data: 'service', searchable: true, render: function(val, type, data) {
                            val = (val == '' || val == null) ? 'N/A' : val;
                            
                            <?php if($this->authorization()->isPermitted('Api::Services', 'view')) { ?>
                            return "<a href='<?php echo $this->basePath('api/services/view/'); ?>" + data.service_id + "'>" + val + "</a>";
                            <?php } else { ?>
                            return val;
                            <?php } ?>
						}, className: 'all' },
                        { data: 'service_method', searchable: true, render: $.datatables_utils.format_na, className: 'all' }
					],
					order: [[3, "asc"], [4, "asc"]],
					fnPreDrawCallback: function() {
						$("#service_methods_info").html("Loading service methods...");
						$('#service_methods .cb-all').prop('checked', false);
						return true;
					},
					fnDrawCallback: function() {
						$("#service_methods input.cb, #service_methods input.cb-all").off('click.gem');
						$("#service_methods input.cb, #service_methods input.cb-all").on('click.gem', function() {
							if ($(this).hasClass('cb-all')) {
								if ($(this).prop('checked')) {
									// check all cb
									$('#service_methods input.cb').prop('checked', true);
								} else {
									// uncheck all cb
									$('#service_methods input.cb').prop('checked', false);
								}
							}
							
							$('#service_methods li.action').addClass('disabled');							
							var checks = $('#service_methods input.cb:checked').length;
							
							if (checks > 0) {
								// enable all buttons
								$('#service_methods li.action').removeClass('disabled');
							}
						});
					}
				});
			} else {
				table.responsive.recalc();
			}
		});
		
		$('#service_methods_a').tab('show');
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="service_methods" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th style="min-width: 40px; max-width: 40px;">
						<div class="btn-group">
							<button class="btn btn-minier btn-yellow dropdown-toggle"
									data-toggle="dropdown"
									data-position="auto">
								Actions
								<i class="ace-icon fa fa-caret-down icon-only bigger-120"></i>
							</button>
							<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
								<?php if($this->authorization()->isPermitted('Api::Keys', 'unassign-service-methods')) { ?>
									<li class="action disabled">
										<a href="javascript: void(0);"
										   class="red"
										   onclick="unassignServiceMethodsSelected()">
											<i class="ace-icon fa fa-remove"></i>
											Unassign
										</a>
									</li>
								<?php } ?>
							</ul>
						</div>
					</th>
					<th style="min-width: 60px; max-width: 60px;" class="align-center">
						<input class='ace cb-all' type='checkbox' />
						<span class='lbl'></span>
					</th>
                    <th style="min-width: 100px;">Service</th>
					<th style="min-width: 100px;">Method</th>
				</tr>
			</thead>
			<tfoot>
				<td></td>
				<td>
					<div class="btn-group">
						<button class="btn btn-minier btn-yellow dropdown-toggle"
								data-toggle="dropdown"
								data-position="auto">
							Actions
							<i class="ace-icon fa fa-caret-down icon-only bigger-120"></i>
						</button>
						<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
							<?php if($this->authorization()->isPermitted('Api::Keys', 'unassign-service-methods')) { ?>
								<li class="action disabled">
									<a href="javascript: void(0);"
									   class="red"
									   onclick="unassignServiceMethodsSelected()">
										<i class="ace-icon fa fa-remove"></i>
										Unassign
									</a>
								</li>
							<?php } ?>
						</ul>
					</div>
				</td>
				<td></td>
                <td></td>
				<td></td>
			</tfoot>
		</table>
	</div>
</div>
<?php include(__DIR__ . "/unassign-service-methods.phtml"); ?>