<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">	
	function unassignServiceMethod(row) {		
		var data = $("#service_methods").dataTable().fnGetData(row);
		if (data) {
			$("#unassign_service_methods_modal").modal('show');
			$("#unassign_service_methods_message")
				.show()
				.removeClass("alert-success")
				.removeClass("alert-danger")
				.addClass("alert-info")
				.html("Unassigning service method...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('api/keys/unassign-service-methods/' . $this->id); ?>',
				data: {
					service_method_id: data.service_method_id
				}
			}).done(function(data) {
				$("#unassign_service_methods_message")
					.removeClass("alert-info")
					.addClass("alert-success")
					.html("Successfully unassigned service method");
				
				setTimeout(function() {
					$("#unassign_service_methods_message").hide();					
					$("#unassign_service_methods_modal").modal('hide');
					
					if ($.fn.DataTable.isDataTable('#service_methods')) {
						$("#service_methods").dataTable().api().ajax.reload();
					}
				}, 1000);
			}).fail(function(error) {
				if (error.responseJSON && error.responseJSON['error']) {
					error = error.responseJSON['error'];
				} else {
					error = 'Unable to unassign service method, try again';
				}
				
				$("#unassign_service_methods_message")
					.removeClass("alert-info")
					.addClass("alert-danger")
					.html(error);
			});
		}
	}
    
    function unassignServiceMethodsSelected() {
        var service_methods = [];
		$("#service_methods input.cb:checked").each(function(i, ele) {			
			service_methods.push($(ele).val());
		});
		
		if (service_methods.length > 0) {			
			$("#unassign_service_methods_modal").modal('show');
			$("#unassign_service_methods_message")
				.show()
				.removeClass("alert-success")
				.removeClass("alert-danger")
				.addClass("alert-info")
				.html("Unassigning service methods...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('api/keys/unassign-service-methods/' . $this->id); ?>',
				data: {
					service_method_id: service_methods.join(',')
				}
			}).done(function(data) {
				$("#unassign_service_methods_message")
					.removeClass("alert-info")
					.addClass("alert-success")
					.html("Successfully unassigned service methods");
				
				setTimeout(function() {
					$("#unassign_service_methods_message").hide();					
					$("#unassign_service_methods_modal").modal('hide');
					
					if ($.fn.DataTable.isDataTable('#service_methods')) {
						$("#service_methods").dataTable().api().ajax.reload();
					}
				}, 1000);
			}).fail(function(error) {
				if (error.responseJSON && error.responseJSON['error']) {
					error = error.responseJSON['error'];
				} else {
					error = 'Unable to unassign service methods, try again';
				}
				
				$("#unassign_service_methods_message")
					.removeClass("alert-info")
					.addClass("alert-danger")
					.html(error);
			});
		}
    }
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="unassign_service_methods_modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Unassign Service Method
				</div>
			</div>
			<form id="unassign_service_methods" class="form-horizontal">
				<div class="modal-body">
					<div id="unassign_service_methods_message" style="display: none;" class="alert alert-info no-margin"></div>					
				</div>
			</form>
		</div>
	</div>
</div>