<?php include(__DIR__ . "/layout/layout.phtml"); ?>

<?php $this->placeholder('heading')->captureStart(); ?>
View All Tickets & Incidents
<?php $this->placeholder('heading')->captureEnd() ;?>

<?php $this->placeholder('breadcrumb')->captureStart(); ?>
<li class="active">
	<a href="<?php echo $this->basePath('ticket/tickets/'); ?>">View All Tickets &amp; Incidents</a>
</li>
<?php $this->placeholder('breadcrumb')->captureEnd() ;?>

<?php $this->placeholder('header')->captureStart('SET'); ?>
<div class="row">
	<div class="col-xs-12">
		<div class="row">
			<div class="col-sm-8">
				<h1>
					Tickets
					<small>
						<i class="ace-icon fa fa-angle-double-right"></i>
						View All Tickets &amp; Incidents
					</small>
				</h1>
			</div>
			<div class="col-sm-4">
				<form method="get" id="filter" class="form-inline align-right">
					<div class="form-group">
						<label for="system_id">System</label>
						<input id='system_id'
							   name='system_id'
							   type='hidden'
							   placeHolder='System'
							   value="<?php echo $this->system_id; ?>"
							   class="align-left"
							   style="width: 180px;" />
						<div class="space-4 hidden-xs"></div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<?php $this->placeholder('header')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = $("#tickets").DataTable({
			processing: true,
			serverSide: true,
			ajax: {
				data: function(d) {
					$.datatables_utils.normalize_data(d);
					
					<?php if($this->system_id) { ?>
					d['system_id'] = '<?php echo $this->system_id; ?>';
					<?php } ?>
				},
				url: "<?php echo $this->basePath('ticket/rest/all-ticket-incidents/'); ?>"
			},
			oLanguage: {
				sEmptyTable: "No tickets or incidents matched",
				sProcessing: "",
				sSearch: "Search",
				sSearchPlaceholder: "Search tickets & incidents"
			},
			iDisplayLength: 25,
			stateSave: false,
			deferRender: true,
			searchDelay: 500,
			responsive: {
				details: {
					renderer: function(api, row, columns) {
						return $.datatables_utils.responsive_renderer(api, row, columns, table);
					}
				}
			},
			columns: [
				{ data: 'id', orderable: false, searchable: false, render: $.datatables_utils.format_empty, className: 'control' },
				{ data: 'id', orderable: false, searchable: false, render: function(val, type, data, options) {
					return "<div class='inline pos-rel'>"
							+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
								+ "Actions "
								+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
							+ "</button>"
							+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>"
								<?php if($this->authorization()->isPermitted('Ticket::Tickets', 'view')) { ?>
								+ "<li>"
									+ "<a data-rel='tooltip' href='<?php echo $this->basePath('ticket/tickets/view/'); ?>" + val + "'>"
										+ "<span class='green'>"
											+ "<i class='ace-icon fa fa-image bigger-120'></i>"
											+ " View"
										+ "</span>"
									+ "</a>"
								+ "</li>"
								<?php } ?>
								<?php if($this->authorization()->isPermitted('Ticket::Tickers', 'edit')) { ?>
								+ "<li>"
									+ "<a data-rel='tooltip' href='<?php echo $this->basePath('ticket/tickets/edit/'); ?>" + val + "'>"
										+ "<span class='blue'>"
											+ "<i class='ace-icon fa fa-edit bigger-120'></i>"
											+ " Edit"
										+ "</span>"
									+ "</a>"
								+ "</li>"
								<?php } ?>
							+ "</ul>"
						+ "</div>";
				}, className: 'action-col all' },                
				{ data: 'name', searchable: true, render: function(val, type, data) {
					val = (val == null || val == '') ? 'N/A' : val;
					
					<?php if($this->authorization()->isPermitted('Ticket::Tickets', 'view')) { ?>
					return "<a href='<?php echo $this->basePath('ticket/tickets/view/'); ?>" + data.id + "'>" + val + "</a>";
					<?php } else { ?>
					return val;
					<?php } ?>
				}, className: 'all' },
                { data: 'title', searchable: true },
				{ data: 'status', searchable: true },
				{ data: 'contact', searchable: true },
                { data: 'submitted_on', searchable: false, render: $.datatables_utils.format_date }
			],
			order: [[6, "desc"]],
			fnPreDrawCallback: function() {
				$("#tickets_info").html("Loading tickets...");
				return true;
			}
		});
		
		// initialize the complex selects
		var selects = [{
			id: 'system_id',
			url: '<?php echo $this->basePath("ticket/rest/systems/"); ?>',
			onChange: function() {
				$("#filter").submit();
			},
			onData: function(data) {
				data['is_active'] = 1;
			}
		}];
		
		$.select2_utils.create(selects, 25);
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="tickets" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th style="min-width: 40px; max-width: 40px;"></th>
					<th style="min-width: 80px;">Name</th>
					<th style="min-width: 100px;">Title</th>
					<th style="min-width: 80px;">Status</th>
					<th style="min-width: 100px;">Contact</th>
					<th style="min-width: 80px;">Submitted On</th>
				</tr>
			</thead>
		</table>
	</div>
</div>
<?php $this->placeholder('content')->captureEnd(); ?>