<?php include(__DIR__ . "/layout/layout.phtml"); ?>
<?php $this->placeholder('heading')->captureStart(); ?>
Permissions
<?php $this->placeholder('heading')->captureEnd() ;?>

<?php $this->placeholder('breadcrumb')->captureStart(); ?>
<li class="active">
	<a href="<?php echo $this->basePath('auth/security/permissions/'); ?>">Permissions</a>
</li>
<?php $this->placeholder('breadcrumb')->captureEnd() ;?>

<?php $this->placeholder('header')->captureStart('SET'); ?>
<div class="row no-padding no-margin">
	<div class="col-sm-8 no-padding no-margin">
		<h1>
			Security
			<small>
				<i class="ace-icon fa fa-angle-double-right"></i>
				Permissions
			</small>
		</h1>
	</div>
	<div class="col-sm-4 no-padding no-margin">
		<div class="btn-toolbar no-padding no-margin" role="toolbar">
			<div class="btn-group pull-right" role="group">
				<?php if($this->authorization()->isPermitted('Auth::Security', 'permissions-add')) { ?>
				<a href="#"
				   class="btn btn-xs btn-primary"
				   data-toggle="modal"
				   data-target="#add_permission_modal">
					<i class="ace-icon fa fa-plus"></i>
					Add New Permission
				</a>
				<?php } ?>
			</div>
		</div>
	</div>
</div>
<?php $this->placeholder('header')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = $("#permissions").DataTable({
			processing: true,
			serverSide: true,
			ajax: {
				data: $.datatables_utils.normalize_data,
				url: "<?php echo $this->basePath('auth/rest/permissions/'); ?>"
			},
			oLanguage: {
				sEmptyTable: "No permissions matched",
				sProcessing: "",
				sSearch: "Search",
				sSearchPlaceholder: "Search permissions"
			},
			iDisplayLength: 25,
			stateSave: false,
			deferRender: true,
			searchDelay: 500,
			responsive: {
				details: {
					renderer: function(api, row, columns) {
						return $.datatables_utils.responsive_renderer(api, row, columns, table);
					}
				}
			},
			columns: [
				{ data: 'id', orderable: false, searchable: false, render: $.datatables_utils.format_empty, className: 'control' },
				{ data: 'id', orderable: false, searchable: false, render: function(val, type, data, options) {
					return "<div class='inline pos-rel'>"
								+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
									+ "Actions "
									+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
								+ "</button>"
								+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>"
									<?php if($this->authorization()->isPermitted('Auth::Security', 'permissions-edit')) { ?>
									+ "<li>"
										+ "<a data-rel='tooltip' href='<?php echo $this->basePath('auth/security/permissions-edit/'); ?>" + val + "'>"
											+ "<span class='blue'>"
												+ "<i class='ace-icon fa fa-edit bigger-120'></i>"
												+ " Edit"
											+ "</span>"
										+ "</a>"
									+ "</li>"
									<?php } ?>
									<?php if($this->authorization()->isPermitted('Auth::Security', 'permissions-delete')) { ?>
									+ "<li>"
										+ "<a role='button' href='javascript: void(0);' data-rel='tooltip' onclick=\"deletePermission('" + options.row + "')\">"
											+ "<span class='red'>"
												+ "<i class='ace-icon fa fa-trash bigger-120'></i>"
												+ " Delete"
											+ "</span>"
										+ "</a>"
									+ "</li>"
									<?php } ?>
								+ "</ul>"
							+ "</div>";
				}, className: 'action-col' },
				{ data: 'name', searchable: true, render: function(val, type, data) {
					<?php if($this->authorization()->isPermitted('Auth::Security', 'permissions-edit')) { ?>
					return "<a href='<?php echo $this->basePath('auth/security/permissions-edit/'); ?>" + data.id + "'>" + val + "</a>";
					<?php } else { ?>
					return val;
					<?php } ?>
				}, className: 'all' },
				{ data: 'description', searchable: true, render: $.proxy($.datatables_utils.format_length, null, 60) },
				{ data: 'roles', orderable: false, searchable: false, className: 'center' },
				{ data: 'resources', orderable: false, searchable: false, className: 'center' }
			],
			order: [[2, "asc"]],
			fnPreDrawCallback: function() {
				$("#permissions_info").html("Updating permissions...");
				return true;
			}
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="permissions" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th style="width: 80px;"></th>
					<th style="min-width: 100px;">Name</th>
					<th style="min-width: 100px;">Description</th>
					<th style="min-width: 100px;"># Assigned Roles</th>
					<th style="min-width: 100px;"># Assigned Resources</th>				
				</tr>
			</thead>
		</table>
	</div>
</div>
<?php if($this->authorization()->isPermitted('Auth::Security', 'permissions-add')) { ?>
<?php include(__DIR__ . "/pane/add-permission.phtml"); ?>
<?php } ?>
<?php if($this->authorization()->isPermitted('Auth::Security', 'permissions-delete')) { ?>
<?php include(__DIR__ . "/pane/delete-permission.phtml"); ?>
<?php } ?>
<?php $this->placeholder('content')->captureEnd(); ?>