<?php include(__DIR__ . "/layout/layout.phtml"); ?>
<?php
$this->formElementErrors()
	 ->setAttributes(array('class' => 'list-unstyled'));
?>

<?php $this->placeholder('heading')->captureStart(); ?>
Update Permission
<?php $this->placeholder('heading')->captureEnd() ;?>

<?php $this->placeholder('breadcrumb')->captureStart(); ?>
<li>
	<a href="<?php echo $this->basePath('auth/security/permissions/'); ?>">Permissions</a>
</li>
<li class="active">
	<a href="<?php echo $this->basePath('auth/security/permissions-edit/' . $this->id); ?>">Update Permission (<?php echo $this->permission['name']; ?>)</a>
</li>
<?php $this->placeholder('breadcrumb')->captureEnd() ;?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {		
		var fields = {
			name: {
				required: true,
				message: 'Please provide a Name'
			}
		};
		$.validate_utils.create('#permission', fields);
		
		<?php if($this->success) { ?>
		setTimeout(function() {
			$("#success-msg").hide();
		}, 2000);
		<?php } ?>
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<?php $this->placeholder('header')->captureStart('SET'); ?>
<h1>
	Security
	<small>
		<i class="ace-icon fa fa-angle-double-right"></i>
		Update Permission
	</small>
</h1>
<?php $this->placeholder('header')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<div class="row">
	<div class="col-xs-12">
		<form id="permission" method="post" role="form" class="form-horizontal">
			<?php if ($this->error) { ?>
				<div class="alert alert-danger alert-dismissible">
					<?php echo $this->error; ?>
				</div>
			<?php } ?>
			
			<?php if ($this->success) { ?>
				<div id="success-msg" class="alert alert-success alert-dismissible">
					<?php echo $this->success; ?>
				</div>
			<?php } ?>
			
			<div class="alert alert-warning">
				All fields with an <i class="ace-icon fa fa-asterisk red"></i> are required.
			</div>
			
			<?php $error = ($this->form->has('name')) ? $this->formElementErrors($this->form->get('name')) : ""; ?>
			<div class="form-group <?php echo ($error) ? "has-error" : ""; ?>">
				<label class="col-sm-2 control-label no-padding-right" for="name">Name </label>
				<div class="col-sm-5">
					<span class="block input-icon input-icon-right">
						<input type="text"
							   id="name"
							   name="name"
							   placeholder="Permission name"
							   value="<?php echo $this->post['name']; ?>"
							   class="width-100" />
						<i class="ace-icon fa fa-asterisk red" style="margin-right: 15px;"></i>
					</span>
					<?php if ($error) { ?>
					<div id="name-error" class="help-block">
						<?php echo $error; ?>
					</div>
					<?php } ?>
				</div>
			</div>
			
			<div class="form-group">
				<label class="col-sm-2 control-label no-padding-right" for="description">Description </label>
				<div class="col-sm-5">
					<span class="block input-icon input-icon-right">
						<textarea id="description"
								  name="description"
								  placeholder="Permission description"
								  class="width-100"><?php echo $this->post['description']; ?></textarea>
					</span>
				</div>
			</div>
			
			<div class="form-group">
				<label class="col-sm-2"></label>
				<div class="col-sm-9">
					<a class="btn btn-sm" href="<?php echo $this->basePath('auth/security/permissions/'); ?>">
						<i class="ace-icon fa fa-remove align-top bigger-125"></i>
						Cancel
					</a>
					<button class="btn btn-sm btn-primary"
							type="submit">
						<i class="ace-icon fa fa-check align-top bigger-125"></i>
						Update
					</button>
				</div>
			</div>
		</form>
	</div>
</div>
<div class="row tabbable">
	<div class="col-xs-12">
		<div class="btn-group pull-right bring-front">
			<button type="button" class="btn btn-xs btn-inverse dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Tab Actions
				<span class="ace-icon fa fa-caret-down icon-only"></span>
			</button>
			<ul class="dropdown-menu dropdown-inverse dropdown-white dropdown-menu-right">
				<?php if($this->authorization()->isPermitted('Auth::Security', 'permissions-assign-resources')) { ?>
				<li>
					<a data-toggle='modal' href='#assign_permission_resources_modal'>
						<i class="ace-icon fa fa-plus"></i>
						Assign Resources
					</a>
				</li>
				<?php } ?>
				<?php if($this->authorization()->isPermitted('Auth::Security', 'permissions-assign-roles')) { ?>
				<li>
					<a data-toggle='modal' href="#assign_permission_roles_modal">
						<i class="ace-icon fa fa-plus"></i>
						Assign Roles
					</a>
				</li>
				<?php } ?>
			</ul>
		</div>
		<ul class="nav nav-tabs">
			<li class="active">
				<a data-toggle="tab" href="#resources_pane" id="resources_a">Resources</a>
			</li>
			<li>
				<a data-toggle="tab" href="#roles_pane" id="roles_a">Roles</a>
			</li>
		</ul>
		<div class="tab-content">
			<div id="resources_pane" class="tab-pane fade in active">
				<?php include(__DIR__ . "/pane/permission-resources.phtml"); ?>
			</div>
			<div id="roles_pane" class="tab-pane fade">
				<?php include(__DIR__ . "/pane/permission-roles.phtml"); ?>
			</div>		
		</div>
	</div>
</div>
<?php if($this->authorization()->isPermitted('Auth::Security', 'permissions-assign-resources')) { ?>
<?php include(__DIR__ . "/pane/assign-permission-resources.phtml"); ?>
<?php } ?>
<?php if($this->authorization()->isPermitted('Auth::Security', 'permissions-assign-roles')) { ?>
<?php include(__DIR__ . "/pane/assign-permission-roles.phtml"); ?>
<?php } ?>
<?php $this->placeholder('content')->captureEnd(); ?>