<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		$('#add_status').on('submit', function() {
			var name = $("#add_status_name").val();
			var user_selectable = $("#add_status_selectable").prop('checked') ? 1 : 0;
			
			$("#add_status_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Adding new contract status...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('contract/statuses/add/'); ?>',
				data: { 
					name: name,
					user_selectable: user_selectable 
				}
			}).done(function(data) {
				if (data.status == 1) {
					$("#add_status_message")
						.removeClass("label-default")
						.addClass("label-success")
						.html("Successfully added new contract status");
					
					setTimeout(function() {
						$("#add_status_message").hide();
						
						$("#add-status-modal").modal('hide');
						reloadStatusesTable();
					}, 1000);
				} else {
					$("#add_status_message")
						.removeClass("label-default")
						.addClass("label-danger");
						
					if (data.error) {
						if ($.isArray(data.error)) {
							$("#add_status_message").html(data.error.join('<br />'));
						} else {
							$("#add_status_message").html(data.error);
						}
					} else {
						$("#add_status_message").html("Unable to add new contract status, please try again");
					}
				}
			}).fail(function(error) {
				$("#add_status_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html("Unable to add new contract status, please try again");
			});
			
			// prevent the page submit
			return false;
		});
	});
	
	function addStatus() {
		$("#add_status_message").hide();
		$("#add_status_name").val('');
	}
	
	function reloadStatusesTable() {
		$("#statuses").dataTable().api().ajax.reload();
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="add-status-modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Add New Contract Status
				</div>
			</div>
			<form id="add_status" class="form-horizontal">
				<div class="modal-body no-padding">				
					<div class="row no-padding no-margin">
						<div class="alert alert-warning">
							All fields with an <i class="ace-icon fa fa-asterisk red"></i> are required.  Provide the Contract Status name.
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="add_status_name">Contract Status </label>
						<div class="col-sm-8">
							<span class="block input-icon input-icon-right">
								<input type="text"
									   id="add_status_name"
									   name="add_status_name"
									   placeholder="New Contract Status Name"
									   class="width-100" />
							</span>
						</div>
					</div>
								
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="add_status_selectable">User Selectable? </label>
						<div class="col-sm-8">
							<span class="block input-icon input-icon-right">
								<input name='add_status_selectable'
									id='add_status_selectable'
									type='checkbox'
									class='ace ace-switch ace-switch-2'
									checked
									value='1' />
								<span class='lbl' style='vertical-align: text-top;'></span>
							</span>
						</div>
					</div>
				</div>
				<div class="space-6"></div>
				<div class="modal-footer">
					<button class="btn btn-sm pull-left"
							type="button"
							data-dismiss="modal">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</button>
					<button class="btn btn-sm btn-primary pull-left"
							type="submit">
						<i class="ace-icon fa fa-plus bigger-125"></i>
						Add
					</button>
					<div id="add_status_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>