<?php include(__DIR__ . "/layout/layout.phtml"); ?>

<?php $this->placeholder('style')->captureStart(); ?>
<style type="text/css">
	.tags {
		display: block !important;
		width: 100% !important;
	}
</style>
<?php $this->placeholder('style')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {				
		// Initialize the file upload
		$("input.doc-upload").ace_file_input({
			style: 'well',
			btn_choose: 'Click to choose a document',
			btn_change: null,
			no_icon: 'ace-icon fa fa-file-text-o',
			droppable: true,
			thumbnail: 'small'
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<?php $this->placeholder('header')->captureStart('SET'); ?>
<h1>
	Contracts
	<small>
		<i class="ace-icon fa fa-angle-double-right"></i>
		Upload Documents
	</small>
</h1>
<?php $this->placeholder('header')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<form id="contract"
	  method="post"
	  role="form"
	  class="form-horizontal"
	  enctype="multipart/form-data">
	<?php if ($this->success) { ?>
		<div class="alert alert-success alert-dismissible">
			<?php echo $this->success; ?>
		</div>
	<?php } ?>
	
	<?php if ($this->error) { ?>
		<div class="alert alert-danger alert-dismissible">
			<?php echo $this->error; ?>
		</div>
	<?php } ?>
	
	<?php for($i = 0; $i < 2; $i++) { ?>
	<div class="form-group">
		<label class="col-sm-2 control-label no-padding-right" for="ext_docs[<?php echo $i; ?>]">External Document </label>
		<div class="col-sm-9">
			<span class="block input-icon input-icon-right">
				<input name="ext_docs[<?php echo $i; ?>]"
						id="ext_docs[<?php echo $i; ?>]"
						placeholder="External Document URL"
						value="<?php echo $this->post['ext_docs'][$i]; ?>"
						class="form-control" />
			</span>
		</div>
	</div>
	<?php } ?>
	
	<div class="form-group">
		<label class="col-sm-2 control-label no-padding-right">Upload Documents </label>
		<div class="col-sm-9 no-padding-left">
			<div class="col-sm-3">
				<input type="file"
					   id="doc1"
					   name="doc1"
					   class="doc-upload" />
			</div>
			<div class="col-sm-3">
				<input type="file"
					   id="doc2"
					   name="doc2"
					   class="doc-upload"/>
			</div>
			<div class="col-sm-3">
				<input type="file"
					   id="doc3"
					   name="doc3"
					   class="doc-upload"/>
			</div>
			<div class="col-sm-3">
				<input type="file"
					   id="doc4"
					   name="doc4"
					   class="doc-upload"/>
			</div>
		</div>
	</div>
			
	<?php if($this->post['docs']) { ?>
		<div class="form-group">
		<?php $counter = 0; ?>
		<?php foreach($this->post['docs'] as $doc) { ?>
			<?php if ($counter == 0) { ?>
			<div class="col-sm-2"></div>
			<div class="col-sm-9 no-padding-left">
			<?php } ?>
				<div class="col-sm-3">
					<span>
						<label>
							<input type="checkbox"
								   class="ace"
								   name="delete_doc[]"
								   value="<?php echo $doc['id']; ?>" />
							<span class="lbl">
								<i class="ace-icon fa fa-trash red"
								   title="Delete this doc"></i>
							</span>
						</label>
						<?php $extension = array_pop(explode('.', $doc['path'])); ?>
						
						<?php if($extension == 'xls' || $extension == 'xlsx') { ?>
						<i class="ace-icon fa fa-file-excel-o bigger-300 middle green"></i>
						<?php } else if($extension == 'doc' || $extension == 'docx') { ?>
						<i class="ace-icon fa fa-file-word-o bigger-300 middle blue"></i>
						<?php } else if($extension == 'ppt' || $extension == 'pptx') { ?>
						<i class="ace-icon fa fa-file-powerpoint-o bigger-300 middle red"></i>
						<?php } else if($extension == 'pdf') { ?>
						<i class="ace-icon fa fa-file-pdf-o bigger-300 middle red"></i>
						<?php } else if(in_array($extension, array('zip', 'rar', 'gz'))) { ?>
						<i class="ace-icon fa fa-file-archive-o bigger-300 middle purple"></i>
						<?php } else { ?>
						<i class="ace-icon fa fa-file-o bigger-300 middle"></i>
						<?php } ?>
					</span>
					<br />
					<span class="text-muted">
						<?php
							if(strlen($doc['name']) > 20) {
								echo substr($doc['name'], 0, 20) . "...";
							} else {
								echo $doc['name'];
							}
						?>
					</span>
				</div>
			<?php if ($counter == 3) { ?>
			</div>
			<?php }  ?>
			<?php
				$counter++;
				$counter = $counter % 4;
			?>
		<?php } ?>
		
		<?php if ($counter > 0) { ?>
			<?php for($i = $counter; $i < 4; $i++) { ?>
				<div class="col-sm-3"></div>
				<?php if ($i == 3) { ?>
				</div>
				<?php } ?>
			<?php } ?>
		<?php } ?>
		</div>
	<?php } ?>
	
	<div class="form-group">
		<label class="col-sm-2"></label>
		<div class="col-sm-9">
			<a class="btn btn-sm" href="<?php echo $this->wizard()->getRedirect('contract', $this->basePath('contract/contracts/')); ?>">
				<i class="ace-icon fa fa-close align-top bigger-125"></i>
				Back
			</a>
			<button class="btn btn-sm btn-primary"
					type="submit">
				<i class="ace-icon fa fa-check align-top bigger-125"></i>
				Next
			</button>
		</div>
	</div>
</form>
<?php $this->placeholder('content')->captureEnd(); ?>