<?php include(__DIR__ . "/layout/layout.phtml"); ?>

<?php $this->placeholder('breadcrumb')->captureStart('APPEND'); ?>
<li>
	<a href="<?php echo $this->basePath('contract/contracts/by-quarter/'); ?>">By Quarter</a>
</li>
<?php $this->placeholder('breadcrumb')->captureEnd(); ?>

<?php $this->placeholder('header')->captureStart('SET'); ?>
<div class="row">
	<div class="col-sm-8">
		<h1>
			Contracts
			<small>
				<i class="ace-icon fa fa-angle-double-right"></i>
				By Quarter
			</small>
		</h1>
	</div>
</div>
<?php $this->placeholder('header')->captureEnd(); ?>

<?php $this->placeholder('style')->captureStart(); ?>
<style type="text/css">
	.cursor-hand {
		cursor: pointer;
		cursor: hand;
	}
</style>
<?php $this->placeholder('style')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	var status_text_deleted = 'Deleted';

	$(document).ready(function() {
		var table = $("#payments").DataTable({
			serverSide: true,	
			ajax: {
				url: "<?php echo $this->basePath('contract/rest/payment-by-quarter/'); ?>",
				data: function(d) {
					$.datatables_utils.normalize_data(d);
					d['>end_date'] = '<?php echo $this->today['date']; ?>';
				}
			},
			columns: [
				{ data: 'id', searchable: false, sortable: false, render: function(val, type, data, options) {
					var str = "<span class='expander cursor-hand'>"
						+ "<span class='ace-icon fa fa-plus-circle center bigger-110'></span>"
						+ "</span>"
						;
					
					return str;
				} },
			    { data: 'id', searchable: false, render: function(val, type, data, options) {
					return "<div class='inline pos-rel'>"
					+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
						+ "Actions "
						+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
					+ "</button>"
					+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>"
						<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'by-quarter-view')) { ?>
						+ "<li>"
							+ "<a data-rel='tooltip' href='<?php echo $this->basePath('contract/contracts/by-quarter-view/'); ?>" + val + "'>"
								+ "<span class='green'>"
									+ "<i class='ace-icon fa fa-image bigger-120'></i>"
									+ " View"
								+ "</span>"
							+ "</a>"
						+ "</li>"
						<?php } ?>
					+ "</ul>"
				+ "</div>"; 
			    }},
				{ data: 'fiscal_year', searchable: true },
			    { data: 'fiscal_quarter', searchable: true },
			    { data: 'start_date', searchable: true },
			    { data: 'end_date', searchable: true },
			    { data: 'payments_amount_scheduled', searchable: false },
			    { data: 'payments_count_scheduled', searchable: false },
			    { data: 'payments_amount_paid', searchable: false },
			    { data: 'payments_count_paid', searchable: false }
			],
		})
		.on('draw.dt', function() {
			var url = '<?php echo $this->basePath('contract/export/payment-by-quarter/'); ?>';
			url += '?>end_date=<?php echo $this->today['date']; ?>';
			
			var params = table.ajax.params();
			if(params.search) {
				url += '&' + params.search.fields[0] + '=' + params.search.value;
			}

			<?php if ($this->authorization()->isPermitted('Contract::Export', 'payment-by-quarter')) { ?>
			addExportButton(url);
			<?php } ?>
		});
	    // Add event listener for opening and closing details
	    $('#payments tbody').on('click', 'span.expander', function () {
	        var tr = $(this).closest('tr');
	        var row = table.row( tr );
			var td = tr.children('td');
			td = td.eq(0);
			td = td.children('span.expander');

	        if ( row.child.isShown() ) {
	            // This row is already open - close it
	            row.child.hide();
	            tr.removeClass('shown');
	            td.html("<span class='ace-icon fa fa-plus-circle center bigger-110'></span>");
	        }
	        else {
	            // Open this row
	            row.child( printContracts(row.data()) ).show();
	            tr.addClass('shown');
	            td.html("<span class='ace-icon fa fa-minus-circle center bigger-110'></span>");
	        }
		});
	});

	function printContracts(d) {
		var start_date = d.start_date;
		var end_date = d.end_date;
		var max_lines_printed = 15;

		//since we want to subtract a day for the check, we won't add one to the day here (normally we add 1)
		var date1 = new Date(start_date);

		var start_date_year = date1.getFullYear();
		var start_date_month = date1.getMonth()+1;
		var start_date_day = date1.getDate();

		//since we want to add a day for the check, we'll add an extra day here (normally we add 1)
		var date2 = new Date(end_date);
		date2.setDate(date2.getDate() + 2);

		var end_date_year = date2.getFullYear();
		var end_date_month = date2.getMonth()+1;
		var end_date_day = date2.getDate();
		
		var start_date_check = start_date_year+'-'+start_date_month+'-'+start_date_day;
		var end_date_check = end_date_year+'-'+end_date_month+'-'+end_date_day;

		var str_no_contracts = 'There are currently no contracts/payments for this quarter.';
		var str = '<table style="width: 60%;" role="grid" class="table table-hover dataTable no-footer">';
		str += '<tr role="row">'
			+ '<th style="width: 40px;"></th>'
			+ '<th>Vendor</th>'
			+ '<th>Contract Type</th>'
			+ '<th>Description</th>'
			+ '<th>Contract Number</th>'
			+ '<th>Payment Type</th>'
			+ '<th>Payment Date</th>'
			+ '<th>Amount</th>'
			+ '</tr>';

		var i = 0;
		$.ajax({
			url: "<?php echo $this->basePath('contract/rest/payments/?sort(+payment_date)'); ?>",
			data: { 
				'>payment_date': start_date_check,
				'<payment_date': end_date_check,
				'!contract_status' : status_text_deleted
			},
			dataType: 'json',
			async: false
		}).done(function(data) {
			$.each(data, function(idx, obj) {
 				i++;
 				if(i>max_lines_printed) {
 					var number_left = data.length-i+1;
 					str += '<tr><td></td><td colspan=8><b>(' + number_left	 + ' more)</b></td></tr>';
 					return false; //break loop
 				}

				str += '<tr role="row">'
					+ '<td style="width: 40px;">'
					+"<div class='inline pos-rel'>"
						+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
							+ " "
							+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
						+ "</button>"
						+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>"
							<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'view')) { ?>
							+ "<li>"
								+ "<a data-rel='tooltip' href='<?php echo $this->basePath('contract/contracts/view/'); ?>" + obj.contract_id + "'>"
									+ "<span class='green'>"
										+ "<i class='ace-icon fa fa-image bigger-120'></i>"
										+" View"
									+ "</span>"
								+ "</a>"
							+ "</li>"
							<?php } ?>
						+ "</ul>"
					+ "</div>"
					+'</td><td>'
					+obj.contract_vendor
					+'</td><td>'
					+obj.contract_type
					+'</td><td>'
					+obj.contract_description
					+'</td><td>'
					+obj.contract_number
					+'</td><td>'
					+obj.payment_type
					+'</td><td>'
					+obj.payment_date
					+'</td><td>'
					+obj.amount
					+'</td></tr>';
			});

		});

		str += '</table>';

		if(i==0) {
			str = str_no_contracts;
		}

		return str;
	}

	function addExportButton(url) {
		$('#payments_paginate').prepend("<a class=\"btn btn-sm btn-success btn-bold align-top\" "
			+ "id=\"payments_export_link\" "
			+ "href='"+url+"'"
			+ ">"
			+ "Excel Export"
			+ "</a>");
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<div class="row no-margin">
	<div class="widget-body no-padding">
		<div class="widget-table no-padding">
			<table id="payments" class="table table-striped table-hover" width="100%">
				<thead>
					<tr>
						<th style="max-width: 30px;"></th>
						<th style="max-width: 140px;"></th>
						<th>Fiscal Year</th>
						<th>Fiscal Quarter</th>
						<th>Start Date</th>
						<th>End Date</th>
						<th>Due Amount ($)</th>
						<th>Due Count</th>
						<th>Paid Amount ($)</th>
						<th>Paid Count</th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
<?php $this->placeholder('content')->captureEnd(); ?>