<?php include(__DIR__ . "/layout/layout.phtml"); ?>

<?php $this->placeholder('breadcrumb')->captureStart('APPEND'); ?>
<li>
	<a href="<?php echo $this->basePath('contract/contracts/by-quarter/'); ?>">Payment By Quarter</a>
</li>
<li>
	<a href="<?php echo $this->basePath('contract/contracts/by-quarter-view/'.$this->id); ?>"><?php echo $this->fiscal_quarter . ' FY' . $this->fiscal_year; ?></a>
</li>
<?php $this->placeholder('breadcrumb')->captureEnd(); ?>

<?php $this->placeholder('header')->captureStart('SET'); ?>
<h1>
	Contracts
	<small>
		<i class="ace-icon fa fa-angle-double-right"></i>
		By Quarter
	</small>
</h1>
<?php $this->placeholder('header')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	var status_text_deleted = 'Deleted';
	
	$(document).ready(function() {
		var start_date = '<?php echo $this->start_date; ?>';
		var end_date = '<?php echo $this->end_date; ?>';

		//since we want to subtract a day for the check, we won't add one to the day here (normally we add 1)
		var date1 = new Date(start_date);

		var start_date_year = date1.getFullYear();
		var start_date_month = date1.getMonth()+1;
		var start_date_day = date1.getDate();

		//since we want to add a day for the check, we'll add an extra day here (normally we add 1)
		var date2 = new Date(end_date);
		date2.setDate(date2.getDate() + 2);

		var end_date_year = date2.getFullYear();
		var end_date_month = date2.getMonth()+1;
		var end_date_day = date2.getDate();
		
		var start_date_check = start_date_year+'-'+start_date_month+'-'+start_date_day;
		var end_date_check = end_date_year+'-'+end_date_month+'-'+end_date_day;
		
		var table = $("#payments").DataTable({
			serverSide: true,	
			ajax: {
				url: "<?php echo $this->basePath('contract/rest/payments/'); ?>",
				data: function(d) {
					$.datatables_utils.normalize_data(d);
					d['>payment_date'] =  start_date_check;
					d['<payment_date'] =  end_date_check;
					d['!contract_status'] =  status_text_deleted;
				}
			},
			columns: [
			    { data: 'id', searchable: false, render: function(val, type, data, options) {
					return "<div class='inline pos-rel'>"
						+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
							+ "Actions "
							+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
						+ "</button>"
						+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>"
							<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'view')) { ?>
							+ "<li>"
								+ "<a data-rel='tooltip' href='<?php echo $this->basePath('contract/contracts/view/'); ?>" + data.contract_id + "?pane=payments'>"
									+ "<span class='green'>"
										+ "<i class='ace-icon fa fa-image bigger-120'></i>"
										+ " View"
									+ "</span>"
								+ "</a>"
							+ "</li>"
							<?php } ?>
							<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'edit-payment')) { ?>
							+ "<li>"
								+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"editPayment('" + options.row + "')\">"
									+ "<span class='blue'>"
										+ "<i class='ace-icon fa fa-edit bigger-120'></i>"
										+ " Edit"
									+ "</span>"
								+ "</a>"
							+ "</li>"
							<?php } ?>
						+ "</ul>"
					+ "</div>"; 
			    }},
			    { data: 'contract_vendor', searchable: true },
				{ data: 'contract_type', searchable: true },
				{ data: 'contract_description', searchable: true },
				{ data: 'contract_number', searchable: true },
			    { data: 'payment_type', searchable: true },
			    { data: 'payment_date', searchable: true },
			    { data: 'amount', searchable: true },
			],
		})
		.on('draw.dt', function() {
			var url = '<?php echo $this->basePath('contract/export/payments/'); ?>';
			url += '?>payment_date='+start_date_check;
			url += '&<payment_date='+end_date_check;
			url += '&!contract_status='+status_text_deleted;

			var params = table.ajax.params();
			if(params.search) {
				url += '&' + params.search.fields[0] + '=' + params.search.value;
			}

			<?php if ($this->authorization()->isPermitted('Contract::Export', 'payments')) { ?>
			addExportButton(url);
			<?php } ?>
		});
	});

	function addExportButton(url) {
		$('#payments_paginate').prepend("<a class=\"btn btn-sm btn-success btn-bold align-top\" "
			+ "id=\"payments_export_link\" "
			+ "href='"+url+"'"
			+ ">"
			+ "Excel Export"
			+ "</a>");
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<div class="widget-body">
	<div class="widget-main padding-12">
		<div class="row">
			<div class="col-sm-5">
				<div class="row">
					<div class="col-xs-12 label label-lg label-default align-left">
						<b>Fiscal Quarter Detail</b>
					</div>
				</div>
				<div>
					<ul class="list-unstyled">
						<li class="row">
							<span class="col-xs-4 bolder"><i class="ace-icon fa fa-caret-right blue"></i> Fiscal Year</span>
							<span class="col-xs-8"><?php echo $this->fiscal_year; ?></span>
						</li>
						<li class="row">
							<span class="col-xs-4 bolder"><i class="ace-icon fa fa-caret-right blue"></i> Fiscal Quarter</span>
							<span class="col-xs-8"><?php echo $this->fiscal_quarter; ?></span>
						</li>
						<li class="row">
							<span class="col-xs-4 bolder"><i class="ace-icon fa fa-caret-right blue"></i> Start Date</span>
							<span class="col-xs-8"><?php echo $this->start_date; ?></span>
						</li>
						<li class="row">
							<span class="col-xs-4 bolder"><i class="ace-icon fa fa-caret-right blue"></i> End Date</span>
							<span class="col-xs-8"><?php echo $this->end_date; ?></span>
						</li>
						<li class="row">
							<span class="col-xs-4 bolder"><i class="ace-icon fa fa-caret-right blue"></i> Due Amount ($)</span>
							<span class="col-xs-8"><?php echo $this->payments_amount_scheduled; ?></span>
						</li>
						<li class="row">
							<span class="col-xs-4 bolder"><i class="ace-icon fa fa-caret-right blue"></i> Due Count</span>
							<span class="col-xs-8"><?php echo $this->payments_count_scheduled; ?></span>
						</li>
						<li class="row">
							<span class="col-xs-4 bolder"><i class="ace-icon fa fa-caret-right blue"></i> Paid Amount ($)</span>
							<span class="col-xs-8"><?php echo $this->payments_amount_paid; ?></span>
						</li>
						<li class="row">
							<span class="col-xs-4 bolder"><i class="ace-icon fa fa-caret-right blue"></i> Paid Count</span>
							<span class="col-xs-8"><?php echo $this->payments_count_paid; ?></span>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<br />
<div class="row no-margin">
	<div class="widget-body no-padding">
		<div class="widget-table no-padding">
			<table id="payments" class="table table-striped table-hover" width="100%">
				<thead>
					<tr>
						<th style="max-width: 140px;"></th>
						<th>Vendor</th>
						<th>Contract Type</th>
						<th>Description</th>
						<th>Contract Number</th>
						<th>Payment Type</th>
						<th>Payment Date</th>
						<th>Payment Amount</th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
<?php include(__DIR__ . "/pane/edit-payment.phtml"); ?>
<?php $this->placeholder('content')->captureEnd(); ?>