<?php include(__DIR__ . "/layout/layout.phtml"); ?>

<?php $this->placeholder('header')->captureStart('SET'); ?>
<div class="row">
	<div class="col-sm-8">
		<h1>
			Contracts
		</h1>
	</div>
	<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'add')) { ?>
	<div class="col-sm-4">
		<div class="align-right">
			<div class="btn-group" role="group">
				<a href='<?php echo $this->basePath('contract/contracts/add/'); ?>'
				   class="btn btn-sm btn-primary">
					<i class="ace-icon fa fa-plus"></i>
					Add New
				</a>
			</div>
		</div>
	</div>
	<?php } ?>
</div>
<?php $this->placeholder('header')->captureEnd(); ?>

<?php $this->placeholder('style')->captureStart(); ?>
<style type="text/css">
	#monthly_run_rate_filter {
		display: none;
	}
	#monthly_run_rate_length {
		display: none;
	}
	.cursor-hand {
		cursor: pointer;
		cursor: hand;
	}
</style>
<?php $this->placeholder('style')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	var status_text_active = 'Active';
	var status_text_closed = 'Closed';
	var status_text_deleted = 'Deleted';
	var payment_type_text_renewal = 'Renewal';

	var additional_fields = 'devices_infodots|devices_serials';

	var table;
	var table2;
	$(document).ready(function() {
		table = $("#contracts").DataTable({
			serverSide: true,
			ajax: {
				url: "<?php echo $this->basePath('contract/rest/contracts/'); ?>",
				data: function(d) {
					$.datatables_utils.normalize_data(d,additional_fields);

					d['!status'] = status_text_deleted;
					//on initial load or "Active"
					if(typeof $("#status").val() == 'undefined' || $("#status").val() == status_text_active) {
						d['!status'] = [status_text_closed, status_text_deleted];
					}
					else if($("#status").val() == status_text_closed) {
						d['status'] = status_text_closed;
					}
				}
			},
			columns: [
			    { data: 'id', searchable: false, sortable: false, render: function(val, type, data, options) {
				    var str =
						"<div class='inline pos-rel'>"
							+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
								+ "Actions "
								+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
							+ "</button>"
							+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>"
								<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'view')) { ?>
								+ "<li>"
									+ "<a data-rel='tooltip' href='<?php echo $this->basePath('contract/contracts/view/'); ?>" + val + "'>"
										+ "<span class='green'>"
											+ "<i class='ace-icon fa fa-image bigger-120'></i>"
											+ " View"
										+ "</span>"
									+ "</a>"
								+ "</li>";
								<?php } ?>
							<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'edit')) { ?>
							if(data.status != status_text_closed) {
								str += "<li>"
									+ "<a data-rel='tooltip' href='<?php echo $this->basePath('contract/contracts/edit/'); ?>" + val + "'>"
										+ "<span class='blue'>"
											+ "<i class='ace-icon fa fa-edit bigger-120'></i>"
											+ " Edit"
										+ "</span>"
									+ "</a>"
								+ "</li>";
							}
							<?php } ?>
							<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'renew')) { ?>
							if(data.status != status_text_closed && (!data.next_payment_date || data.next_payment_type == payment_type_text_renewal)) {
								str += "<li>"
									+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"renewContract('" + options.row + "')\">"
										+ "<span class='orange'>"
											+ "<i class='ace-icon fa fa-share bigger-120'></i>"
											+ " Renew"
										+ "</span>"
									+ "</a>"
								+ "</li>";
							}
							<?php } ?>
							<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'archive')) { ?>
							if(data.status != status_text_deleted && data.status != status_text_closed) {
								str += "<li>"
									+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"archiveContract('" + options.row + "')\">"
										+ "<span class='brown'>"
											+ "<i class='ace-icon fa fa-archive bigger-120'></i>"
											+ " Archive"
										+ "</span>"
									+ "</a>"
								+ "</li>";
							}
							<?php } ?>
							<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'delete')) { ?>
							if(data.status != status_text_deleted) {
								str += "<li>"
									+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"deleteContract('" + options.row + "')\">"
										+ "<span class='red'>"
											+ "<i class='ace-icon fa fa-trash bigger-120'></i>"
											+ " Delete"
										+ "</span>"
									+ "</a>"
								+ "</li>";
							}
							<?php } ?>
							<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'export')) { ?>
							str += "<li>"
								+ "<a data-rel='tooltip' href='<?php echo $this->basePath('contract/contracts/export/'); ?>" + val + "'>"
									+ "<span class='green'>"
										+ "<i class='ace-icon fa fa-file-excel-o bigger-120'></i>"
										+ " Export"
									+ "</span>"
								+ "</a>"
							+ "</li>";
							<?php } ?>
							str += "</ul>"
						+ "</div>";
					return str;
			    }},
			    { data: 'vendor', searchable: true, render: function(val, type, data, options) {
				    var str = '';
					<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'view')) { ?>
						str = "<a href='<?php echo $this->basePath('contract/contracts/view/'); ?>" + data.id + "'>"
							+ val
						+ "</a>";
					<?php } else { ?>
						str = val;
					<?php } ?>

					return str;
			    }},
				{ data: 'type', searchable: true },
				{ data: 'status', searchable: true },
			    { data: 'description', searchable: true, render: $.datatables_utils.format_na },
			    { data: 'department', searchable: true, render: $.datatables_utils.format_na },
			    { data: 'contract_number', searchable: true, render: $.datatables_utils.format_na },
			    { data: 'start_date', searchable: true },
			    { data: 'end_date', searchable: true },
			    { data: 'next_payment_amount', searchable: true, render: $.datatables_utils.format_na },
			    { data: 'next_payment_date', searchable: true, render: $.datatables_utils.format_na },
			    { data: 'next_payment_fiscal_year', searchable: true, render: $.datatables_utils.format_na },
			    { data: 'next_payment_fiscal_quarter', searchable: true, render: $.datatables_utils.format_na },
			],
			order: [
				[ 9, "asc" ]
			]
		})
		.on('draw.dt', function() {
			var url = '<?php echo $this->basePath('contract/export/contracts/'); ?>';
			url += '?';

			var params = table.ajax.params();

			if(params["!status"]) {
				var val = params["!status"];
				if(typeof val != "string") {
					val = val.join();
				}
				url += '!status=' + val;
			}
			else {
				url += '!status=' + status_text_deleted;
			}

			if(params.status) {
				url += '&status=' + params.status;
			}

			if(params.search) {
				url += '&' + params.search.fields[0] + '=' + params.search.value;
			}

			addContractsExportButton(url);
		});

		$('.dataTables_filter').prepend(
			"Status: "
			+ "<select id='status' name='status'>"
			+ "<option value='All'>All</option>"
			+ "<option value='Active' selected>Active</option>"
			+ "<option value='Closed'>Closed</option>"
			+ "</select> "
		);

		$(document).on('change', '#status', function() {
			table.draw();
		});

		table2 = $("#monthly_run_rate").DataTable({
			serverSide: true,
			ajax: {
				url: "<?php echo $this->basePath('contract/rest/payment-run-rates-rollup/'); ?>",
				data: function(d) {
					$.datatables_utils.normalize_data(d);
					d['>=year_month'] = '<?php echo $this->today['year_month']; ?>';
					d['<year_month'] = '<?php echo $this->max['year_month']; ?>';
					d['!status'] = status_text_deleted;
				}
			},
			columns: [
			    { data: null, searchable: false, sortable: false, render: function(val, type, data, options) {
					var str = "<span class='expander cursor-hand'>"
						+ "<span class='ace-icon fa fa-plus-circle center bigger-110'></span>"
						+ "</span>"
						;

					return str;
			    }},
			    { data: 'month_name', searchable: true },
			    { data: 'month', searchable: true },
				{ data: 'year', searchable: true },
			    { data: 'amount', searchable: true }
			],
			order: [
				[ 3, "asc" ],
				[ 2, "asc" ],
			]
		})
		.on('draw.dt', function() {
			var url = '<?php echo $this->basePath('contract/export/payment-run-rates-rollup/'); ?>';
			url += '?' + encodeURIComponent('>=year_month') + '=' + encodeURIComponent('<?php echo $this->today['year_month']; ?>');
			url += '&' + encodeURIComponent('<year_month') + '=' + encodeURIComponent('<?php echo $this->max['year_month']; ?>');

			var params = table2.ajax.params();
			if(params.search) {
				url += '&' + encodeURIComponent(params.search.fields[0]) + '=' + encodeURIComponent(params.search.value);
			}

			addRunRateExportButton(url);
		});

	    // Add event listener for opening and closing details
	    $('#monthly_run_rate tbody').on('click', 'span.expander', function () {
	        var tr = $(this).closest('tr');
	        var row = table2.row( tr );
			var td = tr.children('td');
			td = td.eq(0);
			td = td.children('span.expander');

	        if ( row.child.isShown() ) {
	            // This row is already open - close it
	            row.child.hide();
	            tr.removeClass('shown');
	            td.html("<span class='ace-icon fa fa-plus-circle center bigger-110'></span>");
	        }
	        else {
	            // Open this row
	            row.child( printRunRates(row.data()) ).show();
	            tr.addClass('shown');
	            td.html("<span class='ace-icon fa fa-minus-circle center bigger-110'></span>");
	        }
		});
	});

	function addContractsExportButton(url) {
		$('#contracts_paginate').prepend("<a class=\"btn btn-sm btn-success btn-bold align-top\" "
			+ "id=\"contracts_export_link\" "
			+ "href='"+url+"'"
			+ ">"
			+ "Excel Export"
			+ "</a>");
	}

	function addRunRateExportButton(url) {
		$('#monthly_run_rate_paginate').prepend("<a class=\"btn btn-sm btn-success btn-bold align-top\" "
			+ "id=\"monthly_run_rate_export_link\" "
			+ "href='"+url+"'"
			+ ">"
			+ "<i class='ace-icon fa fa-file-excel-o'></i>"
			+ "</a>");
	}

	function printRunRates(d) {
		var month = d.month;
		var year = d.year;

		var max_lines_printed = 15;

		var str_no_run_rates = 'There is currently no run rate for this month.';
		var str = '<table style="width: 80%;" role="grid" class="table table-hover dataTable no-footer">';
		str += '<tr role="row">'
			+ '<th>Vendor</th>'
			+ '<th>Contract Type</th>'
			+ '<th>Description</th>'
			+ '<th>Contract Number</th>'
			+ '<th>Amount</th>'
			+ '</tr>';

		var i = 0;
		$.ajax({
			url: "<?php echo $this->basePath('contract/rest/payment-run-rates/'); ?>",
			data: {
				'month': month,
				'year': year,
				'!status': status_text_deleted
			},
			dataType: 'json',
			async: false
		}).done(function(data) {
			$.each(data, function(idx, obj) {
 				i++;
 				if(i>max_lines_printed) {
 					var number_left = data.length-i+1;
 					str += '<tr><td colspan=2><b>(' + number_left	 + ' more)</b></td></tr>';
 					return false; //break loop
 				}

 				var vendor = obj.vendor;
 				var contract_type = obj.contract_type;
 				var contract_description = obj.contract_description;
 				var contract_number = obj.contract_number;
 				var amount = obj.amount;

 				if(contract_description == '') {
 					contract_description = 'N/A';
 				}
 				if(contract_number == '') {
 					contract_number = 'N/A';
 				}

				str += '<tr role="row">'
					+ '<td>' + vendor + '</td>'
					+ '<td>' + contract_type + '</td>'
					+ '<td>' + contract_description + '</td>'
					+ '<td>' + contract_number + '</td>'
					+ '<td>' + amount + '</td>'
					+'</tr>';
			});
		});

		str += '</table>';

		if(i==0) {
			str = str_no_run_rates;
		}

		return str;
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<div class="row no-margin">
	<div class="widget-body no-padding">
		<div class="widget-table no-padding">
			<table id="contracts" class="table table-striped table-hover" width="100%">
				<thead>
					<tr>
						<th style="max-width: 140px;"></th>
						<th>Vendor</th>
						<th>Type</th>
						<th>Status</th>
						<th>Description</th>
						<th>Department</th>
						<th>Contract Number</th>
						<th>Start Date</th>
						<th>End Date</th>
						<th>Next Payment Amount</th>
						<th>Next Payment Date</th>
						<th style="max-width: 120px;">Next Payment Fiscal Year</th>
						<th style="max-width: 120px;">Next Payment Fiscal Quarter</th>
					</tr>
				</thead>
			</table>
		</div>
		<hr>
		<div class="widget-table no-padding">
			<h4>Monthly Run Rate</h4>
			<table id="monthly_run_rate" class="table table-striped table-hover" width="100%">
				<thead>
					<tr>
						<th style="max-width: 30px;"></th>
						<th>Month Name</th>
						<th>Month</th>
						<th>Year</th>
						<th>Amount</th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
<?php include(__DIR__ . "/pane/renew.phtml"); ?>
<?php include(__DIR__ . "/pane/archive.phtml"); ?>
<?php include(__DIR__ . "/pane/delete.phtml"); ?>
<?php $this->placeholder('content')->captureEnd(); ?>
