<?php include(__DIR__ . "/layout/layout.phtml"); ?>

<?php $this->placeholder('header')->captureStart('SET'); ?>
<h1>
	Contracts
	<small>
		<i class="ace-icon fa fa-angle-double-right"></i>
		Renew Documents
	</small>
</h1>
<?php $this->placeholder('header')->captureEnd(); ?>

<?php $this->placeholder('style')->captureStart(); ?>
<style type="text/css">
	div#documents_filter {
		display: none;
	}
</style>
<?php $this->placeholder('style')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = $("#documents").DataTable({
			serverSide: true,			
			ajax: {
				data: function(d) {
					$.datatables_utils.normalize_data(d);
					d['contract_id'] = '<?php echo $this->renew; ?>';
				},
				url: "<?php echo $this->basePath('contract/rest/contract-documents/'); ?>"
			},
			iDisplayLength: 100,
			stateSave: false,
			deferRender: true,
			searchDelay: 500,
			responsive: {
				details: {
					renderer: function(api, row, columns) {
						return $.datatables_utils.responsive_renderer(api, row, columns, table);
					}
				}
			},
			columns: [
			    { data: 'id', searchable: false, sortable: false, render: function(val, type, data, options) {
			    	return "<input class='ace dev-cb' type='checkbox' value='" + val + "' /><span class='lbl'></span>";
			    }},
				{ data: 'name', searchable: true }
			],
			order: [
				[ 1, "asc" ]
			],
			fnPreDrawCallback: function() {
				$('.dev-cb-all').prop('checked', false);
			},
			fnDrawCallback: function() {
				if($('input.dev-cb-all').prop('checked')) {
					$('#documents input.dev-cb').prop('checked', true);
				} 
				else {
					$('#documents input.dev-cb').prop('checked', false);
				}
			}
		});

		$("input.dev-cb-all").on('click', function() {
			if ($(this).prop('checked')) {
				$("input.dev-cb:not(:disabled)").prop('checked', true);
			} else {
				$("input.dev-cb").prop('checked', false);
			}
		});

		$("#renew_documents").submit(function() {
			var documents = [];
			$("input.dev-cb:checked").each(function(i, ele) {			
				documents.push($(ele).val());
			});

			$("#document_ids").val(documents.join(','));
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<div class="row no-margin">
	<div class="widget-body no-padding">
		<div class="widget-table no-padding">
			<div class="alert alert-info">
				Please select all documents to be added to contract renewal. New documents can be added later.
			</div>
			
			<form id="renew_documents" method="POST" class="form-horizontal">
				<input type='hidden' id='document_ids' name='document_ids' />		
				<table id="documents" class="table table-striped table-hover" width="100%">
					<thead>
						<tr>
							<th style="width: 30px;">
								<input class='ace dev-cb-all' type='checkbox' />
								<span class='lbl'></span>
							</th>
							<th style="min-width: 120px;">Name</th>
						</tr>
					</thead>
				</table>

				<div class="space-6"></div>
				
				<div class="form-group">
					<label class="col-sm-3"></label>
					<div class="col-sm-9">
						<a class="btn btn-sm" href="<?php echo $this->wizard()->getRedirect('contracts', $this->basePath('contract/contracts/')); ?>">
							<i class="ace-icon fa fa-remove align-top bigger-125"></i>
							Cancel
						</a>
						<button class="btn btn-sm btn-primary"
							type="submit">
							<i class="ace-icon fa fa-check align-top bigger-125"></i>
							Submit
						</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

<?php $this->placeholder('content')->captureEnd(); ?>
