<?php include(__DIR__ . "/layout/layout.phtml"); ?>

<?php $this->placeholder('breadcrumb')->captureStart('APPEND'); ?>
<li>
	Admin
</li>
<li>
	<a href="<?php echo $this->basePath('contract/contracts/user-lookup/'); ?>">User Lookup</a>
</li>
<?php $this->placeholder('breadcrumb')->captureEnd(); ?>

<?php $this->placeholder('header')->captureStart('SET'); ?>
<div class="row">
	<div class="col-sm-8">
		<h1>
			Contracts
			<small>
				<i class="ace-icon fa fa-angle-double-right"></i>
				User Lookup
			</small>
		</h1>
	</div>
</div>
<?php $this->placeholder('header')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	var status_text_active = 'Active';
	var status_text_closed = 'Closed';
	var status_text_deleted = 'Deleted';

	var additional_fields = 'devices_infodots|devices_serials'; 
	
	var table;

	$(document).ready(function() {
		// initialize the complex selects
		var contract_lookup_selects = [{
			id: 'user_id',
			url: '<?php echo $this->basePath('hr/rest/hr-users/'); ?>',
			display: 'display_name'
		}];

		$.select2_utils.create(contract_lookup_selects, 25);
		
		table = $("#contracts").DataTable({
			serverSide: true,	
			ajax: {
				url: "<?php echo $this->basePath('contract/rest/contract-lookup/'); ?>",
				data: function(d) {
					$.datatables_utils.normalize_data(d,additional_fields);

					d['!status'] = status_text_deleted;
					//on initial load or "Active"
					if(typeof $("#status").val() == 'undefined' || $("#status").val() == status_text_active) {
						d['!status'] = [status_text_closed, status_text_deleted];
					}
					else if($("#status").val() == status_text_closed) {
						d['status'] = status_text_closed;
					}
					d['user_id'] = $("#user_id").val();
				}
			},
			columns: [
			    { data: 'id', searchable: false, sortable: false, render: function(val, type, data, options) {
				    var str =
						"<div class='inline pos-rel'>"
							+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
								+ "Actions "
								+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
							+ "</button>"
							+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>"
								<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'view')) { ?>
								+ "<li>"
									+ "<a data-rel='tooltip' href='<?php echo $this->basePath('contract/contracts/view/'); ?>" + val + "'>"
										+ "<span class='green'>"
											+ "<i class='ace-icon fa fa-image bigger-120'></i>"
											+ " View"
										+ "</span>"
									+ "</a>"
								+ "</li>";
								<?php } ?>
							str += "</ul>"
						+ "</div>";
					return str; 
			    }},
			    { data: 'vendor', searchable: true, render: function(val, type, data, options) {
				    var str = '';
					<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'view')) { ?>
						str = "<a href='<?php echo $this->basePath('contract/contracts/view/'); ?>" + data.id + "'>"
							+ val
						+ "</a>";
					<?php } else { ?>
						str = val;
					<?php } ?>

					return str; 
			    }},
				{ data: 'type', searchable: true },
				{ data: 'status', searchable: true },
			    { data: 'description', searchable: true, render: $.datatables_utils.format_na },
			    { data: 'department_full', searchable: true, render: $.datatables_utils.format_na },
			    { data: 'contract_number', searchable: true, render: $.datatables_utils.format_na },
			    { data: 'start_date', searchable: true },
			    { data: 'end_date', searchable: true },
			    { data: 'next_payment_amount', searchable: true, render: $.datatables_utils.format_na },
			    { data: 'next_payment_date', searchable: true, render: $.datatables_utils.format_na },
			    { data: 'next_payment_fiscal_year', searchable: true, render: $.datatables_utils.format_na },
			    { data: 'next_payment_fiscal_quarter', searchable: true, render: $.datatables_utils.format_na },
			],
			order: [
				[ 9, "asc" ]
			]
		})
		.on('draw.dt', function() {
			var url = '<?php echo $this->basePath('contract/export/contracts/'); ?>';
			url += '?';
			
			var params = table.ajax.params();

			if(params["!status"]) {
				var val = params["!status"];
				if(typeof val != "string") {
					val = val.join();
				}
				url += '!status=' + val;
			}
			else {
				url += '!status=' + status_text_deleted;
			}

			if(params.status) {
				url += '&status=' + params.status;
			}

			if(params.search) {
				url += '&' + params.search.fields[0] + '=' + params.search.value;
			}
		});

		$('.dataTables_filter').prepend(
			"Status: "
			+ "<select id='status' name='status'>"
			+ "<option value='All'>All</option>"
			+ "<option value='Active' selected>Active</option>"
			+ "<option value='Closed'>Closed</option>"
			+ "</select> "
		);

		$(document).on('change', '#status', function() {
			table.draw();
		});

		$(document).on('change', '#user_id', function() {
			if($("#user_id").select2('val') != '') {
				table.draw();
			}
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<div class="row no-margin">
	<div class="widget-body no-padding">
		<div class="widget-table no-padding">
			<div class="alert alert-info">
				This feature is for Admins to quickly lookup & confirm which contracts a user is able to see.
			</div>
			<div class="form-horizontal">			
				<div class="form-group">
					<label class="col-sm-1 control-label no-padding-right" for="user_id">Lookup User:</label>
					<div class="col-sm-3" style="padding-top:7px;">
						<span class="block input-icon input-icon-right">
							<input type="text"
								   id="user_id"
								   name="user_id"
								   placeholder="User"
								   value="<?php echo $this->user_id; ?>"
								   class="width-100" />
						</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="space-12"></div>

<div class="row no-margin">
	<div class="widget-body no-padding">
		<div class="widget-table no-padding">
			<table id="contracts" class="table table-striped table-hover" width="100%">
				<thead>
					<tr>
						<th style="max-width: 140px;"></th>
						<th>Vendor</th>
						<th>Type</th>
						<th>Status</th>
						<th>Description</th>
						<th>Department</th>
						<th>Contract Number</th>
						<th>Start Date</th>
						<th>End Date</th>
						<th>Next Payment Amount</th>
						<th>Next Payment Date</th>
						<th style="max-width: 120px;">Next Payment Fiscal Year</th>
						<th style="max-width: 120px;">Next Payment Fiscal Quarter</th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
<?php $this->placeholder('content')->captureEnd(); ?>