<?php include(__DIR__ . "/../../layout/layout.phtml"); ?>

<?php $this->placeholder('breadcrumb')->captureStart('APPEND'); ?>
<li>
	<a href="<?php echo $this->basePath('contract/contracts/'); ?>">Contracts</a>
</li>
<?php $this->placeholder('breadcrumb')->captureEnd() ;?>

<?php $this->placeholder('heading')->captureStart('APPEND'); ?>
Contracts
<?php $this->placeholder('heading')->captureEnd() ;?>

<?php $this->placeholder('style')->captureStart(); ?>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/datepicker.min.css'); ?>" />
<?php $this->placeholder('style')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script src="<?php echo $this->basePath('assets/js/bootstrap-datepicker.min.js'); ?>"></script>
<?php $this->placeholder('script')->captureEnd(); ?>