<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
		<base target="_parent" />
        <?php
			$heading = $this->placeholder('heading')->getValue();
			if(empty($heading)) {
				$heading = '';
			} else if(is_array($heading)) {
				$heading = implode(" ", $heading);
			}
			
			echo $this->headTitle($this->translate($heading))->setSeparator(' - ')->setAutoEscape(false)		
		?>
        
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
		
		<link href="<?php echo $this->basePath('images/favicon.ico'); ?>" rel="shortcut icon" type="image/vnd.microsoft.icon" />
		<link href="<?php echo $this->basePath('assets/css/bootstrap.min.css'); ?>" media="screen" rel="stylesheet" type="text/css">
		<?php
			$font_awesome_version = $this->config()->getApplicationConfig('font_awesome');
			$font_awesome_version = (empty($font_awesome_version)) ? '4.2.0' : $font_awesome_version;
		?>
		<link href="<?php echo $this->basePath('assets/font-awesome/' . $font_awesome_version . '/css/font-awesome.min.css'); ?>" media="screen" rel="stylesheet" type="text/css">
		<link href="<?php echo $this->basePath('assets/fonts/fonts.googleapis.com.css'); ?>" media="screen" rel="stylesheet" type="text/css">
		
		<?php echo $this->placeholder('style'); ?>
		 
		<link href="<?php echo $this->basePath('assets/css/ace.min.css'); ?>" rel="stylesheet" type="text/css" class="ace-main-stylesheet" id="main-ace-style">
		
		<!--[if lt IE 9]>
		<link href="<?php echo $this->basePath('assets/css/ace-part2.min.css'); ?>" media="screen" rel="stylesheet" type="text/css">
		<![endif]-->
		
		<link href="<?php echo $this->basePath('assets/css/ace-rtl.min.css'); ?>" media="screen" rel="stylesheet" type="text/css">
			
		<!--[if lte IE 9]>
		<link href="<?php echo $this->basePath('assets/css/ace-ie.min.css'); ?>" media="screen" rel="stylesheet" type="text/css">
		<![endif]-->
		
		<?php echo $this->placeholder('style2'); ?>
		
		<style type="text/css">
			.twitter-typeahead {
				width: 100%;
			}
			.form-group .col-sm-5 .typeahead {
				padding-left: 6px;
			}
		</style>
		<?php echo $this->placeholder('prescript'); ?>
		
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script type="text/javascript" src="<?php echo $this->basePath('assets/js/html5shiv.min.js'); ?>"></script>
		<script type="text/javascript" src="<?php echo $this->basePath('/assets/js/respond.min.js'); ?>"></script>
		<![endif]-->
    </head>
	<body class="<?php echo $this->placeholder('bodyclass'); ?>">
		<?php echo $this->placeholder('content'); ?>
		
		<!--[if !IE]> -->
		<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.2.1.1.min.js'); ?>"></script>
		<!-- <![endif]-->
		
		<!--[if IE]>
		<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.1.11.1.min.js'); ?>"></script>
		<![endif]-->
		
		<script type="text/javascript">
			if('ontouchstart' in document.documentElement) document.write("<script src='<?php echo $this->basePath('assets/js/jquery.mobile.custom.min.js'); ?>'>"+"<"+"/script>");
		</script>
		
		<!-- Scripts -->		
		<?php echo $this->placeholder('script'); ?>
	</body>
</html>