<?php $this->placeholder('bodyclass')->set('no-skin'); ?>

<?php $this->placeholder('prescript')->captureStart('SET'); ?>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/ace-extra.min.js'); ?>"></script>
	<?php echo $this->placeholder('prescript'); ?>
<?php $this->placeholder('prescript')->captureEnd(); ?>

<?php $this->placeholder('style')->captureStart('SET'); ?>
	<link href="<?php echo $this->basePath('assets/css/jquery-ui.custom.min.css'); ?>" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->basePath('assets/css/chosen.min.css'); ?>" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->basePath('assets/css/select2.min.css'); ?>" rel="stylesheet" type="text/css" />
	<!--<link href="<?php echo $this->basePath('assets/css/dropzone.min.css'); ?>" rel="stylesheet" type="text/css" />-->
	<link href="<?php echo $this->basePath('assets/els/css/override.css'); ?>" rel="stylesheet" type="text/css" />
	<?php echo $this->placeholder('style'); ?>
	<style type="text/css">
		body {
			background-color: #FFFFFF !important;
		}
	</style>
<?php $this->placeholder('style')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart('SET'); ?>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/bootstrap.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.raty.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-ui.custom.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.ui.touch-punch.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/typeahead.jquery.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/bloodhound.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.validate.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/chosen.jquery.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/select2.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/bootstrap-tag.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/fuelux.spinner.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-dateFormat.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.number.min.js'); ?>"></script>
	<!--<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dropzone.min.js'); ?>"></script>-->	
	
	<?php echo $this->placeholder('pre-ace-script'); ?>
	
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/ace-elements.min.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo $this->basePath('assets/js/ace.min.js'); ?>"></script>
	<?php echo $this->placeholder('script'); ?>
<?php $this->placeholder('script')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<div class="main-container">
	<div class="main-content">
		<div class="main-content-inner">
			<div class="page-content no-padding">
				<!-- PAGE CONTENT BEGINS -->
				<?php echo $this->placeholder('content'); ?>
				<!-- PAGE CONTENT ENDS -->
			</div><!-- /.page-content -->
		</div>
	</div><!-- /.main-content -->
</div><!-- /.main-container -->
<?php $this->placeholder('content')->captureEnd(); ?>

<?php include("base.phtml"); ?>