<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var selects = [{
			id: 'assign_contacts_contacts',
			url: '<?php echo $this->basePath('contract/rest/vendor-contacts/'); ?>',
			identifier: 'id',
			display: 'description',
			onData: function(data) {
				data['vendor_id'] = '<?php echo $this->vendor_id; ?>';
				data['active'] = 1;
			}
		}];
		$.select2_utils.create(selects, 25, {
			multiple: true
		});
		
		$.validate_utils.create('#assign_contacts', {
			contacts: {
				required: true,
				message: 'Please select a support contact'
			}
		}, function(form) {
			$("#assign_contacts_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Assigning support contacts...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('contract/contracts/assign-contacts/' . $this->id); ?>',
				data: $(form).serializeArray()
			}).done(function(data) {
				$("#assign_contacts_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully assigned support contacts");
				
				setTimeout(function() {
					$("#assign_contacts_message").hide();						
					$("#assign-contacts-modal").modal('hide');
					
					if ($.fn.DataTable.isDataTable('#contacts')) {
						$("#contacts").dataTable().api().ajax.reload();
					}
				}, 1000);
			}).fail(function(error) {
				if (error.responseJSON && error.responseJSON['error']) {
					error = error.responseJSON['error'];
				} else {
					error = 'Unable to assign support contacts, try again';
				}
				
				$("#assign_contacts_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			return false;
		});
		
		$('#assign-contacts-modal').on('show.bs.modal', function(e) {
			// reset the fields
			$("#assign_contacts_contacts").select2('val', null);
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="assign-contacts-modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Assign Support Contacts
				</div>
			</div>
			<form id="assign_contacts" class="form-horizontal">
				<div class="modal-body">				
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								All fields with an <i class="ace-icon fa fa-asterisk red"></i> are required.  Select as many <strong>Support Contacts</strong> as desired.
							</div>
							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="assign_contacts_contacts">Support Contacts </label>
								<div class="col-sm-8">
									<span class="block input-icon input-icon-right">
										<input type="text"
											   id="assign_contacts_contacts"
											   name="assign_contacts_contacts"
											   placeholder="Support Contacts"
											   class="width-100" />
										<i class="ace-icon fa fa-asterisk red" style="margin-right: 15px;"></i>
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer align-left">
					<a class="btn btn-sm" href="#" data-dismiss="modal" aria-hidden="true">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</a>
					<button class="btn btn-sm btn-primary"
							type="submit">
						<i class="ace-icon fa fa-plus bigger-125"></i>
						Assign
					</button>
										
					<?php if ($this->authorization()->isPermitted('Contract::Vendors', 'add-contact')) { ?>
					<a href="<?php echo $this->basePath('contract/vendors/view/'.$this->vendor_id); ?>?onload=add-contact"
					   class="btn btn-sm btn-success pull-right"
					   id="bulk_add">
						<i class="ace-icon fa fa-plus bigger-125"></i>
						Add New Support Contact
					</a>
					<?php } ?>
					<div id="assign_contacts_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>