<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var selects = [{
			id: 'assign_labviews_labviews',
			url: '<?php echo $this->basePath('contract/rest/contracts/' . $this->id . '/available-labviews/'); ?>',
			display: 'name',
			onResult: function(item) {
                var text  = [item.name, item.description];
                
				return {
					id: item.id,
					text: text.join(' / ')
				};
			},
			onData: function(data) {
				data['name|description'] = data['name'];
			}
		}];
		
		$.select2_utils.create(selects, 25, {
			multiple: true
		});
		
		$.validate_utils.create('#assign_labviews', {
			labviews: {
				required: true,
				message: 'Please select a labview'
			}
		}, function(form) {
			$("#assign_labviews_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Assigning labviews...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('contract/contracts/assign-labviews/' . $this->id); ?>',
				data: $(form).serializeArray()
			}).done(function(data) {
				$("#assign_labviews_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully assigned labviews");
				
				setTimeout(function() {
					$("#assign_labviews_message").hide();						
					$("#assign-labviews-modal").modal('hide');
					
					if ($.fn.DataTable.isDataTable('#labviews')) {
						$("#labviews").dataTable().api().ajax.reload();
					}
				}, 1000);
			}).fail(function(error) {
				if (error.responseJSON && error.responseJSON['error']) {
					error = error.responseJSON['error'];
				} else {
					error = 'Unable to assign labviews, try again';
				}
				
				$("#assign_labviews_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			return false;
		});
		
		$('#assign-labviews-modal').on('show.bs.modal', function(e) {
			// reset the fields
			$("#assign_labviews_labviews").select2('val', null);
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="assign-labviews-modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Assign Labviews
				</div>
			</div>
			<form id="assign_labviews" class="form-horizontal">
				<div class="modal-body">				
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								All fields with an <i class="ace-icon fa fa-asterisk red"></i> are required.  Select as many <strong>Labviews</strong> as desired.
							</div>
							<div class="form-group">
								<label class="col-sm-2 control-label no-padding-right" for="assign_labviews_labviews">Labviews </label>
								<div class="col-sm-9">
									<span class="block input-icon input-icon-right">
										<input type="text"
											   id="assign_labviews_labviews"
											   name="assign_labviews_labviews"
											   placeholder="Labviews"
											   class="width-100" />
										<i class="ace-icon fa fa-asterisk red" style="margin-right: 15px;"></i>
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer align-left">
					<a class="btn btn-sm" href="#" data-dismiss="modal" aria-hidden="true">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</a>
					<button class="btn btn-sm btn-primary"
							type="submit">
						<i class="ace-icon fa fa-plus bigger-125"></i>
						Assign
					</button>
					<div id="assign_labviews_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>