<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = null;
		$("#documents_a").on('shown.bs.tab', function(e) {			
			if (!table) {
				table = $("#documents").DataTable({
					processing: true,
					serverSide: true,
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
							d['contract_id'] = '<?php echo $this->id; ?>';
						},
						url: "<?php echo $this->basePath('contract/rest/contract-documents/'); ?>"
					},
					oLanguage: {
						sEmptyTable: "No documents",
						sProcessing: "",
						sSearch: "Search",
						sSearchPlaceholder: "Search within..."
					},
					iDisplayLength: 50,
					stateSave: false,
					deferRender: true,
					searchDelay: 500,
					columns: [
						{ data: 'id', orderable: false, searchable: false, render: function(val, type, data, options) {
							var downloadHtml1 = '';
							
							if (parseInt(data.is_external, 10) == 0) {
								downloadHtml1 += "<a class='blue' href='<?php echo $this->basePath('contract/contract-documents/download/'); ?>" + val + "'>"
									+ "<i class='ace-icon fa fa-download bigger-130' title='Download this document'></i>"
								+ "</a>";
							}
							
							return "<div class='action-buttons'>"
										<?php if ($this->authorization()->isPermitted('Contract::ContractDocuments', 'delete')) { ?>
										+ "<a class='red' href='javascript: void(0);' onclick=\"deleteContractDocument('" + options.row + "')\">"
											+ "<i class='ace-icon fa fa-trash bigger-130' title='Delete this document'></i>"
										+ "</a>"
										<?php } ?>
										<?php if ($this->authorization()->isPermitted('Contract::ContractDocuments', 'download')) { ?>
										+ downloadHtml1								
										<?php } ?>
									+ "</div>";
						} },
						{ data: 'name', searchable: true, render: function(val, type, data) {
							val = (val == '' || val == null) ? 'N/A' : val;
							
							if (parseInt(data.is_external, 10) == 1) {
								// we should just show the link
								return '<a href="' + data.path + '">' + data.path + '</a>';
							} else {
								return val;
							}
						} }	
					],
					order: [[1, "asc"]],
					fnPreDrawCallback: function() {
						$("#documents_info").html("Loading documents...");
						return true;
					}
				});
			}
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="documents" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 80px;"></th>
					<th>Name</th>					
				</tr>
			</thead>
		</table>
	</div>
</div>