<?php $this->placeholder('style')->captureStart(); ?>
<style type="text/css">
	div.profile-info-value {
		border-top: none !important;
	}
</style>
<?php $this->placeholder('style')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		$("#edit_device").on('submit', function() {
			var id = $("#edit_device_id").val();
			var notes = $("#edit_device_notes").val();
			
			$("#edit_device_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Edit device...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('contract/contracts/edit-device/'); ?>',
				data: { 
					id: id,
					notes: notes
				}
			}).done(function(data) {
				$("#edit_device_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully edited device");
				
				setTimeout(function() {
					$("#edit_device_message").hide();					
					$("#edit-device-modal").modal('hide');
					
					if($.fn.DataTable.isDataTable('#devices')) {
                        // reload the devices table
                        $("#devices").dataTable().api().ajax.reload();
                    }
				}, 1000);
			}).fail(function(error) {
                if (error.responseJSON && error.responseJSON['error']) {
                    error = error.responseJSON['error'];
                } else {
                    error = 'Unable to edit device, try again';
                }
				
				$("#edit_device_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			
			// prevent the page submit
			return false;
		});
	});

	function editDevice(row) {
		$("#edit_device_message").hide();
		var data = $("#devices").dataTable().fnGetData(row);
		if (data) {
			var infodot = data.infodot;
			var serial = data.serial;
			var asset = data.asset;

			if(infodot == null || infodot == '') {
				infodot = 'N/A';
			}
			if(serial == null || serial == '') {
				serial = 'N/A';
			}
			if(asset == null || asset == '') {
				asset = 'N/A';
			}
			
			$("#edit_device_id").val(data.id);
			$("#edit_device_infodot").html(infodot);
			$("#edit_device_serial").html(serial);
			$("#edit_device_asset").html(asset);
			$("#edit_device_notes").val(data.notes);
	
			$('#edit-device-modal').modal('show');
		}
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="edit-device-modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Edit Device
				</div>
			</div>
			<form id="edit_device" class="form-horizontal">
				<div class="modal-body">				
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								Are you sure?  Click <strong>Edit</strong> to proceed and edit this device.
							</div>
							<input type="hidden" id="edit_device_id" name="id" value="" />

							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="edit_device_notes">Infodot </label>
								<div class="col-sm-8">
									<span class="block input-icon input-icon-right">
										<div class="profile-info-value">
											<span id="edit_device_infodot">
											</span>
										</div>
									</span>
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="edit_device_notes">S/N </label>
								<div class="col-sm-8">
									<span class="block input-icon input-icon-right">
										<div class="profile-info-value">
											<span id="edit_device_serial">
											</span>
										</div>
									</span>
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="edit_device_notes">Asset Tag </label>
								<div class="col-sm-8">
									<span class="block input-icon input-icon-right">
										<div class="profile-info-value">
											<span id="edit_device_asset">
											</span>
										</div>
									</span>
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right" for="edit_device_notes">Notes </label>
								<div class="col-sm-8">
									<span class="block input-icon input-icon-right">
										<textarea
											   name="edit_device_notes"
											   id="edit_device_notes"
											   placeholder="Notes"
											   class="scrollable width-100"></textarea>
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="space-6"></div>
				<div class="modal-footer">
					<button class="btn btn-sm pull-left"
							type="button"
							data-dismiss="modal">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</button>
					<button class="btn btn-sm btn-primary pull-left"
							type="submit">
						<i class="ace-icon fa fa-edit bigger-125"></i>
						Edit
					</button>
					<div id="edit_device_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>