<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = null;
		$("#labviews_a").on('shown.bs.tab', function() {
			if (!table) {
				table = $("#labviews").DataTable({
					processing: true,
					serverSide: true,			
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
						},
						url: "<?php echo $this->basePath('contract/rest/contracts/' . $this->id . '/labviews/'); ?>"
					},
					iDisplayLength: 25,
					stateSave: false,
					deferRender: true,
					searchDelay: 500,
					responsive: {
						details: {
							renderer: function(api, row, columns) {
								return $.datatables_utils.responsive_renderer(api, row, columns, table);
							}
						}
					},
					columns: [
					    { data: 'id', searchable: false, render: function(val, type, data, options) {
							return "<div class='inline pos-rel'>"
								+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
									+ "Actions "
									+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
								+ "</button>"
								+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>"
									<?php if($this->authorization()->isPermitted('Gem::Labviews', 'view')) { ?>
									+ "<li>"
										+ "<a data-rel='tooltip' href='<?php echo $this->basePath('gem/labviews/view/'); ?>" + data.id + "'>"
											+ "<span class='green'>"
												+ "<i class='ace-icon fa fa-image bigger-120'></i>"
												+ " View"
											+ "</span>"
										+ "</a>"
									+ "</li>"
									<?php } ?>
									<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'unassign-labview')) { ?>
									+ "<li>"
										+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"unassignLabview('" + options.row + "')\">"
											+ "<span class='red'>"
												+ "<i class='ace-icon fa fa-trash bigger-120'></i>"
												+ " Unassign"
											+ "</span>"
										+ "</a>"
									+ "</li>"
									<?php } ?>
								+ "</ul>"
							+ "</div>"; 
					    }},
						{ data: 'name', searchable: true },
						{ data: 'description', searchable: true }
					]
				});
			} else {
				table.responsive.recalc();
			}
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="labviews" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th>Name</th>
					<th>Description</th>
				</tr>
			</thead>
		</table>
	</div>
</div>