<?php $this->placeholder('style')->captureStart(); ?>
<style type="text/css">
	#payments_filter {
		display: none;
	}
	#payments_length {
		display: none;
	}
</style>
<?php $this->placeholder('style')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	var payment_type_text_renewal = 'Renewal';
	var payment_type_text_scheduled = 'Scheduled';
	
	$(document).ready(function() {
		var table = null;
		$("#payments_a").on('shown.bs.tab', function() {
			if (!table) {
				table = $("#payments").DataTable({
					serverSide: true,			
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
							d['contract_id'] = '<?php echo $this->id; ?>';
						},
						url: "<?php echo $this->basePath('contract/rest/payments/'); ?>"
					},
					iDisplayLength: 25,
					stateSave: false,
					deferRender: true,
					searchDelay: 500,
					responsive: {
						details: {
							renderer: function(api, row, columns) {
								return $.datatables_utils.responsive_renderer(api, row, columns, table);
							}
						}
					},
					columns: [
					    { data: 'id', orderable: false, searchable: false, render: function(val, type, data, options) {
							var str
								= "<div class='inline pos-rel'>"
									+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
										+ "Actions "
										+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
									+ "</button>"
									+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>";
							if(data.contract_next_payment_id==data.id) {
								if(data.payment_type==payment_type_text_scheduled) {
									<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'make-payment')) { ?>
									str+="<li>"
										+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"makePayment('" + options.row + "')\">"
											+ "<span class='green'>"
												+ "<i class='ace-icon fa fa-money bigger-120'></i>"
												+ " Mark as Paid"
											+ "</span>"
										+ "</a>"
									+ "</li>";
									<?php } ?>
								}
								else if(data.payment_type==payment_type_text_renewal) {
									<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'renew')) { ?>
									str += "<li>"
										+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"renewContractView('" + options.row + "')\">"
											+ "<span class='orange'>"
												+ "<i class='ace-icon fa fa-share bigger-120'></i>"
												+ " Renew"
											+ "</span>"
										+ "</a>"
									+ "</li>";
									<?php } ?>
								}
							}
									<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'edit-payment')) { ?>
									str	+= "<li>"
										+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"editPayment('" + options.row + "')\">"
												+ "<span class='blue'>"
													+ "<i class='ace-icon fa fa-edit bigger-120'></i>"
													+ " Edit"
												+ "</span>"
											+ "</a>"
										+ "</li>"
									<?php } ?>
									+ "</ul>"
								+ "</div>";

							return str; 
					    }},
					    { data: 'payment_number', searchable: true },
						{ data: 'payment_type', searchable: true },
						{ data: 'payment_date', searchable: true },
					    { data: 'amount', searchable: true }
					],
					order: [
						[ 1, "asc" ]
					],
					fnPreDrawCallback: function() {
						return true;
					}
				});
			} else {
				table.responsive.recalc();
			}
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="payments" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th style="min-width: 120px;">Payment #</th>
					<th style="min-width: 120px;">Payment Type</th>
					<th style="min-width: 120px;">Payment Date</th>
					<th style="min-width: 120px;">Amount</th>				
				</tr>
			</thead>
		</table>
	</div>
</div>