<?php $this->placeholder('bodyclass')->set('login-layout'); ?>

<?php
$font_color = $this->config()->getApplicationConfig('font_color');
$font_color = (empty($font_color)) ? 'red' : $font_color;
?>
<?php $this->placeholder('style')->captureStart(); ?>
<link href="<?php echo $this->basePath('assets/els/css/login.css'); ?>" rel="stylesheet" type="text/css" />
<?php $this->placeholder('style')->captureEnd(); ?>
<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	jQuery(function($) {
	 $(document).on('click', '.toolbar a[data-target]', function(e) {
		e.preventDefault();
		var target = $(this).data('target');
		$('.widget-box.visible').removeClass('visible');//hide others
		$(target).addClass('visible');//show target
	 });
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart(); ?>
<div class="main-container" style="background-image: url('<?php echo $this->basePath('assets/els/img/slide1-S.jpg'); ?>'); background-size: cover;">
	<div class="main-content">
		<?php echo $this->config()->getApplicationConfig('pre_login_msg'); ?>
		<div class="row" >
			<div class="col-sm-10 col-sm-offset-1">
				<?php echo $this->config()->getApplicationConfig('left_login_msg'); ?>
				<div class="login-container ">
					<div class="center">
						<h1>
							<?php echo $this->config()->getApplicationConfig('login_app_name'); ?>
						</h1>
					</div>

					<div class="space-6"></div>

					<div class="position-relative">
						<?php if($this->config()->getApplicationConfig('login_logo') !== false) { ?>
						<img src="<?php echo $this->basePath('assets/els/img/els.png'); ?>"
							 class="login-logo" />
						<?php } ?>
						<div id="login-box" class="login-box visible widget-box no-border">
							<div class="widget-body">
								<div class="widget-main">
									<h5 class="header <?php echo $font_color; ?> lighter bigger">
										<i class="ace-icon fa fa-desktop grey"></i>
										Login With Your Commescope Credentials
									</h5>
									<div class="space-6"></div>
									<form method="post">
										<fieldset>
											<label class="block clearfix">
												<span class="block input-icon input-icon-right">
													<input type="text"
														   name="username"
														   class="form-control"
														   placeholder="Username" />
													<i class="ace-icon fa fa-user"></i>
												</span>
											</label>

											<label class="block clearfix">
												<span class="block input-icon input-icon-right">
													<input type="password"
														   name="password"
														   class="form-control"
														   placeholder="Password" />
													<i class="ace-icon fa fa-lock"></i>
												</span>
											</label>

											<div class="space"></div>

											<div class="clearfix">
												<button type="submit" class="width-35 pull-right btn btn-sm btn-default">
													<i class="ace-icon fa fa-key"></i>
													<span class="bigger-110">Login</span>
												</button>
											</div>

											<?php if($this->errors) { ?>
												<div class="space"></div>
												<div class="alert alert-danger" style="padding: 5px;" role="alert">
												<?php
													if(is_array($this->errors)) {
														foreach($this->errors as $error) {
															echo "<strong>{$error}</strong><br />";
														}
													} else {
														echo "<strong>$this->errors</strong>";
													}
												?>
												</div>
											<?php } ?>
										</fieldset>
									</form>
								</div><!-- /.widget-main -->
							</div><!-- /.widget-body -->
						</div><!-- /.login-box -->
					</div><!-- /.position-relative -->

					<div class="space-6"></div>

					<div class="center">
						<h4 class="<?php echo $font_color; ?>" id="id-company-text">&copy; WWIE</h4>
					</div>
				</div>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.main-content -->

	<div class="footer layout_fullscreen">
		<div class="footer-inner">
			<div class="footer-content" style="border: none;">
				<?php $version = $this->config()->getApplicationConfig('version'); ?>
				<?php if($version) { ?>
				<span class="pull-right text-muted">
					<?php if ($this->config()->getApplicationConfig('enable_version_doc') !== false) { ?>
					<a href="<?php echo $this->basePath('documentations/release-notes.html'); ?>" target="_blank">
						<?php echo $version; ?>
					</a>
					<?php } else { ?>
						<?php echo $version; ?>
					<?php } ?>
				</span>
				<?php } ?>
			</div>
		</div>
	</div>
</div><!-- /.main-container -->
<?php $this->placeholder('content')->captureEnd(); ?>
