<?php $gem_ns = $this->config()->getConfig('auth', 'gem_ns'); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		$("#rights_level").ace_spinner({
			min: 0,
			max: parseInt('<?php echo max($this->authorization()->getRoles($gem_ns)); ?>', 10),
			step: 1,
			touch_spinner: ace.vars['touch'],
			btn_up_class: 'btn-info',
			btn_down_class: 'btn-info'
		}).closest('.ace-spinner')
		.css('width', '200px');
		
		$.validate_utils.create('#add_role', {
			name: {
				required: true,
				message: 'Please provide a Name'
			}
		}, function(form) {
			$("#add_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Adding role...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('auth/security/roles-add/'); ?>',
				data: $(form).serializeArray()
			}).done(function(data) {
				$("#add_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully added role");
				
				setTimeout(function() {
					$("#add_message").hide();					
					$("#add_role_modal").modal('hide');
					
					if ($.fn.DataTable.isDataTable('#roles')) {
						$("#roles").dataTable().api().ajax.reload();
					}
				}, 1000);
			}).fail(function(error) {
				if (error.responseJSON && error.responseJSON['error']) {
					error = error.responseJSON['error'];
				} else {
					error = 'Unable to add role, try again';
				}
				
				$("#add_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			
			// prevent the page submit
			return false;
		});
		
		$('#add_role_modal').on('show.bs.modal', function(e) {
			// reset the form
			$("#add_role")[0].reset();
		});		
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="add_role_modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Add New Role
				</div>
			</div>
			<form id="add_role" class="form-horizontal">
				<div class="modal-body">				
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								All fields with an <i class="ace-icon fa fa-asterisk red"></i> are required.
							</div>
							<div class="form-group">
								<label class="col-sm-2 control-label no-padding-right" for="name">Name </label>
								<div class="col-sm-9">
									<span class="block input-icon input-icon-right">
										<input type="text"
											   id="name"
											   name="name"
											   placeholder="Role name"
											   class="width-100" />
										<i class="ace-icon fa fa-asterisk red" style="margin-right: 15px;"></i>
									</span>
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-sm-2 control-label no-padding-right" for="description">Description </label>
								<div class="col-sm-9">
									<span class="block input-icon input-icon-right">
										<textarea id="description"
												  name="description"
												  placeholder="Role description"
												  class="width-100"></textarea>
									</span>
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-sm-2 control-label no-padding-right" for="rights_level">Rights Level</label>
								<div class="col-sm-9">
									<div class="row no-padding no-margin">
										<div class="col-sm-6 no-padding no-margin">
											<input name="rights_level"
												   id="rights_level"
												   value="0"
												   class="typeahead scrollable" />
										</div>
										<div class="col-sm-6 no-padding no-margin">
											<span class="text-muted">
												Can manage other Roles with lower Rights Level.
											</span>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer align-left">
					<a class="btn btn-sm" href="#" data-dismiss="modal" aria-hidden="true">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</a>
					<button class="btn btn-sm btn-primary"
							type="submit">
						<i class="ace-icon fa fa-plus bigger-125"></i>
						Add
					</button>
					<div id="add_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>