<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var fields = {
			permissions: {
				required: true,
				message: 'Please select a permission'
			}
		};
		
		$.validate_utils.create('#assign_permissions', fields, function(form) {
			$("#assign_permission_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Assigning permissions...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('auth/security/resources-assign-permissions/' . $this->id); ?>',
				data: $(form).serializeArray()
			}).done(function(data) {
				$("#assign_permission_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully assigned permissions");
				
				setTimeout(function() {
					// reset the permissions field
					$("#permissions").select2('val', null);
					$("#assign_permission_message").hide();						
					$("#assign_resource_permissions_modal").modal('hide');
					
					if ($.fn.DataTable.isDataTable('#resource_permissions')) {
						$("#resource_permissions").dataTable().api().ajax.reload();
					}
					
				}, 1000);
			}).fail(function(error) {
				$("#assign_permission_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html("Unable to assign permissions, try again");
			});
			return false;
		});
		
		var selects = [{
			id: 'permissions',
			url: '<?php echo $this->basePath('auth/rest/available-permissions/'); ?>',
			onData: function(data) {
				data['resource_id'] = '<?php echo $this->id; ?>';
			}
		}];
		
		$.select2_utils.create(selects, 25, {
			multiple: true
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="assign_resource_permissions_modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Assign Permissions
				</div>
			</div>
			<form id="assign_permissions" class="form-horizontal">
				<div class="modal-body">				
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								All fields with an <i class="ace-icon fa fa-asterisk red"></i> are required.  Select as many <strong>Permissions</strong> as desire.
							</div>
							<div class="form-group">
								<label class="col-sm-2 control-label no-padding-right" for="permissions">Permissions </label>
								<div class="col-sm-9">
									<span class="block input-icon input-icon-right">
										<input type="text"
											   id="permissions"
											   name="permissions"
											   placeholder="Permissions"
											   class="width-100" />
										<i class="ace-icon fa fa-asterisk red" style="margin-right: 15px;"></i>
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer align-left">
					<a class="btn btn-sm" href="#" data-dismiss="modal" aria-hidden="true">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</a>
					<button class="btn btn-sm btn-primary"
							type="submit">
						<i class="ace-icon fa fa-plus bigger-125"></i>
						Assign
					</button>
					<div id="assign_permission_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>