<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var selects = [{
			id: 'resources',
			url: '<?php echo $this->basePath('auth/rest/available-resources/'); ?>',
			onData: function(data) {
				data['order'] = [{
					column: 'controller',
					dir: 'asc'
				}, {
					column: 'action',
					dir: 'asc'
				}];
				data['permission_id'] = '<?php echo $this->id; ?>';
				data['controller|action'] = data['name'];
				delete data['name'];
			},
			onResult: function(item) {
				return {
					id: item.id,
					text: item.controller + ' >> ' + item.action
				};
			}
		}];
		$.select2_utils.create(selects, 25, {
			multiple: true
		});
		
		$.validate_utils.create('#assign_permission_resources', {
			resources: {
				required: true,
				message: 'Please select a resource'
			}
		}, function(form) {
			$("#assign_permission_resources_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Assigning resources...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('auth/security/permissions-assign-resources/' . $this->id); ?>',
				data: $(form).serializeArray()
			}).done(function(data) {
				$("#assign_permission_resources_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully assigned resources");
				
				setTimeout(function() {
					$("#assign_permission_resources_message").hide();						
					$("#assign_permission_resources_modal").modal('hide');
					
					if ($.fn.DataTable.isDataTable('#permission_resources')) {
						$("#permission_resources").dataTable().api().ajax.reload();
					}
				}, 1000);
			}).fail(function(error) {
				if (error.responseJSON && error.responseJSON['error']) {
					error = error.responseJSON['error'];
				} else {
					error = 'Unable to assign resources, try again';
				}
				
				$("#assign_permission_resources_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			return false;
		});
		
		$('#assign_permission_resources_modal').on('show.bs.modal', function(e) {
			// reset the fields
			$("#resources").select2('val', null);
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="assign_permission_resources_modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Assign Resources
				</div>
			</div>
			<form id="assign_permission_resources" class="form-horizontal">
				<div class="modal-body">				
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								All fields with an <i class="ace-icon fa fa-asterisk red"></i> are required.  Select as many <strong>Resources</strong> as desire.
							</div>
							<div class="form-group">
								<label class="col-sm-2 control-label no-padding-right" for="resources">Resources </label>
								<div class="col-sm-9">
									<span class="block input-icon input-icon-right">
										<input type="text"
											   id="resources"
											   name="resources"
											   placeholder="Resources"
											   class="width-100" />
										<i class="ace-icon fa fa-asterisk red" style="margin-right: 15px;"></i>
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer align-left">
					<a class="btn btn-sm" href="#" data-dismiss="modal" aria-hidden="true">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</a>
					<button class="btn btn-sm btn-primary"
							type="submit">
						<i class="ace-icon fa fa-plus bigger-125"></i>
						Assign
					</button>
					<div id="assign_permission_resources_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>