<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		$("#delete_permission").on('submit', function() {
			$("#delete_permission_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Deleting permission...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('auth/security/permissions-delete/'); ?>' + $("#delete_permission_id").val()
			}).done(function(data) {
				$("#delete_permission_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully deleted permission");
				
				setTimeout(function() {
					$("#delete_permission_message").hide();						
					$("#delete_permission_modal").modal('hide');
					
					if ($.fn.DataTable.isDataTable('#permissions')) {
						$("#permissions").dataTable().api().ajax.reload();
					}						
				}, 1000);
			}).fail(function(error) {
				if (error.responseJSON && error.responseJSON['error']) {
					error = error.responseJSON['error'];
				} else {
					error = 'Unable to delete permission, try again';
				}
				
				$("#delete_permission_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			
			// prevent the page submit
			return false;
		});
	});
	
	function deletePermission(row) {
		$("#delete_permission_message").hide();
		var data = $("#permissions").dataTable().fnGetData(row);
		if (data) {
			$("#delete_permission_id").val(data.id);
			$("#delete_name_value").html(data.name);
			$("#delete_description_value").html(data.description);
			
			$('#delete_permission_modal').modal('show');
		}
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="delete_permission_modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Delete Permission
				</div>
			</div>
			<form id="delete_permission" class="form-horizontal">
				<div class="modal-body">				
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								Are you sure?  Click <strong>Delete</strong> to proceed and delete this permission.
							</div>
							<input type="hidden" id="delete_permission_id" name="id" />
							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Name </div>
									<div class="profile-info-value">
										<span id="delete_name_value"></span>
									</div>
								</div>
								<div class="profile-info-row">
									<div class="profile-info-name"> Description </div>
									<div class="profile-info-value">
										<span id="delete_description_value"></span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="space-6"></div>
				<div class="modal-footer">
					<button class="btn btn-sm pull-left"
							type="button"
							data-dismiss="modal">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</button>
					<button class="btn btn-sm btn-danger pull-left"
							type="submit">
						<i class="ace-icon fa fa-trash bigger-125"></i>
						Delete
					</button>
					<div id="delete_permission_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>