<?php $gem_ns = $this->config()->getConfig('auth', 'gem_ns'); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = null;
		$("#resources_a").on('shown.bs.tab', function() {
			if (!table) {	
				table = $("#permission_resources").DataTable({
					processing: true,
					serverSide: true,
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
							d['permission_id'] = '<?php echo $this->id; ?>'
						},
						url: "<?php echo $this->basePath('auth/rest/resources/'); ?>"
					},
					oLanguage: {
						sEmptyTable: "No resources",
						sProcessing: "",
						sSearch: "Search",
						sSearchPlaceholder: "Search within..."
					},
					iDisplayLength: 10,
					stateSave: false,
					deferRender: true,
					searchDelay: 500,
					responsive: {
						details: {
							renderer: function(api, row, columns) {
								return $.datatables_utils.responsive_renderer(api, row, columns, table);
							}
						}
					},
					columns: [
						{ data: 'id', orderable: false, searchable: false, render: $.datatables_utils.format_empty, className: 'control' },
						{ data: 'id', orderable: false, searchable: false, render: function(val, type, data, options) {
							return "<div class='action-buttons'>"
										<?php if($this->authorization()->isPermitted('Auth::Security', 'permissions-unassign-resources', $gem_ns)) { ?>
										+ "<a class='red' role='button' href=\"javascript: unassignPermissionResource('" + options.row + "')\">"
											+ "<i class='ace-icon fa fa-close bigger-130' title='Unassign this resource'></i>"
										+ "</a>"
										<?php } ?>
									+ "</div>";
						} },
						{ data: 'controller', searchable: true, render: function(val, type, data, options) {
							return "<a href='<?php echo $this->basePath('auth/security/resources-edit/'); ?>" + data.id + "'>" + val + "</a>";
						} },
						{ data: 'action', searchable: true }				
					],
					order: [[2, "asc"]],
					fnPreDrawCallback: function() {
						$("#permission_resources_info").html("Loading resources...");
						return true;
					}
				});
			} else {
				table.responsive.recalc();
			}
		});
		
		$('#resources_a').trigger('shown.bs.tab');
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="permission_resources" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th style="min-width: 40px; max-width: 40px;"></th>
					<th style="min-width: 100px;">Controller</th>
					<th style="min-width: 100px;">Action</th>					
				</tr>
			</thead>
		</table>
	</div>
</div>
<?php if($this->authorization()->isPermitted('Auth::Security', 'permissions-unassign-resources', $gem_ns)) { ?>
<?php include(__DIR__ . "/unassign-permission-resource.phtml"); ?>
<?php } ?>