<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = null;
		$("#groups_a").on('shown.bs.tab', function() {
			if (!table) {				
				table = $("#role_groups").DataTable({
					processing: true,
					serverSide: true,
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
						},
						url: "<?php echo $this->basePath('auth/rest/groups/?role_id=' . $this->id); ?>"
					},
					oLanguage: {
						sEmptyTable: "No groups",
						sProcessing: "",
						sSearch: "Search",
						sSearchPlaceholder: "Search within..."
					},
					iDisplayLength: 10,
					stateSave: false,
					deferRender: true,
					responsive: {
						details: {
							renderer: function(api, row, columns) {
								return $.datatables_utils.responsive_renderer(api, row, columns, table);
							}
						}
					},
					columns: [
						{ data: 'role_id', orderable: false, searchable: false, render: $.datatables_utils.format_empty, className: 'control' },
						{ data: 'role_id', orderable: false, searchable: false, render: function(val, type, data, options) {
							return "<div class='action-buttons'>"
										<?php if($this->authorization()->isPermitted('Auth::Security', 'roles-unassign-groups', $gem_ns)) { ?>
										+ "<a class='red' role='button' href=\"javascript: unassignRoleGroup('" + options.row + "')\">"
											+ "<i class='ace-icon fa fa-close bigger-130' title='Unassign this group'></i>"
										+ "</a>"
										<?php } ?>
									+ "</div>";
						} },
						{ data: 'group', searchable: true, className: 'all' },
						{ data: 'domain', searchable: true, className: 'all' },
						{ data: 'users', orderable: false, searchable: false, className: 'center' },						
					],
					order: [[2, "asc"]],
					fnPreDrawCallback: function() {
						$("#role_groups_info").html("Loading groups...");
						return true;
					}
				});
			} else {
				table.responsive.recalc();
			}
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="role_groups" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th style="min-width: 40px; max-width: 40px;"></th>
					<th style="width: 100px;">Name</th>
					<th style="width: 100px;">Domain</th>
					<th style="width: 100px;"># Users</th>					
				</tr>
			</thead>
		</table>
	</div>
</div>
<?php include(__DIR__ . "/unassign-role-group.phtml"); ?>