<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = null;
		$("#users_a").on('shown.bs.tab', function() {
			if (!table) {
				table = $("#role_users").DataTable({
					processing: true,
					serverSide: true,
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
						},
						url: "<?php echo $this->basePath('auth/rest/users/?role_id=' . $this->id); ?>"
					},
					oLanguage: {
						sEmptyTable: "No users",
						sProcessing: "",
						sSearch: "Search",
						sSearchPlaceholder: "Search within..."
					},
					iDisplayLength: 10,
					stateSave: false,
					deferRender: true,
					searchDelay: 500,
					responsive: {
						details: {
							renderer: function(api, row, columns) {
								return $.datatables_utils.responsive_renderer(api, row, columns, table);
							}
						}
					},
					columns: [
						{ data: 'role_id', orderable: false, searchable: false, render: $.datatables_utils.format_empty, className: 'control' },
						{ data: 'role_id', orderable: false, searchable: false, render: function(val, type, data, options) {
							return "<div class='action-buttons'>"
										<?php if($this->authorization()->isPermitted('Auth::Security', 'roles-unassign-users')) { ?>
										+ "<a class='red' role='button' href=\"javascript: unassignRoleUser('" + options.row + "')\">"
											+ "<i class='ace-icon fa fa-close bigger-130' title='Unassign this user'></i>"
										+ "</a>"
										<?php } ?>
									+ "</div>";
						} },
						{ data: 'user', searchable: true },
						{ data: 'username', searchable: true },
						{ data: 'domain', searchable: true }
					],
					order: [[2, "asc"]],
					fnPreDrawCallback: function() {
						$("#role_users_info").html("Loading users...");
						return true;
					}
				});
			} else {
				table.responsive.recalc();
			}
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="role_users" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px"></th>
					<th style="min-width: 40px; max-width: 40px;"></th>
					<th style="min-width: 100px;">Name</th>
					<th style="min-width: 100px;">Username</th>
					<th style="min-width: 100px;">Domain</th>			
				</tr>
			</thead>
		</table>
	</div>
</div>
<?php include(__DIR__ . "/unassign-role-user.phtml"); ?>