<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = null;
		$("#exclude_roles_a").on('shown.bs.tab', function() {
			if (!table) {
				table = $("#role_exclude_roles").DataTable({
					processing: true,
					serverSide: true,
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
						},
						url: "<?php echo $this->basePath('auth/rest/exclude-roles/?role_id=' . $this->id); ?>"
					},
					oLanguage: {
						sEmptyTable: "No excluded roles",
						sProcessing: "",
						sSearch: "Search",
						sSearchPlaceholder: "Search within..."
					},
					iDisplayLength: 10,
					stateSave: false,
					deferRender: true,
					searchDelay: 500,
					responsive: {
						details: {
							renderer: function(api, row, columns) {
								return $.datatables_utils.responsive_renderer(api, row, columns, table);
							}
						}
					},
					columns: [
						{ data: 'id', orderable: false, searchable: false, render: $.datatables_utils.format_empty, className: 'control' },
						{ data: 'id', orderable: false, searchable: false, render: function(val, type, data, options) {
							return "<div class='action-buttons'>"
										+ "<a class='red' role='button' href=\"javascript: unassignRoleExcludeRole('" + options.row + "')\">"
											+ "<i class='ace-icon fa fa-close bigger-130' title='Unassign this role'></i>"
										+ "</a>"
									+ "</div>";
						} },
						{ data: 'exclude_role', searchable: true, render: function(val, type, data, options) {
							return "<a href='<?php echo $this->basePath('auth/security/roles-edit/'); ?>" + data.id + "'>" + val + "</a>";
						}  },
						{ data: 'exclude_description', searchable: true }
					],
					order: [[2, "asc"]],
					fnPreDrawCallback: function() {
						$("#role_exclude_roles_info").html("Loading roles...");
						return true;
					}
				});
				window.role_exclude_roles_build = true;
			} else {
				table.responsive.recalc();
			}
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="role_exclude_roles" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th style="min-width: 40px; max-width: 40px;"></th>
					<th style="min-width: 70px;">Role</th>
					<th style="min-width: 100px;">Description</th>					
				</tr>
			</thead>
		</table>
	</div>
</div>
<?php if($this->authorization()->isPermitted('Auth::Security', 'roles-assign-exclude-roles', $gem_ns)) { ?>
<?php include(__DIR__ . "/unassign-role-exclude-role.phtml"); ?>
<?php } ?>