<?php $gem_ns = $this->config()->getConfig('auth', 'gem_ns'); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = null;
		$("#permissions_a").on('shown.bs.tab', function() {
			if (!table) {				
				table = $("#role_permissions").DataTable({
					processing: true,
					serverSide: true,
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
							d['role_id'] = '<?php echo $this->id; ?>';
						},
						url: "<?php echo $this->basePath('auth/rest/permissions/'); ?>"
					},
					oLanguage: {
						sEmptyTable: "No permissions",
						sProcessing: "",
						sSearch: "Search",
						sSearchPlaceholder: "Search within..."
					},
					iDisplayLength: 10,
					stateSave: false,
					deferRender: true,
					searchDelay: 500,
					responsive: {
						details: {
							renderer: function(api, row, columns) {
								return $.datatables_utils.responsive_renderer(api, row, columns, table);
							}
						}
					},
					columns: [
						{ data: 'id', orderable: false, searchable: false, render: $.datatables_utils.format_empty, className: 'control' },
						{ data: 'id', orderable: false, searchable: false, render: function(val, type, data, options) {
							return "<div class='action-buttons'>"
										<?php if($this->authorization()->isPermitted('Auth::Security', 'roles-unassign-permissions', $gem_ns)) { ?>
										+ "<a class='red' role='button' href=\"javascript: unassignRolePermission('" + options.row + "')\">"
											+ "<i class='ace-icon fa fa-close bigger-130' title='Unassign this permission'></i>"
										+ "</a>"
										<?php } ?>
									+ "</div>";
						} },
						{ data: 'name', searchable: true, render: function(val, type, data, options) {
							return "<a href='<?php echo $this->basePath('auth/security/permissions-edit/'); ?>" + data.id + "'>" + val + "</a>";
						} },
						{ data: 'description', searchable: true },
						{ data: 'resources', orderable: false, searchable: false, sClass: 'center' }				
					],
					order: [[2, "asc"]],
					fnPreDrawCallback: function() {
						$("#role_permissions_info").html("Loading permissions...");
						return true;
					}
				});
			} else {
				table.responsive.recalc();
			}
		});
		
		$('#permissions_a').trigger('shown.bs.tab');
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="role_permissions" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th style="min-width: 40px; max-width: 40px;"></th>
					<th style="min-width: 100px;">Permission</th>
					<th style="min-width: 160px;">Description</th>
					<th style="min-width: 120px;"># Assigned Resources</th>					
				</tr>
			</thead>
		</table>
	</div>
</div>
<?php if($this->authorization()->isPermitted('Auth::Security', 'roles-unassign-permissions', $gem_ns)) { ?>
<?php include(__DIR__ . "/unassign-role-permission.phtml"); ?>
<?php } ?>