<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">	
	function unassignRolePermission(row) {		
		var data = $("#role_permissions").dataTable().fnGetData(row);
		if (data) {
			$("#unassign_role_permission_modal").modal('show');
			$("#unassign_role_permission_message")
				.show()
				.removeClass("alert-success")
				.removeClass("alert-danger")
				.addClass("alert-info")
				.html("Unassigning permission...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('auth/security/roles-unassign-permissions/' . $this->id); ?>',
				data: {
					permission_id: data.id
				}
			}).done(function(data) {
				$("#unassign_role_permission_message")
					.removeClass("alert-info")
					.addClass("alert-success")
					.html("Successfully unassigned permission");
				
				setTimeout(function() {
					$("#unassign_role_permission_message").hide();					
					$("#unassign_role_permission_modal").modal('hide');
					
					if ($.fn.DataTable.isDataTable('#role_permissions')) {
						$("#role_permissions").dataTable().api().ajax.reload();
					}
				}, 1000);
			}).fail(function(error) {
				if (error.responseJSON && error.responseJSON['error']) {
					error = error.responseJSON['error'];
				} else {
					error = 'Unable to unassign permission, try again';
				}
				
				$("#unassign_role_permission_message")
					.removeClass("alert-info")
					.addClass("alert-danger")
					.html(error);
			});
		}
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="unassign_role_permission_modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Unassign Permission
				</div>
			</div>
			<form id="unassign_permission" class="form-horizontal">
				<div class="modal-body">
					<div id="unassign_role_permission_message" style="display: none;" class="alert alert-info no-margin"></div>					
				</div>
			</form>
		</div>
	</div>
</div>