<?php $this->placeholder('style2')->captureStart(); ?>
<link href="<?php echo $this->basePath('assets/els/css/forecast.css'); ?>" rel="stylesheet" type="text/css">
<link href="<?php echo $this->basePath('assets/css/dataTables.fixedHeader.min.css'); ?>" rel="stylesheet" type="text/css">
<link href="<?php echo $this->basePath('assets/css/responsive.dataTables.min.css'); ?>" rel="stylesheet" type="text/css">
<link href="<?php echo $this->basePath('assets/els/css/dataTable.responsive.css'); ?>" rel="stylesheet" type="text/css">
<?php $this->placeholder('style2')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.tableTools.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.colVis.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.fixedHeader.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables/api/fnSetFilteringDelay.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/moment.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/moment-timezone.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.raty.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/els/js/datatables/utils.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/els/js/select2/utils.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/els/js/validate/utils.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive-tabs.js'); ?>"></script>
<script type="text/javascript">
    // disable the warning messages from datatable since we are relying on json attributes which may/maynot exists
    $.fn.dataTable.ext.errMode = 'none';
    // show only 3 number buttons on the paginator
    $.fn.dataTable.ext.pager.numbers_length = 5;
</script>
<?php $this->placeholder('script')->captureEnd(); ?>