<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		$('#edit_type').on('submit', function() {
			var id = $("#edit_type_id").val();
			var name = $("#edit_type_name").val();
			var active = $("#edit_type_active").val();
			
			$("#edit_type_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Editing contract type...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('contract/types/edit/'); ?>',
				data: { 
					id: id,
					name: name,
					active: active
				}
			}).done(function(data) {
				if (data.status == 1) {
					$("#edit_type_message")
						.removeClass("label-default")
						.addClass("label-success")
						.html("Successfully edited contract type");
					
					setTimeout(function() {
						$("#edit_type_message").hide();
						
						$("#edit-type-modal").modal('hide');
						reloadTypesTable();
					}, 1000);
				} else {
					$("#edit_type_message")
						.removeClass("label-default")
						.addClass("label-danger");
						
					if (data.error) {
						if ($.isArray(data.error)) {
							$("#edit_type_message").html(data.error.join('<br />'));
						} else {
							$("#edit_type_message").html(data.error);
						}
					} else {
						$("#edit_type_message").html("Unable to edit contract type, please try again");
					}
				}
			}).fail(function(error) {
				$("#edit_type_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html("Unable to edit contract type, please try again");
			});
			
			// prevent the page submit
			return false;
		});
	});
	
	function editType(row) {
		$("#edit_type_message").hide();
		var data = $("#types").dataTable().fnGetData(row);
		if (data) {
			$("#edit_type_id").val(data.id);
			$("#edit_type_name").val(data.name);
			if(data.active==1) {
				$("#edit_type_active").prop('checked', true);
			}
			else {
				$("#edit_type_active").prop('checked', false);
			}
					
			$('#edit-type-modal').modal('show');
		}
	}
	
	function reloadTypesTable() {
		$("#types").dataTable().api().ajax.reload();
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="edit-type-modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Edit Contract Type
				</div>
			</div>
			<form id="edit_type" class="form-horizontal">
				<div class="modal-body no-padding">				
					<div class="row no-padding no-margin">
						<div class="alert alert-warning">
							All fields with an <i class="ace-icon fa fa-asterisk red"></i> are required.  Provide the Contract Type name.
						</div>
					</div>
					<input type='hidden' id='edit_type_id' name='edit_type_id'>
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="edit_type_name">Contract Type </label>
						<div class="col-sm-8">
							<span class="block input-icon input-icon-right">
								<input type="text"
									   id="edit_type_name"
									   name="edit_type_name"
									   placeholder="Contract Type Name"
									   class="width-100" />
							</span>
						</div>
					</div>
					
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="edit_type_active">Active? </label>
						<div class="col-sm-8">
							<span class="block input-icon input-icon-right">
								<input name='edit_type_active'
									id='edit_type_active'
									type='checkbox'
									class='ace ace-switch ace-switch-2'
									value='1' />
								<span class='lbl' style='vertical-align: text-top;'></span>
							</span>
						</div>
					</div>
				</div>
				<div class="space-6"></div>
				<div class="modal-footer">
					<button class="btn btn-sm pull-left"
							type="button"
							data-dismiss="modal">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</button>
					<button class="btn btn-sm btn-primary pull-left"
							type="submit">
						<i class="ace-icon fa fa-check bigger-125"></i>
						Submit
					</button>
					<div id="edit_type_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>