<?php include(__DIR__ . "/layout/layout.phtml"); ?>

<?php $this->placeholder('breadcrumb')->captureStart('APPEND'); ?>
<li>
	Admin
</li>
<li>
	<a href="<?php echo $this->basePath('contract/types/'); ?>">Types</a>
</li>
<?php $this->placeholder('breadcrumb')->captureEnd(); ?>

<?php $this->placeholder('header')->captureStart('SET'); ?>
<div class="row">
	<div class="col-sm-8">
		<h1>
			Contracts
			<small>
				<i class="ace-icon fa fa-angle-double-right"></i>
				Contract Types
			</small>
		</h1>
	</div>
	<?php if ($this->authorization()->isPermitted('Contract::Types', 'add')) { ?>
	<div class="col-sm-4">
		<div class="align-right">
			<div class="btn-group" role="group">
				<a data-toggle='modal' data-target='#add-type-modal'  href='#' onclick="addType()"
				   class="btn btn-sm btn-primary">
					<i class="ace-icon fa fa-plus"></i>
					Add New
				</a>
			</div>
		</div>
	</div>
	<?php } ?>
</div>
<?php $this->placeholder('header')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = $("#types").dataTable({
			ajax: {
				url: "<?php echo $this->basePath('contract/rest/contract-types/'); ?>"
			},
			columns: [
			    { data: 'id', orderable: false, searchable: false, render: function(val, type, data, options) {
					var str
						= "<div class='inline pos-rel'>"
							+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
								+ "Actions "
								+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
							+ "</button>"
							+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>"
								<?php if ($this->authorization()->isPermitted('Contract::Types', 'edit')) { ?>
								+ "<li>"
									+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"editType('" + options.row + "')\">"
										+ "<span class='blue'>"
											+ "<i class='ace-icon fa fa-edit bigger-120'></i>"
											+ " Edit"
										+ "</span>"
									+ "</a>"
								+ "</li>"
								<?php } ?>
							+ "</ul>"
						+ "</div>";

					return str; 
			    }},
				{ data: 'name', searchable: true },
				{ data: 'active', searchable: false, render: $.datatables_utils.format_yesno  },
			]
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<div class="row no-margin">
	<div class="widget-body no-padding">
		<div class="widget-table no-padding">
			<table id="types" class="table table-striped table-hover">
				<thead>
					<tr>
						<th style="max-width: 140px;"></th>
						<th>Name</th>
						<th>Active?</th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
<?php include(__DIR__ . "/pane/add.phtml"); ?>
<?php include(__DIR__ . "/pane/edit.phtml"); ?>
<?php $this->placeholder('content')->captureEnd(); ?>