<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		$("#delete_schedule").on('submit', function() {
			$("#delete_schedule_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Deleting payment schedule...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('contract/payment-schedules/delete/'); ?>',
				data: { id: $("#delete_schedule_id").val() }
			}).done(function(data) {
				if (data.status == 1) {
					$("#delete_schedule_message")
						.removeClass("label-default")
						.addClass("label-success")
						.html("Successfully deleted payment schedule");
					
					setTimeout(function() {
						$("#delete_schedule_message").hide();
						$("#delete-schedule-modal").modal('hide');

						if($.fn.DataTable.isDataTable('#payment_schedules')) {
	                        // reload the schedules table
	                        $("#payment_schedules").dataTable().api().ajax.reload();
	                    }
					}, 1000);
				} else {
					$("#delete_schedule_message")
						.removeClass("label-default")
						.addClass("label-danger");
						
					if (data.error) {
						if ($.isArray(data.error)) {
							$("#delete_schedule_message").html(data.error.join('<br />'));
						} else {
							$("#delete_schedule_message").html(data.error);
						}
					} else {
						$("#delete_schedule_message").html("Unable to delete payment schedule, please try again");
					}
				}
			}).fail(function(error) {
                if (error.responseJSON && error.responseJSON['error']) {
                    error = error.responseJSON['error'];
                } else {
                    error = 'Unable to delete payment schedule, try again';
                }
				
				$("#delete_schedule_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			
			// prevent the page submit
			return false;
		});
	});
	
	function deleteSchedule(row) {
		$("#delete_schedule_message").hide();
		var data = $("#payment_schedules").dataTable().fnGetData(row);
		if (data) {
			$("#delete_schedule_id").val(data.id);
			$("#delete_schedule_name").html(data.name);
			$("#delete_schedule_next_payment_months").html(data.next_payment_months);
			
			$('#delete-schedule-modal').modal('show');
		}
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="delete-schedule-modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Delete Payment Schedule
				</div>
			</div>
			<form id="delete_schedule" class="form-horizontal">
				<div class="modal-body">				
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								Are you sure?  Click <strong>Delete</strong> to proceed and delete this payment schedule.
							</div>
							<input type="hidden" id="delete_schedule_id" name="delete_schedule_id" value="" />
							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Name </div>
									<div class="profile-info-value">
										<span id="delete_schedule_name">
										</span>
									</div>
								</div>
							</div>
							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Months Between Payments </div>
									<div class="profile-info-value">
										<span id="delete_schedule_next_payment_months">
										</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="space-6"></div>
				<div class="modal-footer">
					<button class="btn btn-sm pull-left"
							type="button"
							data-dismiss="modal">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</button>
					<button class="btn btn-sm btn-danger pull-left"
							type="submit">
						<i class="ace-icon fa fa-trash bigger-125"></i>
						Delete
					</button>
					<div id="delete_schedule_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>