<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var tab_active = false;
		$("#masters_a").on('shown.bs.tab', function(e) {
			if (!tab_active) {
				$("#masters").dataTable({
					processing: true,
					serverSide: true,
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
							d['ticket'] = '<?php echo $this->id; ?>';
							d['link_type'] = 'PARENT';
						},
						url: "<?php echo $this->basePath('ticket/rest/sub-tickets/'); ?>"
					},
					oLanguage: {
						sEmptyTable: "No masters",
						sProcessing: "",
						sSearch: "Search",
						sSearchPlaceholder: "Search within..."
					},
					iDisplayLength: 50,
					stateSave: false,
					deferRender: true,
					columns: [
						{ data: 'sub_ticket', searchable: true, render: function(val, type, data) {
							val = (val == '' || val == null) ? 'N/A' : val;
							<?php if ($this->authorization()->isPermitted('Ticket::Tickets', 'view')) { ?>
							return "<a href='<?php echo $this->basePath('ticket/tickets/view/'); ?>" + val + "'>" + val + "</a>";
							<?php } else { ?>
							return val;
							<?php } ?>
						} },
						{ data: 'title', searchable: true },
						{ data: 'status', searchable: true },
						{ data: 'assignees', searchable: true }
					],
					order: [[0, "asc"]],
					fnPreDrawCallback: function() {
						$("#masters_info").html("Loading masters...");
						return true;
					}
				}).fnSetFilteringDelay(500);
				tab_active = true;
			}
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="masters" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th>Ticket</th>
					<th>Title</th>
					<th>Status</th>
					<th>Assignee(s)</th>
				</tr>
			</thead>
		</table>
	</div>
</div>