<?php include(__DIR__ . "/../../layout/layout.phtml"); ?>

<?php $this->placeholder('breadcrumb')->captureStart('APPEND'); ?>
<li>
	<a href="<?php echo $this->basePath('contract/contracts/'); ?>">Contracts</a>
</li>
<?php $this->placeholder('breadcrumb')->captureEnd() ;?>

<?php $this->placeholder('heading')->captureStart('APPEND'); ?>
Contracts
<?php $this->placeholder('heading')->captureEnd() ;?>