<?php include(__DIR__ . "/layout/layout.phtml"); ?>

<?php $this->placeholder('heading')->captureStart(); ?>
Keys
<?php $this->placeholder('heading')->captureEnd() ;?>

<?php $this->placeholder('breadcrumb')->captureStart(); ?>
<li class="active">
	<a href="<?php echo $this->basePath('api/keys/'); ?>">Keys</a>
</li>
<?php $this->placeholder('breadcrumb')->captureEnd() ;?>

<?php $this->placeholder('header')->captureStart('SET'); ?>
<div class="row no-padding no-margin">
	<div class="col-sm-8 no-padding no-margin">
		<h1>
			API
			<small>
				<i class="ace-icon fa fa-angle-double-right"></i>
				Keys
			</small>
		</h1>
	</div>
	<div class="col-sm-4 no-padding no-margin">
		<div class="btn-toolbar no-padding no-margin" role="toolbar">
			<div class="btn-group pull-right" role="group">
				<?php if($this->authorization()->isPermitted('Api::Keys', 'add')) { ?>
				<a href="#"
				   class="btn btn-xs btn-primary"
				   data-toggle="modal"
				   data-target="#add_key_modal">
					<i class="ace-icon fa fa-plus"></i>
					Add New Key
				</a>
				<?php } ?>
			</div>
		</div>
	</div>
</div>
<?php $this->placeholder('header')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = $("#keys").DataTable({
			processing: true,
			serverSide: true,
			ajax: {
				data: function(d) {
                    $.datatables_utils.normalize_data(d);
                    d['active'] = 1;
                },
				url: "<?php echo $this->basePath('api/rest/keys/'); ?>"
			},
			oLanguage: {
				sEmptyTable: "No keys",
				sProcessing: "",
				sSearch: "Search",
				sSearchPlaceholder: "Search keys"
			},
			iDisplayLength: 25,
			stateSave: false,
			deferRender: true,
			searchDelay: 500,
			responsive: {
				details: {
					renderer: function(api, row, columns) {
						return $.datatables_utils.responsive_renderer(api, row, columns, table);
					}
				}
			},
			columns: [
				{ data: 'id', orderable: false, searchable: false, render: $.datatables_utils.format_empty, className: 'control' },
				{ data: 'id', orderable: false, searchable: false, render: function(val, type, data, options) {
					return "<div class='inline pos-rel'>"
							+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
								+ "Actions "
								+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
							+ "</button>"
							+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>"
                                <?php if($this->authorization()->isPermitted('Api::Keys', 'view')) { ?>
								+ "<li>"
									+ "<a role='button' href='<?php echo $this->basePath('api/keys/view/'); ?>" + val + "'>"
										+ "<span class='green'>"
											+ "<i class='ace-icon fa fa-image bigger-120'></i>"
											+ " View"
										+ "</span>"
									+ "</a>"
								+ "</li>"
								<?php } ?>
								<?php if($this->authorization()->isPermitted('Api::Keys', 'edit')) { ?>
								+ "<li>"
									+ "<a role='button' href='javascript: void(0);' data-rel='tooltip' onclick=\"editKey('" + options.row + "')\">"
										+ "<span class='blue'>"
											+ "<i class='ace-icon fa fa-edit bigger-120'></i>"
											+ " Edit"
										+ "</span>"
									+ "</a>"
								+ "</li>"
								<?php } ?>
								<?php if($this->authorization()->isPermitted('Api::Keys', 'delete')) { ?>
								+ "<li>"
									+ "<a role='button' href='javascript: void(0);' data-rel='tooltip' onclick=\"deleteKey('" + options.row + "')\">"
										+ "<span class='red'>"
											+ "<i class='ace-icon fa fa-trash bigger-120'></i>"
											+ " Delete"
										+ "</span>"
									+ "</a>"
								+ "</li>"
								<?php } ?>
                                <?php if($this->authorization()->isPermitted('Api::Keys', 'retire')) { ?>
								+ "<li>"
									+ "<a role='button' href='javascript: void(0);' data-rel='tooltip' onclick=\"retireKey('" + options.row + "')\">"
										+ "<span class='orange'>"
											+ "<i class='ace-icon fa fa-eye-slash bigger-120'></i>"
											+ " Retire"
										+ "</span>"
									+ "</a>"
								+ "</li>"
								<?php } ?>
							+ "</ul>"
						+ "</div>";
				}, sClass: 'action-col' },
				{ data: 'user', searchable: true, className: 'all' },
                { data: 'key', searchable: true, className: 'all', render: function(val, type, data, options) {
                    <?php if($this->authorization()->isPermitted('Api::Keys', 'view')) { ?>
                    return "<a href='<?php echo $this->basePath('api/keys/view/'); ?>" + data.id + "'>" + val + "</a>";
					<?php } else { ?>
					return val;
					<?php } ?>
                } },
				{ data: 'description', searchable: true, className: 'all' },
                { data: 'auto_configure', searchable: false, className: 'all', render: $.datatables_utils.format_yesno },
                { data: 'ctime', searchable: true, className: 'all', render: $.datatables_utils.format_date }
			],
			order: [[2, "asc"]],
			fnPreDrawCallback: function() {
				$("#keys_info").html("Updating keys...");
				return true;
			}
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="keys" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th style="width: 80px;"></th>
					<th style="min-width: 100px;">User</th>
					<th style="min-width: 100px;">Key</th>
                    <th style="min-width: 200px;">Description</th>
                    <th style="min-width: 100px;">Auto Configure</th>
                    <th style="min-width: 120px;">Created</th>
				</tr>
			</thead>
		</table>
	</div>
</div>
<?php if($this->authorization()->isPermitted('Api::Keys', 'add')) { ?>
<?php include(__DIR__ . "/pane/add.phtml"); ?>
<?php } ?>
<?php if($this->authorization()->isPermitted('Api::Keys', 'edit')) { ?>
<?php include(__DIR__ . "/pane/edit.phtml"); ?>
<?php } ?>
<?php if($this->authorization()->isPermitted('Api::Keys', 'delete')) { ?>
<?php include(__DIR__ . "/pane/delete.phtml"); ?>
<?php } ?>
<?php if($this->authorization()->isPermitted('Api::Keys', 'retire')) { ?>
<?php include(__DIR__ . "/pane/retire.phtml"); ?>
<?php } ?>
<?php $this->placeholder('content')->captureEnd(); ?>