<?php include(__DIR__ . "/layout/layout.phtml"); ?>

<?php
$this->formElementErrors()
	 ->setAttributes(array('class' => 'list-unstyled'));
?>

<?php $this->placeholder('heading')->captureStart(); ?>
View Key (<?php echo $this->formatter()->na($this->key['key']); ?>)
<?php $this->placeholder('heading')->captureEnd() ;?>

<?php $this->placeholder('breadcrumb')->captureStart(); ?>
<li class="active">
	<a href="<?php echo $this->basePath('api/keys/view/' . $this->id); ?>">View Key (<?php echo $this->formatter()->na($this->key['key']); ?>)</a>
</li>
<?php $this->placeholder('breadcrumb')->captureEnd() ;?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		fakewaffle.responsiveTabs(['xs']);
	});
	
	function refreshStats() {
		$('.stats-loading').html('<i class="ace-icon fa fa-spin fa-spinner"></i>');
		
		$.ajax({
			url: '<?php echo $this->basePath('api/rest/keys/' . $this->id); ?>?_=' + (new Date()).getTime()
		}).done(function(result) {
			if (result) {
				var total_service_methods = parseInt(result['total_service_methods'], 10);
				total_service_methods = (isNaN(total_service_methods)) ? 0 : total_service_methods;
				
				$('#total_service_methods_display').html(total_service_methods);				
			}
		}).error(function(error) {
			$('.stats-loading').html('<i class="ace-icon fa fa-warning red"></i>');
		});
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<?php $this->placeholder('header')->captureStart('SET'); ?>
<div class="row">
	<div class="col-xs-8">
		<h1>			
			<?php echo $this->formatter()->na($this->key['key']); ?>
		</h1>
	</div>
	<div class="col-xs-4 align-right">
		<div class="btn-group">
			<button type="button" class="btn btn-xs btn-inverse dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Actions
				<span class="ace-icon fa fa-caret-down icon-only"></span>
			</button>
			<ul class="dropdown-menu dropdown-inverse dropdown-white dropdown-menu-right">
				<?php if ($this->authorization()->isPermitted('Api::Keys', 'edit')) { ?>
				<li>
					<a href="#edit_key_modal"
					   data-toggle="modal">
						<i class="ace-icon fa fa-edit"></i>
						Edit
					</a>
				</li>
				<?php } ?>
				<?php if ($this->authorization()->isPermitted('Api::Keys', 'delete')) { ?>
				<li>
					<a href="#delete_key_modal"
					   data-toggle="modal">
						<i class="ace-icon fa fa-trash"></i>
						Delete
					</a>
				</li>
				<?php } ?>
                <?php if ($this->authorization()->isPermitted('Api::Keys', 'retire')) { ?>
				<li>
					<a href="#retire_key_modal"
					   data-toggle="modal">
						<i class="ace-icon fa fa-eye-slash"></i>
						Retire
					</a>
				</li>
				<?php } ?>
				
				<?php if ($this->authorization()->isPermitted('Api::Keys', 'edit')) { ?>
					<li class="divider"></li>
					<?php if (intval($this->key['auto_configure']) == 0) { ?>
					<li>
						<a href="#auto_configure_key_modal"
						   data-toggle="modal">
							<i class="ace-icon fa fa-gear"></i>
							Auto Configure
						</a>
					</li>
					<?php } else { ?>
					<li>
						<a href="#manual_configure_key_modal"
						   data-toggle="modal">
							<i class="ace-icon fa fa-gear"></i>
							Manual Configure
						</a>
					</li>
					<?php } ?>
				<?php } ?>
			</ul>
		</div>
	</div>
</div>
<?php $this->placeholder('header')->captureEnd(); ?>

<?php $this->placeholder('content')->captureStart('SET'); ?>
<div class="row">
	<div class="col-sm-6">
		<div class="widget-body">
			<div class="widget-main padding-12">
				<div class="row">
					<div class="col-xs-12 label label-lg label-default align-left">
						<b>Details</b>
					</div>
				</div>
				<div>
					<dl class="dl-horizontal">
						<dt>User</dt>
						<dd><?php echo $this->formatter()->na($this->key['user']); ?></dd>
						<dt>Description</dt>
						<dd><?php echo $this->formatter()->na($this->key['description']); ?></dd>
						<dt>Auto Configure</dt>
						<dd><?php echo $this->formatter()->yesno($this->key['auto_configure']); ?></dd>
						<dt>Created</dt>
						<dd><?php echo $this->formatter()->date($this->key['ctime']); ?></dd>
					</dl>
				</div>
			</div>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="widget-body">
			<div class="widget-main padding-12">
				<div class="row">
					<div class="col-xs-12 label label-lg label-info align-left">
						<b>Statistics</b>
					</div>
				</div>
				<div>
					<dl class="dl-horizontal">
						<dt># Services</dt>
						<dd>
							<?php if (intval($this->key['auto_configure']) == 0) { ?>
								<?php echo number_format($this->key['total_services'], 0); ?>
							<?php } else { ?>
								Auto Computed
							<?php } ?>
						</dd>
						<dt># Service Methods</dt>
						<dd>
							<?php if (intval($this->key['auto_configure']) == 0) { ?>
								<?php echo number_format($this->key['total_service_methods'], 0); ?>
							<?php } else { ?>
								Auto Computed
							<?php } ?>
						</dd>
					</dl>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row tabbable">
	<div class="col-xs-12">
		<?php if (intval($this->key['auto_configure']) == 0) { ?>
		<div class="btn-group pull-right bring-front">
			<button type="button" class="btn btn-xs btn-inverse dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Tab Actions
				<span class="ace-icon fa fa-caret-down icon-only"></span>
			</button>
			<ul class="dropdown-menu dropdown-inverse dropdown-white dropdown-menu-right">
				<?php if (intval($this->key['auto_configure']) == 0) { ?>
					<?php if ($this->authorization()->isPermitted('Api::Keys', 'assign-service-methods')) { ?>
					<li>
						<a href="#assign_service_methods_modal" data-toggle="modal">
							<i class="ace-icon fa fa-plus"></i>
							Assign Service Methods
						</a>
					</li>
					<?php } ?>
				<?php } ?>
			</ul>
		</div>
		<?php } ?>
		
		<ul class="nav nav-tabs responsive">
			<li>
				<a data-toggle="tab" href="#service_methods_pane" id="service_methods_a">Service Methods</a>
			</li>
		</ul>
		<div class="tab-content responsive">
			<div id="service_methods_pane" class="tab-pane fade in">
				<?php if (intval($this->key['auto_configure']) == 0) { ?>
					<?php include(__DIR__ . "/pane/service-methods.phtml"); ?>
				<?php } else { ?>
					<?php include(__DIR__ . "/pane/auto-service-methods.phtml"); ?>
				<?php } ?>
			</div>
		</div>
	</div>
</div>
<?php if ($this->authorization()->isPermitted('Api::Keys', 'edit')) { ?>
<?php include(__DIR__ . "/pane/edit.phtml"); ?>
<?php } ?>
<?php if ($this->authorization()->isPermitted('Api::Keys', 'delete')) { ?>
<?php include(__DIR__ . "/pane/delete.phtml"); ?>
<?php } ?>
<?php if ($this->authorization()->isPermitted('Api::Keys', 'retire')) { ?>
<?php include(__DIR__ . "/pane/retire.phtml"); ?>
<?php } ?>
<?php if ($this->authorization()->isPermitted('Api::Keys', 'assign-service-methods')) { ?>
<?php include(__DIR__ . "/pane/assign-service-methods.phtml"); ?>
<?php } ?>
<?php if ($this->authorization()->isPermitted('Api::Keys', 'assign-service-methods')) { ?>
<?php include(__DIR__ . "/pane/auto-configure.phtml"); ?>
<?php include(__DIR__ . "/pane/manual-configure.phtml"); ?>
<?php } ?>
<?php $this->placeholder('content')->captureEnd(); ?>