<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		$("#archive_contract").on('submit', function() {
			$("#archive_contract_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Archiving contract...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('contract/contracts/archive/'); ?>',
				data: { id: $("#archive_contract_id").val() }
			}).done(function(data) {
				$("#archive_contract_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully archived contract");
				
				setTimeout(function() {
					$("#archive_contract_message").hide();
					$("#archive-contract-modal").modal('hide');
					if($("#archive_contract_reload").val()==1) {
						location.reload();
					}
					
					if($.fn.DataTable.isDataTable('#contracts')) {
                        // reload the contracts table
                        $("#contracts").dataTable().api().ajax.reload();
                    }
				}, 1000);
			}).fail(function(error) {
                if (error.responseJSON && error.responseJSON['error']) {
                    error = error.responseJSON['error'];
                } else {
                    error = 'Unable to archive contract, try again';
                }
				
				$("#archive_contract_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			
			// prevent the page submit
			return false;
		});
	});
	
	function archiveContract(row) {
		$("#archive_contract_message").hide();
		var data = $("#contracts").dataTable().fnGetData(row);
		if (data) {
			var description = data.description;
			if(description == '') {
				description = 'N/A';
			}
			
			$("#archive_contract_id").val(data.id);
			$("#archive_contract_reload").val(0);
			$("#archive_contract_type").html(data.type);
			$("#archive_contract_vendor").html(data.vendor);
			$("#archive_contract_description").html(description);
			
			$('#archive-contract-modal').modal('show');
		}
	}

	function archiveContractView() {
		$("#archive_contract_message").hide();
		
		$("#archive_contract_id").val('<?php echo $this->id; ?>');
		$("#archive_contract_reload").val(1);
		$("#archive_contract_type").html('<?php echo $this->type; ?>');
		$("#archive_contract_vendor").html('<?php echo $this->vendor; ?>');
		$("#archive_contract_description").html('<?php echo $this->formatter()->na($this->description); ?>');
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="archive-contract-modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Archive Contract
				</div>
			</div>
			<form id="archive_contract" class="form-horizontal">
				<div class="modal-body">				
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								Are you sure?  Click <strong>Archive</strong> to proceed and archive this contract.
							</div>
							<input type="hidden" id="archive_contract_id" name="archive_contract_id" value="" />
							<input type="hidden" id="archive_contract_reload" name="archive_contract_reload" value="0" />
							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Vendor </div>
									<div class="profile-info-value">
										<span id="archive_contract_vendor">
										</span>
									</div>
								</div>
							</div>
							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Type </div>
									<div class="profile-info-value">
										<span id="archive_contract_type">
										</span>
									</div>
								</div>
							</div>
							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Description </div>
									<div class="profile-info-value">
										<span id="archive_contract_description">
										</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="space-6"></div>
				<div class="modal-footer">
					<button class="btn btn-sm pull-left"
							type="button"
							data-dismiss="modal">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</button>
					<button class="btn btn-sm btn-primary pull-left"
							type="submit">
						<i class="ace-icon fa fa-archive bigger-125"></i>
						Archive
					</button>
					<div id="archive_contract_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>