<?php
$gem_ns = $this->config()->getConfig('auth', 'gem_ns');
?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = null;
		$("#devices_a").on('shown.bs.tab', function() {
			if (!table) {
				table = $("#devices").DataTable({
					serverSide: true,			
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
							d['contract_id'] = '<?php echo $this->id; ?>';
						},
						url: "<?php echo $this->basePath('contract/rest/contract-devices/'); ?>"
					},
					iDisplayLength: 25,
					stateSave: false,
					deferRender: true,
					searchDelay: 500,
					responsive: {
						details: {
							renderer: function(api, row, columns) {
								return $.datatables_utils.responsive_renderer(api, row, columns, table);
							}
						}
					},
					columns: [
					    { data: 'id', searchable: false, render: function(val, type, data, options) {
							var str =
							 "<div class='inline pos-rel'>"
								+ "<button class='btn btn-minier btn-yellow dropdown-toggle' data-toggle='dropdown' data-position='auto'>"
									+ "Actions "
									+ "<i class='ace-icon fa fa-caret-down icon-only bigger-120'></i>"
								+ "</button>"
								+ "<ul class='dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close'>";
									<?php if($this->authorization()->isPermitted('Gem::Devices', 'view', $gem_ns)) { ?>
									if(data.device_id != null) {
										str += "<li>"
											+ "<a data-rel='tooltip' href='<?php echo $this->basePath('gem/devices/view/'); ?>" + data.device_id + "'>"
												+ "<span class='green'>"
													+ "<i class='ace-icon fa fa-image bigger-120'></i>"
													+ " View"
												+ "</span>"
											+ "</a>"
										+ "</li>";
									}
									<?php } ?>
									<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'edit-device')) { ?>
									str	+= "<li>"
										+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"editDevice('" + options.row + "')\">"
												+ "<span class='blue'>"
													+ "<i class='ace-icon fa fa-edit bigger-120'></i>"
													+ " Edit"
												+ "</span>"
											+ "</a>"
										+ "</li>"
									<?php } ?>
									<?php if ($this->authorization()->isPermitted('Contract::Contracts', 'remove-device')) { ?>
									str += "<li>"
										+ "<a data-rel='tooltip' href='javascript: void(0);' onclick=\"removeDevice('" + options.row + "')\">"
											+ "<span class='red'>"
												+ "<i class='ace-icon fa fa-trash bigger-120'></i>"
												+ " Remove"
											+ "</span>"
										+ "</a>"
									+ "</li>";
									<?php } ?>
								str += "</ul>"
							+ "</div>";

							return str;
					    }},
						{ data: 'infodot', searchable: true, render: function(val, type, data, options) {
							var str = '';
							if (data.device_id != null && data.device_id != '') {
								<?php if($this->authorization()->isPermitted('Gem::Devices', 'view', $gem_ns)) { ?>
								str = "<a href='<?php echo $this->basePath('gem/devices/view/'); ?>" + data.device_id + "'>"
										+ val
									+ "</a>";
								<?php } else { ?>
								str = val;
								<?php } ?>
							} else {
								str = 'N/A';
							}

							return str;
						} },
						{ data: 'serial', searchable: true, render: $.datatables_utils.format_na },
						{ data: 'asset', searchable: true, render: $.datatables_utils.format_na },
						{ data: 'site', searchable: true, render: $.datatables_utils.format_na },
						{ data: 'lab', searchable: true, render: $.datatables_utils.format_na },
						{ data: 'rack', searchable: true, render: $.datatables_utils.format_na },
						{ data: 'manufacturer', searchable: true, render: $.datatables_utils.format_na },
						{ data: 'model', searchable: true, render: $.datatables_utils.format_na },
						{ data: 'notes', searchable: true }
					],
					order: [
						[ 1, "asc" ]
					]
				});
			} else {
				table.responsive.recalc();
			}
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="devices" class="table table-striped table-hover" width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th style="min-width: 120px;">Infodot</th>
					<th style="min-width: 120px;">Serial</th>
					<th style="min-width: 120px;">Asset Tag</th>
					<th style="min-width: 120px;">Site</th>
					<th style="min-width: 120px;">Lab</th>
					<th style="min-width: 120px;">Rack</th>
					<th style="min-width: 120px;">Manufacturer</th>
					<th style="min-width: 120px;">Model</th>
					<th style="min-width: 120px;">Notes</th>
				</tr>
			</thead>
		</table>
	</div>
</div>