<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		$("#edit_payment").on('submit', function() {
			$("#edit_payment_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Edit payment...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('contract/contracts/edit-payment/'); ?>',
				data: { 
					id: $("#edit_payment_id").val(),
					amount: $("#edit_payment_amount").val(),
					payment_date: $("#edit_payment_date").val()
				}
			}).done(function(data) {
				$("#edit_payment_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully edited payment");
				
				setTimeout(function() {
					$("#edit_payment_message").hide();					
					$("#edit-payment-modal").modal('hide');
					
					if($.fn.DataTable.isDataTable('#payments')) {
                        // reload the payments table
                        $("#payments").dataTable().api().ajax.reload();
                    }
				}, 1000);
			}).fail(function(error) {
                if (error.responseJSON && error.responseJSON['error']) {
                    error = error.responseJSON['error'];
                } else {
                    error = 'Unable to edit payment, try again';
                }
				
				$("#edit_payment_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			
			// prevent the page submit
			return false;
		});

		$('.date-picker').datepicker({
			autoclose: true,
			todayHighlight: true,
			format: 'M d, yyyy'
		});
	});
	
	function editPayment(row) {
		$("#edit_payment_message").hide();
		var data = $("#payments").dataTable().fnGetData(row);
		if (data) {
			$("#edit_payment_id").val(data.id);
			$("#edit_payment_amount").val(data.amount);

			var date1 = data.payment_date;
			if(date1 != '0000-00-00') {
				date1 = new Date(date1);
				date1.setDate(date1.getDate() + 1);
				$('#edit_payment_date').datepicker('setDate', date1);
			}
					
			$('#edit-payment-modal').modal('show');
		}
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="edit-payment-modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Edit Payment
				</div>
			</div>
			<form id="edit_payment" class="form-horizontal">
				<div class="modal-body">				
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								Are you sure?  Click <strong>Edit</strong> to proceed and edit this payment.
							</div>
							<input type="hidden" id="edit_payment_id" name="id" value="" />
							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Amount </div>
									<div class="profile-info-value">
										<input type="text"
										   id="edit_payment_amount"
										   name="edit_payment_amount"
										   class="width-100" />
									</div>
								</div>
							</div>
							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Payment Date </div>
									<div class="profile-info-value">
										<input type="text"
											   id="edit_payment_date"
											   name="edit_payment_date"
											   class="form-control date-picker" />
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="space-6"></div>
				<div class="modal-footer">
					<button class="btn btn-sm pull-left"
							type="button"
							data-dismiss="modal">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</button>
					<button class="btn btn-sm btn-primary pull-left"
							type="submit">
						<i class="ace-icon fa fa-edit bigger-125"></i>
						Edit
					</button>
					<div id="edit_payment_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>