<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
$(document).ready(function() {
	$('#payment_calculator_calculate').click(function() {
		var total = $("#payment_calculator_total").val();
		var payments = $("#payment_calculator_payments").val();

		payments = parseInt(payments);
		total = total.replace(/[\$,]/g, '');
		total = parseFloat(total);
		total = total.toFixed(2);

		var each_payment = total/payments;
		each_payment = each_payment.toFixed(2);

		$("#payment_calculator_each").html(each_payment); 
	});

	$('#payment_calculator_populate').click(function() {

		var each = $("#payment_calculator_each").html();
		$("input.payment_amount").val(each);

		var renewal = each*1.1;
		renewal = renewal.toFixed(2);
		$("input.payment_amount_renewal").val(renewal);

		$("#payment-calculator-modal").modal('hide');
	});
});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="payment-calculator-modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Payment Calculator
				</div>
			</div>
			<div class="modal-body">				
				<div class="row">
					<div class="col-xs-12">
						<div class="profile-user-info">
							<div class="profile-info-row">
								<div class="profile-info-name"> Total Amount </div>
								<div class="profile-info-value">
									<input type='text'
										name='payment_calculator_total'
										id='payment_calculator_total'
										placeholder='0.00'
										value=''
										class='width-100' />
								</div>
							</div>
						</div>
						<div class="profile-user-info">
							<div class="profile-info-row">
								<div class="profile-info-name"> # Payments </div>
								<div class="profile-info-value">
									<input type='text'
										name='payment_calculator_payments'
										id='payment_calculator_payments'
										placeholder='1'
										value='<?php echo $this->payments_sans_renewal; ?>'
										class='width-100' />
								</div>
							</div>
						</div>
						<div class="profile-user-info">
							<div class="profile-info-row">
								<div class="profile-info-name"> Each Payment Amount </div>
								<div class="profile-info-value">
									<span id="payment_calculator_each">0.00
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="space-6"></div>
			<div class="modal-footer">
				<button class="btn btn-sm pull-left"
						type="button"
						data-dismiss="modal">
					<i class="ace-icon fa fa-remove bigger-125"></i>
					Cancel
				</button>
				<button class="btn btn-sm btn-success pull-left"
						id="payment_calculator_calculate"
						type="button">
					<i class="ace-icon fa fa-calculator bigger-125"></i>
					Calculate
				</button>
				
				<button class="btn btn-sm btn-primary pull-right"
						id="payment_calculator_populate"
						type="button">
					<i class="ace-icon fa fa-copy bigger-125"></i>
					Populate
				</button>
				<div id="payment_calculator_message" style="display: none;" class="pull-right label label-default"></div>
			</div>
		</div>
	</div>
</div>