<?php $this->placeholder('style')->captureStart(); ?>
<style type="text/css">
	#run_rate_filter {
		display: none;
	}
	#run_rate_length {
		display: none;
	}
</style>
<?php $this->placeholder('style')->captureEnd(); ?>

<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		var table = null;
		$("#run_rate_a").on('shown.bs.tab', function() {
			if (!table) {
				table = $("#run_rate").DataTable({
					serverSide: true,			
					ajax: {
						data: function(d) {
							$.datatables_utils.normalize_data(d);
							d['contract_id'] = '<?php echo $this->id; ?>';
						},
						url: "<?php echo $this->basePath('contract/rest/payment-run-rates/'); ?>"
					},
					iDisplayLength: 25,
					stateSave: false,
					deferRender: true,
					searchDelay: 500,
					responsive: {
						details: {
							renderer: function(api, row, columns) {
								return $.datatables_utils.responsive_renderer(api, row, columns, table);
							}
						}
					},
					columns: [
					    { data: 'id', orderable: false, searchable: false, render: function(val, type, data, options) {
							var str = "";

							return str; 
					    }},
					    { data: 'month_name', searchable: true },
					    { data: 'month', searchable: true },
						{ data: 'year', searchable: true },
						{ data: 'amount', searchable: true }
					],
					order: [
						[ 3, "asc" ],
						[ 2, "asc" ],
					]
				});
			} else {
				table.responsive.recalc();
			}
		});
	});
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div class="widget-body no-padding">
	<div class="widget-table no-padding">
		<table id="run_rate" class="table table-striped table-hover"  width="100%">
			<thead>
				<tr>
					<th style="width: 30px;"></th>
					<th>Month Name</th>
					<th>Month</th>
					<th>Year</th>
					<th>Amount</th>				
				</tr>
			</thead>
		</table>
	</div>
</div>