<?php $this->placeholder('script')->captureStart(); ?>
<script type="text/javascript">
	$(document).ready(function() {
		$("#unassign_labview").on('submit', function() {
			$("#unassign_labview_message")
				.show()
				.removeClass("label-success")
				.removeClass("label-danger")
				.addClass("label-default")
				.html("Unassigning labview...");
			
			$.ajax({
				type: 'POST',
				url: '<?php echo $this->basePath('contract/contracts/unassign-labview/'.$this->id); ?>',
				data: { 
					labview_id: $("#unassign_labview_labview_id").val() 
				}
			}).done(function(data) {
				$("#unassign_labview_message")
					.removeClass("label-default")
					.addClass("label-success")
					.html("Successfully unassigned labview");
				
				setTimeout(function() {
					$("#unassign_labview_message").hide();					
					$("#unassign-labview-modal").modal('hide');
					
					if($.fn.DataTable.isDataTable('#labviews')) {
                        // reload the labviews table
                        $("#labviews").dataTable().api().ajax.reload();
                    }
				}, 1000);
			}).fail(function(error) {
                if (error.responseJSON && error.responseJSON['error']) {
                    error = error.responseJSON['error'];
                } else {
                    error = 'Unable to unassign labview, try again';
                }
				
				$("#unassign_labview_message")
					.removeClass("label-default")
					.addClass("label-danger")
					.html(error);
			});
			
			// prevent the page submit
			return false;
		});
	});
	
	function unassignLabview(row) {
		$("#unassign_labview_message").hide();
		var data = $("#labviews").dataTable().fnGetData(row);
		if (data) {
			$("#unassign_labview_labview_id").val(data.id);
			$("#unassign_labview_name").html(data.name);
			$("#unassign_labview_description").html(data.description);
			
			$('#unassign-labview-modal').modal('show');
		}
	}
</script>
<?php $this->placeholder('script')->captureEnd(); ?>

<div id="unassign-labview-modal" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header no-padding">
				<div class="table-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="white">&times;</span>
					</button>
					Unassign Labview
				</div>
			</div>
			<form id="unassign_labview" class="form-horizontal">
				<div class="modal-body">				
					<div class="row">
						<div class="col-xs-12">
							<div class="alert alert-warning">
								Are you sure?  Click <strong>Unassign</strong> to proceed and unassign this labview.
							</div>
							<input type="hidden" id="unassign_labview_labview_id" name="unassign_labview_labview_id" value="" />
							
							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Name </div>
									<div class="profile-info-value">
										<span id="unassign_labview_name">
										</span>
									</div>
								</div>
							</div>
							
							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Description </div>
									<div class="profile-info-value">
										<span id="unassign_labview_description">
										</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="space-6"></div>
				<div class="modal-footer">
					<button class="btn btn-sm pull-left"
							type="button"
							data-dismiss="modal">
						<i class="ace-icon fa fa-remove bigger-125"></i>
						Cancel
					</button>
					<button class="btn btn-sm btn-danger pull-left"
							type="submit">
						<i class="ace-icon fa fa-trash bigger-125"></i>
						Unassign
					</button>
					<div id="unassign_labview_message" style="display: none;" class="pull-right label label-default"></div>
				</div>
			</form>
		</div>
	</div>
</div>